### ISSUE TITLE
When running the tests, is there a way to run two instances of Tron on the same machine

### ISSUE THREAD

**Issue by ajayt6** [tronprotocol/java-tron#10]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Start two instances of Tron from IDEA (i.e. run it twice) on the same machine. The idea is to test sending from one account to another.

2. What did you expect to see?
Two tron instances running successfully enabling testing of certain functions between the two instances.

3. What did you see instead?
Exception in thread "main" java.lang.RuntimeException: Can't initialize database
	at org.tron.datasource.leveldb.LevelDbDataSource.init(LevelDbDataSource.java:96)
	at org.tron.core.Blockchain.<init>(Blockchain.java:97)
	at org.tron.peer.Peer.initBlockchian(Peer.java:110)
	at org.tron.peer.Peer.init(Peer.java:96)
	at org.tron.peer.Peer.<init>(Peer.java:45)
	at org.tron.peer.Peer.getInstance(Peer.java:74)
	at org.tron.example.Tron.run(Tron.java:39)
	at org.tron.example.Tron.main(Tron.java:35)
Caused by: org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: C:\Users\IdeaProjects\java-tron\database-test\block_data\MANIFEST-000019: The handle is invalid.

	at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200)
	at org.fusesource.leveldbjni.internal.NativeDB.open(NativeDB.java:218)
	at org.fusesource.leveldbjni.JniDBFactory.open(JniDBFactory.java:168)
	at org.tron.datasource.leveldb.LevelDbDataSource.init(LevelDbDataSource.java:85)
	... 7 more

**Comment by sasaxie** [comment]
Database locked.
You can copy database-test directory and rename database-test-02, then update `java-tron/src/main/resources/tron.conf`

```conf
# database  directory
database {
  directory = "database-02" ## here
}

# database directory for test
database-test {
  directory = "database-test-02" # here
}
```

Run with parameter `--type normal`

**Comment by ajayt6** [comment]
This is working now. Duplicated the entire folder and ran an instance from there.
Thanks

**Comment by sasaxie** [comment]
You are welcome~

**Comment by RahulSarkar1992** [comment]
Hi,

I am facing the same issue.
can you please tell me where 

> Database locked.
> You can copy database-test directory and rename database-test-02, then update `java-tron/src/main/resources/tron.conf`
> 
> ```
> # database  directory
> database {
>   directory = "database-02" ## here
> }
> 
> # database directory for test
> database-test {
>   directory = "database-test-02" # here
> }
> ```
> Run with parameter `--type normal`

Hi,

I am facing the same issue, but not able to find the database-test directory.
can you please tell me the exact directory location of database-test.

Thanks,
