### ISSUE TITLE
Soliditynode synchronization failed

### ISSUE THREAD

**Issue by pangpangfeng** [tronprotocol/java-tron#1001]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Soliditynode synchronization failed

2. What did you expect to see?
no error

3. What did you see instead?
11:53:46.417 INFO  [pool-17-thread-3] [o.t.c.Wallet](Wallet.java:309) number: [0, 0, 0, 0, 0, 0, 0, 2] is not found!
11:53:47.040 INFO  [pool-17-thread-1] [o.t.c.Wallet](Wallet.java:309) number: [0, 0, 0, 0, 0, 0, 0, 2] is not found!
11:53:48.259 INFO  [pool-18-thread-1] [o.t.p.SolidityNode](SolidityNode.java:88) sync solidity block, lastSolidityBlockNum:1, remoteLastSolidityBlockNum:247
11:53:48.263 INFO  [pool-18-thread-1] [o.t.c.w.WitnessController](WitnessController.java:207) scheduledWitness:41f2fb1e7e5db5c29d6e25e1aa00f54760bd58bbab, currentSlot:509620348
11:53:48.263 WARN  [pool-18-thread-1] [o.t.c.w.WitnessController](WitnessController.java:161) Witness is out of order, scheduledWitness[41f2fb1e7e5db5c29d6e25e1aa00f54760bd58bbab],blockWitnessAddress[410be88a918d74d0dfd71dc84bd4abf036d0562991],blockTimeStamp[2018-06-13T11:37:30.000+08:00],slot[1]
11:53:48.263 ERROR [pool-18-thread-1] [o.t.c.d.Manager](Manager.java:735) validateWitnessSchedule error
org.tron.core.exception.ValidateScheduleException: validateWitnessSchedule error
        at org.tron.core.db.Manager.processBlock(Manager.java:1046)
        at org.tron.core.db.Manager.applyBlock(Manager.java:576)
        at org.tron.core.db.Manager.pushBlock(Manager.java:730)
        at org.tron.program.SolidityNode.syncSolidityBlock(SolidityNode.java:93)
        at org.tron.program.SolidityNode.lambda$start$0(SolidityNode.java:129)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
11:53:48.263 ERROR [pool-18-thread-1] [o.t.p.SolidityNode](SolidityNode.java:132) Error in sync solidity block validate schedule exception
org.tron.core.exception.BadBlockException: validate schedule exception
        at org.tron.program.SolidityNode.syncSolidityBlock(SolidityNode.java:99)
        at org.tron.program.SolidityNode.lambda$start$0(SolidityNode.java:129)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
11:53:48.420 INFO  [pool-17-thread-2] [o.t.c.Wallet](Wallet.java:309) number: [0, 0, 0, 0, 0, 0, 0, 2] is not found!
11:53:49.044 INFO  [pool-17-thread-4] [o.t.c.Wallet](Wallet.java:309) number: [0, 0, 0, 0, 0, 0, 0, 2] is not found!

**Comment by pangpangfeng** [comment]
In soliditynode  config.conf have 5 witnesses but in fact  only one witnesses。close
