### ISSUE TITLE
Trying To Run Mainnet Witness Node

### ISSUE THREAD

**Issue by ifelsefi** [tronprotocol/java-tron#1170]
Hi

I am trying to run a mainnet witness node.  

After doing ```git clone https://github.com/tronprotocol/java-tron.git```, setting up dependencies, and adding my private key into ```src/main/resources/config.conf```, I run:

`user@node[/opt/java-tron]$ ./gradlew run -Pwitness`

The error that I get:

> 
> Exception in thread "main" java.lang.IllegalArgumentException: Private key(**longkeyfromtronscan**) must be 64-bits hex string.
> 

The private key comes from [Tronscan](https://tronscan.org/) so I am unsure what to do at this point.  Will you please help me run a node on the Mainnet?

**Comment by kookiekrak** [comment]
@JusticeForMikeBrown can you try this format:

java -jar java-tron.jar -p your private key --witness -c your config.conf(Example：/data/java-tron/config.conf)

there might be a typo in the config file so it's failing to interpret it

**Comment by JusticeForMikeBrown** [comment]
Hi @kookiekrak 

```
me@laptop[/opt/java-tron]$ java -jar build/libs/java-tron.jar -p verylongley --witness -c src/main/resources/config.conf
Exception in thread "main" java.lang.IllegalArgumentException: Private key(verylongkey) must be 64-bits hex string.
	at org.tron.core.config.args.LocalWitnesses.validate(LocalWitnesses.java:63)
	at org.tron.core.config.args.LocalWitnesses.addPrivateKeys(LocalWitnesses.java:69)
	at org.tron.core.config.args.LocalWitnesses.<init>(LocalWitnesses.java:37)
	at org.tron.core.config.args.Args.setParam(Args.java:317)
	at org.tron.program.FullNode.main(FullNode.java:23)

```

**Comment by JusticeForMikeBrown** [comment]
OK @kookiekrak think I got it... I was using encrypted private key.

**Comment by JusticeForMikeBrown** [comment]
My firewall is configured to allow witness node port

![screenshot from 2018-09-06 08-57-21](https://user-images.githubusercontent.com/14250760/45158742-e93a3080-b1b2-11e8-885a-cfc147ab3822.png)

**Comment by JusticeForMikeBrown** [comment]
Using [deployment script ](https://github.com/tronprotocol/java-tron) I am now running FullNode on mainnet:

```
21:42:32.384 INFO  [pool-13-thread-1] [o.t.c.d.Manager](Manager.java:897) save block: BlockCapsule 
[ hash=000000000003df3f9454d6853b8243b3c6d39e27b0fb4a9e1184c9d3aed3f6d0
number=253759
parentId=000000000003df3e8cc1a1d8abecbac8cc9ffaad4a33ce06f6f85a27ddef13db
witness address=41318b2b6b4c7fcaa4b62f25a282329e1952a3c0d1
generated by myself=false
generate time=2018-07-03 17:23:45.0
txs are empty
]
21:42:32.384 INFO  [pool-13-thread-1] [o.t.c.n.n.NodeImpl](NodeImpl.java:799) Success handle block Num:253759,ID:000000000003df3f9454d6853b8243b3c6d39e27b0fb4a9e1184c9d3aed3f6d0
21:42:32.384 INFO  [pool-13-thread-1] [o.t.c.n.n.NodeImpl](NodeImpl.java:1283) update peer 142.44.137.53 block both we have Num:253759,ID:000000000003df3f9454d6853b8243b3c6d39e27b0fb4a9e1184c9d3aed3f6d0
21:42:32.384 INFO  [pool-13-thread-1] [o.t.c.n.n.NodeImpl](NodeImpl.java:1283) update peer 18.217.144.24 block both we have Num:253759,ID:000000000003df3f9454d6853b8243b3c6d39e27b0fb4a9e1184c9d3aed3f6d0
21:42:32.384 INFO  [pool-13-thread-1] [o.t.c.n.n.NodeImpl](NodeImpl.java:1283) update peer 52.15.142.111 block both we have Num:253759,ID:000000000003df3f9454d6853b8243b3c6d39e27b0fb4a9e1184c9d3aed3f6d0
21:42:32.384 INFO  [pool-13-thread-1] [o.t.c.n.n.NodeImpl](NodeImpl.java:1283) update peer 18.191.209.250 block both we have Num:253759,ID:000000000003df3f9454d6853b8243b3c6d39e27b0fb4a9e1184c9d3aed3f6d0
21:42:32.384 INFO  [pool-13-thread-1] [o.t.c.n.n.NodeImpl](NodeImpl.java:1283) update peer 35.183.78.98 block both we have Num:253759,ID:000000000003df3f9454d6853b8243b3c6d39e27b0fb4a9e1184c9d3aed3f6d0
21:42:32.384 INFO  [pool-13-thread-1] [o.t.c.n.n.NodeImpl](NodeImpl.java:1283) update peer 35.237.115.106 block both we have Num:253759,ID:000000000003df3f9454d6853b8243b3c6d39e27b0fb4a9e1184c9d3aed3f6d0
21:42:32.385 INFO  [pool-13-thread-1] [o.t.c.n.n.NodeImpl](NodeImpl.java:1283) update peer 71.34.1.169 block both we have Num:253759,ID:000000000003df3f9454d6853b8243b3c6d39e27b0fb4a9e1184c9d3aed3f6d0
21:42:32.385 INFO  [pool-13-thread-1] [o.t.c.n.n.NodeImpl](NodeImpl.java:1283) update peer 68.107.152.170 block both we have Num:253759,ID:000000000003df3f9454d6853b8243b3c6d39e27b0fb4a9e1184c9d3aed3f6d0
21:42:32.385 INFO  [pool-13-thread-1] [o.t.c.n.n.NodeImpl](NodeImpl.java:1283) update peer 18.130.99.124 block both we have Num:253759,ID:000000000003df3f9454d6853b8243b3c6d39e27b0fb4a9e1184c9d3aed3f6d0
```

However I still do not see my IP address on the map.  How can I fix?

**Comment by zk19862018** [comment]
The IP analysis is related to your device router or network operator.
