### ISSUE TITLE
Calling getBlocksByLimitNext in parallel returns wrong results

### ISSUE THREAD

**Issue by Rovak** [tronprotocol/java-tron#1425]
**Problem**

When calling `getBlockByLimitNext` in multiple threads the function will return the wrong results.

**Failing testcase**

A testcase which reproduces the problem can be found at https://github.com/Rovak/java-tron/blob/blocklimit-testcase/src/test/java/org/tron/core/WalletTest.java#L304

It calls the `getBlocksByLimitNext` function in multiple threads and it logs to console whenever the wrong blocks are returned.

In the log below the `IN` shows the start and end parameters with which the function was called. And the `OUT` shows the range of the blocks that was returned. 

Some noticeable things are:  
* `0 => 100` is being returned multiple times
* Some calls return in 0 blocks

```
IN  1 => 101
OUT 201 => 201
IN  101 => 201
OUT 201 => 201
IN  601 => 701
OUT 0 => 100
IN  501 => 601
OUT 0 => 100
IN  701 => 801
OUT 0 => 100
IN  901 => 1001
OUT 0 => 100
IN  1301 => 1401
OUT 1501 => 1601
IN  1501 => 1601
OUT 0 => 100
IN  1201 => 1301
OUT 0 => 100
IN  1601 => 1701
OUT 1701 => 1801
IN  2101 => 2201
IN  2001 => 2101
OUT 2007 => 2099
OUT 2201 => 2201
java.lang.Exception: NO BLOCKS FOR 1801 => 1901
	at org.tron.core.WalletTest.lambda$getBlocksByLimitMultiThreaded$2(WalletTest.java:319)
	at java.lang.Thread.run(Thread.java:748)
java.lang.Exception: NO BLOCKS FOR 1901 => 2001
	at org.tron.core.WalletTest.lambda$getBlocksByLimitMultiThreaded$2(WalletTest.java:319)
	at java.lang.Thread.run(Thread.java:748)
java.lang.Exception: NO BLOCKS FOR 2401 => 2501
	at org.tron.core.WalletTest.lambda$getBlocksByLimitMultiThreaded$2(WalletTest.java:319)
	at java.lang.Thread.run(Thread.java:748)
java.lang.Exception: NO BLOCKS FOR 2301 => 2401
	at org.tron.core.WalletTest.lambda$getBlocksByLimitMultiThreaded$2(WalletTest.java:319)
	at java.lang.Thread.run(Thread.java:748)
IN  2701 => 2801
OUT 0 => 100
IN  3101 => 3201
OUT 3201 => 3201
IN  3501 => 3601
OUT 0 => 100
IN  3401 => 3501
OUT 0 => 100
IN  3301 => 3401
OUT 0 => 100
IN  3901 => 4001
IN  3701 => 3801
OUT 3701 => 3801
OUT 3601 => 3701
java.lang.Exception: NO BLOCKS FOR 3801 => 3901
	at org.tron.core.WalletTest.lambda$getBlocksByLimitMultiThreaded$2(WalletTest.java:319)
	at java.lang.Thread.run(Thread.java:748)
java.lang.Exception: NO BLOCKS FOR 4101 => 4201
	at org.tron.core.WalletTest.lambda$getBlocksByLimitMultiThreaded$2(WalletTest.java:319)
	at java.lang.Thread.run(Thread.java:748)
IN  4601 => 4701
OUT 4701 => 4701
java.lang.Exception: NO BLOCKS FOR 4501 => 4601
	at org.tron.core.WalletTest.lambda$getBlocksByLimitMultiThreaded$2(WalletTest.java:319)
	at java.lang.Thread.run(Thread.java:748)
IN  4801 => 4901
OUT 0 => 100
java.lang.Exception: NO BLOCKS FOR 4901 => 5001
	at org.tron.core.WalletTest.lambda$getBlocksByLimitMultiThreaded$2(WalletTest.java:319)
	at java.lang.Thread.run(Thread.java:748)
java.lang.Exception: NO BLOCKS FOR 5201 => 5301
	at org.tron.core.WalletTest.lambda$getBlocksByLimitMultiThreaded$2(WalletTest.java:319)
	at java.lang.Thread.run(Thread.java:748)
java.lang.Exception: NO BLOCKS FOR 5601 => 5701
	at org.tron.core.WalletTest.lambda$getBlocksByLimitMultiThreaded$2(WalletTest.java:319)
	at java.lang.Thread.run(Thread.java:748)
java.lang.Exception: NO BLOCKS FOR 5001 => 5101
	at org.tron.core.WalletTest.lambda$getBlocksByLimitMultiThreaded$2(WalletTest.java:319)
	at java.lang.Thread.run(Thread.java:748)
IN  5101 => 5201
OUT 0 => 100
IN  6001 => 6101
OUT 6101 => 6101
IN  6201 => 6301
OUT 0 => 100
IN  6401 => 6501
OUT 0 => 100
java.lang.Exception: NO BLOCKS FOR 5901 => 6001
	at org.tron.core.WalletTest.lambda$getBlocksByLimitMultiThreaded$2(WalletTest.java:319)
	at java.lang.Thread.run(Thread.java:748)
IN  6501 => 6601
OUT 6601 => 6601
IN  6801 => 6901
OUT 6901 => 6901
IN  7201 => 7301
OUT 7301 => 7301
java.lang.Exception: NO BLOCKS FOR 7101 => 7201
	at org.tron.core.WalletTest.lambda$getBlocksByLimitMultiThreaded$2(WalletTest.java:319)
	at java.lang.Thread.run(Thread.java:748)
IN  7401 => 7501
OUT 0 => 100
IN  7501 => 7601
OUT 0 => 100
IN  7601 => 7701
OUT 0 => 100
IN  7701 => 7801
OUT 0 => 100
IN  8001 => 8101
OUT 7901 => 7901
IN  7801 => 7901
OUT 7901 => 8001
IN  8201 => 8301
OUT 0 => 100
IN  8101 => 8201
OUT 0 => 100
IN  8301 => 8401
OUT 0 => 100
IN  8501 => 8601
IN  8401 => 8501
OUT 8401 => 8501
OUT 0 => 100
IN  8701 => 8801
OUT 8601 => 8701
IN  8801 => 8901
OUT 8901 => 9001
```

**Comment by zhaohong** [comment]
thanks!

**Comment by Shrey33** [comment]
@Rovak can you tell me the reproduction steps ?

**Comment by Rovak** [comment]
@Shrey33 Here is a link to a unit test that reproduces the problem. https://github.com/Rovak/java-tron/blob/blocklimit-testcase/src/test/java/org/tron/core/WalletTest.java#L304

**Comment by Shrey33** [comment]
@Rovak thanks for an update

**Comment by Shrey33** [comment]
@Rovak can you tell me the impact of this problem ?

**Comment by Rovak** [comment]
I use `getBlocksByLimitNext` in https://tronscan.org to import the blockchain because it has better performance then calling `getBlockByNum` for every block. The impact is that i can no longer call `getBlocksByLimitNext` and that importing the blockchain now takes a few hours instead of 30 minutes. 

Also this bug makes the function `getBlocksByLimitNext` highly unreliable and unusable when more then a few clients are trying to call the function at the same time.

**Comment by sean-liu55** [comment]
https://github.com/tronprotocol/java-tron/pull/1460
@Rovak , Already fixed, please try again

**Comment by Rovak** [comment]
I've merged the fix you referenced into the testcase and it no longer returns wrong results. Thanks!
