### ISSUE TITLE
Tron syncing stuck at a particular blocknumber

### ISSUE THREAD

**Issue by jatin7413** [tronprotocol/java-tron#1626]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Hi,
I started tron as FullNode on my server. It was in sync with the blockchain and i was able to make transactions.
However, the syncing stopped at blocknumber 3244924 and ever since no block is being synced.
The error is saw in logs is -

`ERROR [pool-7-thread-1] [o.t.c.n.n.NodeImpl](NodeImpl.java:771) We get a bad block Num:3244925,ID:000000000031837d48daca07b2ae75d4ab875baeba0110ede66adb763ce0e678, reason is Contract Execute exception,not yet hard forked
`
I deleted the output-directory and started the syncing from zero, everything was good till block 3244924, but after that same issue occured and blocks are not getting downloaded.
The downloading of blocks is stopped
Logs - 
```
MyHeadBlockNum: 3244924
advObjToSpread: 0
advObjToFetch: 0
advObjWeRequested: 0
unSyncNum: 167839
blockWaitToProc: 3999
blockJustReceived: 0
syncBlockIdWeRequested: 4000

```

Please suggest what can I do ?

**Comment by Shrey33** [comment]
@jatin7413 can you provide some more detail ?

**Comment by jotto** [comment]
I have same issue, block: 3244924, date: 2018-10-16T09:21:30.000Z ( 1539681690000 )

**Comment by jotto** [comment]
```
19:36:34.596 ERROR [pool-8-thread-1] [o.t.c.d.Manager](Manager.java:810) not yet hard forked
org.tron.core.exception.ContractExeException: not yet hard forked
	at org.tron.common.utils.ForkController.hardFork(ForkController.java:70)
	at org.tron.core.db.Manager.processTransaction(Manager.java:950)
	at org.tron.core.db.Manager.processBlock(Manager.java:1191)
	at org.tron.core.db.Manager.applyBlock(Manager.java:617)
	at org.tron.core.db.Manager.pushBlock(Manager.java:807)
	at org.tron.core.net.node.NodeDelegateImpl.handleBlock(NodeDelegateImpl.java:71)
	at org.tron.core.net.node.NodeImpl.processSyncBlock(NodeImpl.java:763)
	at org.tron.core.net.node.NodeImpl.lambda$handleSyncBlock$27(NodeImpl.java:560)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.tron.core.net.node.NodeImpl.handleSyncBlock(NodeImpl.java:535)
	at org.tron.core.net.node.NodeImpl.lambda$activeTronPump$9(NodeImpl.java:393)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
19:36:34.599 ERROR [pool-8-thread-1] [o.t.c.n.n.NodeImpl](NodeImpl.java:771) We get a bad block Num:3112628,ID:00000000002f7eb4d5c862a4af3e003a40af806b24302cf7ae73259e3ac75ab0, reason is Contract Execute exception,not yet hard forked
```

**Comment by jotto** [comment]
I was on 3.1.1 when it happened, I updated to 3.1.3 but it didn't help

**Comment by tjchern** [comment]
ok, it looks like the database's problem, so you can resolve it step by step as follow:
1.  use kill -15 to shutdown the node.
2. delete the datebase(output-directory default)
3. upgrade the configeration file https://github.com/tronprotocol/tron-deployment. 
4. you can use our offical data dump http://47.89.178.46/, so that  you don't have to resync. of course you can also sync from the genesis block by yourself
5. restart the node
