### ISSUE TITLE
solidity node error, stop at 4727894

### ISSUE THREAD

**Issue by bitcodernull** [tronprotocol/java-tron#1828]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

solidity node error, can not sync

2. What did you expect to see?

sync

3. What did you see instead?

not sync
there are errors in log:
org.tron.core.exception.ReceiptCheckErrException: Different resultCode
	at org.tron.core.db.TransactionTrace.check(TransactionTrace.java:218)
	at org.tron.core.db.Manager.processTransaction(Manager.java:1053)
	at org.tron.core.db.Manager.processBlock(Manager.java:1271)
	at org.tron.core.db.Manager.applyBlock(Manager.java:679)
	at org.tron.core.db.Manager.pushBlock(Manager.java:875)
	at org.tron.core.db.Manager.pushVerifiedBlock(Manager.java:666)
	at org.tron.program.SolidityNode.loopProcessBlock(SolidityNode.java:232)
	at org.tron.program.SolidityNode.processBlock(SolidityNode.java:200)
	at org.tron.program.SolidityNode.lambda$start$3(SolidityNode.java:76)
	at java.lang.Thread.run(Thread.java:748)
12:39:32.013 ERROR [Thread-67] [o.t.p.SolidityNode](SolidityNode.java:236) Failed to process block 4727875.

**Comment by benjaminchencobinhood** [comment]
Do you mean that the database of solidity can not be used anymore?
Or just update the binary to v3.2.1?

**Comment by zhaohong** [comment]
use binary v3.2.1 soliditynode and fullnode data.
Or you can use v3.2.1.1 soliditynode and soliditydata.
we will release 3.2.1.1 soon.

**Comment by bitcodernull** [comment]
i have updated to  v3.2.1 and got the errors above

**Comment by bitcodernull** [comment]
i have updated to v3.2.1.1, the solidty node still can not sync
the error is the same as above

**Comment by wmroar** [comment]
> use binary v3.2.1 soliditynode and fullnode data.
> Or you can use v3.2.1.1 soliditynode and soliditydata.
> we will release 3.2.1.1 soon.

I met this issue too
this tx resultCode in self: OUT_OF_ENERGY
07:40:35.616 ERROR [pool-10-thread-1] [o.t.c.d.Manager](Manager.java:878) Different resultCode
org.tron.core.exception.ReceiptCheckErrException: Different resultCode
        at org.tron.core.db.TransactionTrace.check(TransactionTrace.java:218)
        at org.tron.core.db.Manager.processTransaction(Manager.java:1053)
        at org.tron.core.db.Manager.processBlock(Manager.java:1272)
        at org.tron.core.db.Manager.applyBlock(Manager.java:679)
        at org.tron.core.db.Manager.pushBlock(Manager.java:875)
        at org.tron.core.net.node.NodeDelegateImpl.handleBlock(NodeDelegateImpl.java:71)
        at org.tron.core.net.node.NodeImpl.processSyncBlock(NodeImpl.java:788)
        at org.tron.core.net.node.NodeImpl.lambda$handleSyncBlock$27(NodeImpl.java:571)
        at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
        at org.tron.core.net.node.NodeImpl.handleSyncBlock(NodeImpl.java:546)
        at org.tron.core.net.node.NodeImpl.lambda$activeTronPump$9(NodeImpl.java:403)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
07:40:35.618 ERROR [pool-10-thread-1] [o.t.c.n.n.NodeImpl](NodeImpl.java:796) We get a bad block Num:4727894,ID:0000000000482456a9d91ace77bda1ede7fa7c406d96bf156777d4cb6c7f11a4, reason is TransactionTrace Exception,Different resultCode

**Comment by zhaohong** [comment]
please use fullnode data and use 3.2.1 code.

**Comment by Yrp** [comment]
We have solved this problem, please upgrade to [Odyssey-v3.2.1.2](https://github.com/tronprotocol/java-tron/releases/tag/Odyssey-v3.2.1.2)

**Comment by myitlabro** [comment]
Thank you ! I had the same issue like wmroar and after updating it started to work again.

**Comment by wusuimantou** [comment]
不行，启动之后 获取节点一直都是nil，是因为节点配置改了吗？
Active peers
============
Other connected peers
============

16:03:37.500 INFO  [main] [o.t.c.n.n.NodeImpl](NodeImpl.java:701) other peer is nil, please wait ... 
16:03:37.508 INFO  [pool-1-thread-1] [o.t.c.n.n.NodeImpl](NodeImpl.java:605) LocalNode stats:
============
MyHeadBlockNum: 0
advObjToSpread: 0
advObjToFetch: 0
advObjWeRequested: 0
unSyncNum: 0
blockWaitToProc: 0
blockJustReceived: 0
syncBlockIdWeRequested: 0

**Comment by zhaohong** [comment]
@wusuimantou  could you please open a new issue and provide more information? thanks.
