### ISSUE TITLE
Return array as output of function call

### ISSUE THREAD

**Issue by chuang39** [tronprotocol/java-tron#1896]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

https://github.com/cyrusadkisson/solidity-baby-steps/blob/master/contracts/60_array_receiver_and_returner.sol

When I follow examples of solidity above to return array as output and deploy the contract, I get following error of contract deployment in Tron studio.

Caused by: java.lang.UnsupportedOperationException: Unsupported type encountered: uint8[7]
        at org.tron.abi.datatypes.generated.AbiTypes.getTypeReference(AbiTypes.java:742)
        at org.tron.studio.ui.RightTabRunController.getContractRunPanel(RightTabRunController.java:403)
        at org.tron.studio.ui.RightTabRunController.onClickDeploy(RightTabRunController.java:318)

2. What did you expect to see?

3. What did you see instead?

**Comment by jeancky** [comment]
It's a tron-studio issue, please refer to this repo.
https://github.com/tronprotocol/tron-studio
