### ISSUE TITLE
DB issue

### ISSUE THREAD

**Issue by osiztechnologies** [tronprotocol/java-tron#2163]
when we start the Fullnode. we have faced following issue.

******** begin to pop revokingDb ********
******** before revokingDb size:0
******** end to pop revokingDb ********

Advise us how to resolve this issue.

**Comment by jiangyy0824** [comment]
@osiztechnologies Please ignore. This is not an issue.

**Comment by osiztechnologies** [comment]
But port numbers (8090, 8091) not listen.

**Comment by jiangyy0824** [comment]
@osiztechnologies Please use "netstat -an |grep 8090" to confirm the port is not listen after launching your fullnode. 

If the port is not listen, please provide the tron.log and your config.conf.

Thanks.

**Comment by osiztechnologies** [comment]
@jiangyy0824 Here i have shared log & conf file.

![screenshot--2019 05 03-11-26-06](https://user-images.githubusercontent.com/12368647/57121602-50d26b00-6d96-11e9-819d-4c489c90f96a.png)

[tronconfig.txt](https://github.com/tronprotocol/java-tron/files/3140762/tronconfig.txt)

[tron.log](https://github.com/tronprotocol/java-tron/files/3140760/tron.log)

**Comment by thel0ner** [comment]
same happened to me. 
I got a ubuntu server with a oracle JDK 8 available on my environment path. First decided to build the java-tron but it failed in tests, now trying to use the one in release  section of your repo and here's the out put of of **SolidityNode.jar** on my server : 
`
18:37:04.943 INFO  [main] [app](SolidityNode.java:176) Solidity node running.
18:37:06.325 INFO  [main] [app](Args.java:1118) Bind address wasn't set, Punching to identify it...
18:37:06.646 INFO  [main] [app](Args.java:1121) UDP local bound to: ******
18:37:06.651 INFO  [main] [app](Args.java:1136) External IP wasn't set, using checkip.amazonaws.com to identify it...
18:37:06.914 INFO  [main] [app](Args.java:1150) External address identified: *****
18:37:06.921 INFO  [main] [app](Args.java:1241)

18:37:06.932 INFO  [main] [app](Args.java:1242) ************************ Net config ************************
18:37:06.932 INFO  [main] [app](Args.java:1243) P2P version: 11111
18:37:06.932 INFO  [main] [app](Args.java:1244) Bind IP: ******
18:37:06.933 INFO  [main] [app](Args.java:1245) External IP: ******
18:37:06.933 INFO  [main] [app](Args.java:1246) Listen port: 18888
18:37:06.933 INFO  [main] [app](Args.java:1247) Discover enable: true
18:37:06.933 INFO  [main] [app](Args.java:1248) Active node size: 0
18:37:06.934 INFO  [main] [app](Args.java:1249) Passive node size: 0
18:37:06.934 INFO  [main] [app](Args.java:1250) Seed node size: 29
18:37:06.934 INFO  [main] [app](Args.java:1251) Max connection: 30
18:37:06.934 INFO  [main] [app](Args.java:1252) Max connection with same IP: 2
18:37:06.934 INFO  [main] [app](Args.java:1253) Solidity threads: 1
18:37:06.934 INFO  [main] [app](Args.java:1254) ************************ Backup config ************************
18:37:06.934 INFO  [main] [app](Args.java:1255) Backup listen port: 10001
18:37:06.935 INFO  [main] [app](Args.java:1256) Backup member size: 0
18:37:06.935 INFO  [main] [app](Args.java:1257) Backup priority: 8
18:37:06.935 INFO  [main] [app](Args.java:1258) ************************ Code version *************************
18:37:06.935 INFO  [main] [app](Args.java:1259) Code version : 3.5.1
18:37:06.941 INFO  [main] [app](Args.java:1260) Version name: Odyssey-v3.5.0.1-318-gc6864f595
18:37:06.941 INFO  [main] [app](Args.java:1261) Version code: 9911
18:37:06.941 INFO  [main] [app](Args.java:1262) ************************ DB config *************************
18:37:06.941 INFO  [main] [app](Args.java:1263) DB version : 2
18:37:06.942 INFO  [main] [app](Args.java:1264) DB engine : LEVELDB
18:37:06.943 INFO  [main] [app](Args.java:1265) ***************************************************************
18:37:06.944 INFO  [main] [app](Args.java:1266)
18:37:06.945 INFO  [main] [app](SolidityNode.java:180) index switch is on
18:37:07.265 INFO  [main] [o.t.c.a.TronApplicationContext](AbstractApplicationContext.java:573) Refreshing org.tron.common.application.TronApplicationContext@3d34d211: $
18:37:10.056 INFO  [main] [o.s.b.f.a.AutowiredAnnotationBeanPostProcessor](AutowiredAnnotationBeanPostProcessor.java:153) JSR-330 'javax.inject.Inject' annotation found$
18:37:10.743 INFO  [main] [app](DefaultConfig.java:65) key-value data source created.
18:37:11.582 INFO  [main] [DB](DynamicPropertiesStore.java:1465) update latest block header timestamp = 0
18:37:11.588 INFO  [main] [DB](DynamicPropertiesStore.java:1473) update latest block header number = 0
18:37:11.606 INFO  [main] [DB](DynamicPropertiesStore.java:1481) update latest block header id = 00
18:37:11.612 INFO  [main] [DB](DynamicPropertiesStore.java:1488) update state flag = 0
18:37:12.342 INFO  [main] [DB](Manager.java:499) create genesis block
18:37:12.345 INFO  [main] [DB](Manager.java:505) save block: BlockCapsule
[ hash=******
number=0
parentId=*****
witness address=*****$
generated by myself=true
generate time=1970-01-01 01:00:00.0
merkle root=******
18:37:06.945 INFO  [main] [app](SolidityNode.java:180) index switch is on
18:37:07.265 INFO  [main] [o.t.c.a.TronApplicationContext](AbstractApplicationContext.java:573) Refreshing org.tron.common.application.TronApplicationContext@3d34d211: $
18:37:10.056 INFO  [main] [o.s.b.f.a.AutowiredAnnotationBeanPostProcessor](AutowiredAnnotationBeanPostProcessor.java:153) JSR-330 'javax.inject.Inject' annotation found$
18:37:10.743 INFO  [main] [app](DefaultConfig.java:65) key-value data source created.
18:37:11.582 INFO  [main] [DB](DynamicPropertiesStore.java:1465) update latest block header timestamp = 0
18:37:11.588 INFO  [main] [DB](DynamicPropertiesStore.java:1473) update latest block header number = 0
18:37:11.606 INFO  [main] [DB](DynamicPropertiesStore.java:1481) update latest block header id = 00
18:37:11.612 INFO  [main] [DB](DynamicPropertiesStore.java:1488) update state flag = 0
18:37:12.342 INFO  [main] [DB](Manager.java:499) create genesis block
18:37:12.345 INFO  [main] [DB](Manager.java:505) save block: BlockCapsule
[ hash=00000000000000001ebf88508a03865c71d452e25f4d51194196a1d22b6653dc
number=0
parentId=e58f33f9baf9305dc6f82b9f1934ea8f0ade2defb951258d50167028c780351f
witness address=41206e65772073797374656d206d75737420616c6c6f77206578697374696e672073797374656d7320746f206265206c696e6b656420746f67657468657220776974686f7574207265717569$
generated by myself=true
generate time=1970-01-01 01:00:00.0
merkle root=8ef446bf3f395af929c218014f6101ec86576c5f61b2ae3236bf3a2ab5e2fecd
18:37:12.346 INFO  [main] [DB](DynamicPropertiesStore.java:1473) update latest block header number = 0
18:37:12.346 INFO  [main] [DB](DynamicPropertiesStore.java:1481) update latest block header id = 00000000000000001ebf88508a03865c71d452e25f4d51194196a1d22b6653dc
18:37:12.347 INFO  [main] [DB](DynamicPropertiesStore.java:1465) update latest block header timestamp = 0
18:37:12.449 INFO  [main] [witness](WitnessController.java:61) initWits shuffled addresses:415095d4f4d26ebc672ca12fc0e3a48d6ce3b169d2
18:37:12.454 INFO  [main] [witness](WitnessController.java:61) initWits shuffled addresses:41d32b3fa8ca0b4896257fdf1821ac8d116da84c45
18:37:12.454 INFO  [main] [witness](WitnessController.java:61) initWits shuffled addresses:41df3bd4e0463534cb7f1f3ffc2ec14ac4693dc3b2
18:37:12.454 INFO  [main] [witness](WitnessController.java:61) initWits shuffled addresses:4127a6419bbe59f4e64a064d710787e578a150d6a7
18:37:12.455 INFO  [main] [witness](WitnessController.java:61) initWits shuffled addresses:4108b55b2611ec829d308a62b3339fba9dd5c27151
18:37:12.455 INFO  [main] [witness](WitnessController.java:61) initWits shuffled addresses:416419765bacf1dc441f722cabc8b661140558bb5d
18:37:12.455 INFO  [main] [witness](WitnessController.java:61) initWits shuffled addresses:414b4778beebb48abe0bc1df42e92e0fe64d0c8685
18:37:12.456 INFO  [main] [witness](WitnessController.java:61) initWits shuffled addresses:411661f25387370c9cd3a9a5d97e60ca90f4844e7e
18:37:12.456 INFO  [main] [witness](WitnessController.java:61) initWits shuffled addresses:41e40de6895c142ade8b86194063bcdbaa6c9360b6
18:37:12.456 INFO  [main] [witness](WitnessController.java:61) initWits shuffled addresses:41207ab1585b9cc6c4c1232f67e4a10e19a442fe68
18:37:12.456 INFO  [main] [witness](WitnessController.java:61) initWits shuffled addresses:41410e468919155aa847d83b0c206148511b6dc848
18:37:12.456 INFO  [main] [witness](WitnessController.java:61) initWits shuffled addresses:4186f5793eb678c65d9673d5498c550439d762c1cc
18:37:12.457 INFO  [main] [witness](WitnessController.java:61) initWits shuffled addresses:417040583133e831953ea4f65a8196fcffcfbf0d80
18:37:12.457 INFO  [main] [witness](WitnessController.java:61) initWits shuffled addresses:412edce151c81d9b4aae17f974f7f646242eff989d
18:37:12.457 INFO  [main] [witness](WitnessController.java:61) initWits shuffled addresses:41ffd564656556a8b6b79311a932e3d216f4fc030b
18:37:12.457 INFO  [main] [witness](WitnessController.java:61) initWits shuffled addresses:414593d27b70d21454b39ab60bf13291dae8dc0326
18:37:12.457 INFO  [main] [witness](WitnessController.java:61) initWits shuffled addresses:41746e6af4ac9db3473c0c955f1fca11d4013f32ed
18:37:12.458 INFO  [main] [witness](WitnessController.java:61) initWits shuffled addresses:41e72d833e0c46837c0802864acc5f119a0a904d05
18:37:12.458 INFO  [main] [witness](WitnessController.java:61) initWits shuffled addresses:41f8c7acc4c08cf36ca08fc2a61b1f5a7c8dea7bec
18:37:12.458 INFO  [main] [witness](WitnessController.java:61) initWits shuffled addresses:411d7aba13ea199a63d1647e58e39c16a9bb9da689
18:37:12.459 INFO  [main] [witness](WitnessController.java:61) initWits shuffled addresses:410694981b116304ed21e05896fb16a6bc2e91c92c
18:37:12.459 INFO  [main] [witness](WitnessController.java:61) initWits shuffled addresses:411155d10415fac16a8f4cb2f382ce0e0f0a7e64cc
18:37:12.460 INFO  [main] [witness](WitnessController.java:61) initWits shuffled addresses:41318b2b6b4c7fcaa4b62f25a282329e1952a3c0d1
18:37:12.466 INFO  [main] [witness](WitnessController.java:61) initWits shuffled addresses:41a857362c1b77cb04e8f2b51b6e970f24fa5c1e5b
18:37:12.467 INFO  [main] [witness](WitnessController.java:61) initWits shuffled addresses:41a8bb7680d85f9821b3d82505edc4663f6fbd8fde
18:37:12.467 INFO  [main] [witness](WitnessController.java:61) initWits shuffled addresses:4127bf0d1a57f335c11bc5d002dd82e9e0727cb967
18:37:12.467 INFO  [main] [witness](WitnessController.java:61) initWits shuffled addresses:4172fd5dfb8ab36eb28df8e4aee97966a60ebf9efe
18:37:12.481 INFO  [main] [DB](AssetUpdateHelper.java:34) Start updating the asset
18:37:12.517 INFO  [main] [DB](AssetUpdateHelper.java:92) Total block：1
18:37:12.518 INFO  [main] [DB](AssetUpdateHelper.java:120) Complete the asset store update,Total assets：0
18:37:12.521 INFO  [main] [DB](AssetUpdateHelper.java:141) Complete the exchange store update,Total exchanges：0
18:37:12.528 INFO  [main] [DB](AssetUpdateHelper.java:189) The number of accounts that have completed the update ：0
18:37:12.545 INFO  [main] [DB](AssetUpdateHelper.java:194) Complete the account store update,Total assets：30
18:37:12.545 INFO  [main] [DB](AssetUpdateHelper.java:40) Complete the asset update,Total time：64 milliseconds
18:37:12.547 INFO  [main] [DB](Manager.java:575) begin to init txs cache.
18:37:12.604 INFO  [main] [DB](Manager.java:614) end to init txs cache. trxids:3, block count:1, empty block count:0, cost:57
18:37:12.610 WARN  [main] [o.t.c.a.TronApplicationContext](AbstractApplicationContext.java:544) Exception encountered during context initialization - cancelling refresh$
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'blockMsgHandler': Injection of autowired dependencies failed; nested exception i$
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:305)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:301)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:196)
   at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:834)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537)
        at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:84)
        at org.tron.common.application.TronApplicationContext.<init>(TronApplicationContext.java:21)
        at org.tron.program.SolidityNode.main(SolidityNode.java:189)
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.net.TronNetDelegate org.tron.core.net.messagehandler$
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:571)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
        ... 13 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tronNetDelegate': Injection of autowired dependencies failed; nested $
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:305)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:301)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:196)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1145)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1069)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:967)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:543)
        ... 15 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.server.SyncPool org.tron.core.net.TronNetD$
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:571)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
        ... 26 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'syncPool': Injection of autowired dependencies failed; nested excepti$
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tronNetDelegate': Injection of autowired dependencies failed; nested $
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:305)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:301)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:196)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1145)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1069)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:967)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:543)
        ... 15 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.server.SyncPool org.tron.core.net.TronNetD$
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:571)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
        ... 26 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.server.SyncPool org.tron.core.net.TronNetD$
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:571)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
        ... 26 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'syncPool': Injection of autowired dependencies failed; nested excepti$
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:305)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:301)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:196)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1145)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1069)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:967)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:543)
        ... 28 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.discover.node.NodeManager org.tron.common.$
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:571)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
        ... 39 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nodeManager' defined in URL [jar:file:/home/tron/SolidityNod$
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:185)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1143)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:305)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:301)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:196)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1145)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1069)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:967)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:543)
        ... 41 common frames omitted
18:37:12.626 ERROR [main] [app](DefaultConfig.java:39) Uncaught exception
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'blockMsgHandler': Injection of autowired dependencies failed; nested exception i$
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:305)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:301)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:196)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:834)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537)
        at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:84)
        at org.tron.common.application.TronApplicationContext.<init>(TronApplicationContext.java:21)
        at org.tron.program.SolidityNode.main(SolidityNode.java:189)
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.net.TronNetDelegate org.tron.core.net.messagehandler$
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:571)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
        ... 13 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.discover.node.NodeManager org.tron.common.$
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:571)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
        ... 39 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nodeManager' defined in URL [jar:file:/home/tron/SolidityNod$
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:185)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1143)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:305)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:301)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:196)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1145)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1069)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:967)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:543)
        ... 41 common frames omitted
Caused by: java.lang.IllegalArgumentException: null
        at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1314)
        at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1202)
        at java.util.concurrent.Executors.newFixedThreadPool(Executors.java:89)
        at org.tron.core.db.Manager.init(Manager.java:465)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:354)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcesso$
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.ja$
        ... 67 common frames omitted
`
You see how ugly are the errors ... 
and about the conf, i use the default .conf file of you repo except that i have replaced my own private key with the one in the file.
any hopes?
