### ISSUE TITLE
Solidity node stops sync

### ISSUE THREAD

**Issue by risyasin** [tronprotocol/java-tron#2398]
I am trying to deploy a Solidity node. But on block 4022 it stops with the following error log below. 
`assetName can't be trx`. I couldn't find any related closed or open issue. 

1. What did you do?
I  have installed latest tron-cli with `pip3 install troncli` then I've started node with 
`tron-cli run --nodetype sol`. It can only count to block number 4022
I have tried new release 3.6.1 since troncli was only supporting 3.5 by replacing jar file. It also stops at block 4022. I have removed database and index directories. Tried any yet it didn't change. I believe at this point it shouldn't be that difficult to reproduce this error. 

Side notes: 
Ubuntu 18.4.2 
java -version 
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

```
RAM  <usages>
             total    percent       used       free     active   inactive
Mem:         31.4G      31.5%       9.5G       5.9G      14.7G      10.4G
Swap:         8.0G       0.0%         0B       8.0G                      
Node Version 3.5.0.1
Full-node IDs [17441]
    http connection: 127.0.0.1:8500
    rpc connection: 127.0.0.1:58500
    log location: /root/tron_nodes/fullnode/logs/tron.log
Solidity-node IDs [23096]
    http connection: 127.0.0.1:8600
    rpc connection: 127.0.0.1:58600
    log location: /root/tron_nodes/soliditynode/logs/tron.log
Event-node IDs []
Grid-api IDs []
Config CMD tron-cli config --nettype main --fullhttpport 8500 --solhttpport 8600 --eventhttpport 8400 --fullrpcport 58500 --solrpcport 58600 --eventrpcport 58400 --enablememdb True --dbsyncmode async --saveintertx False --savehistorytx False --gridport 18891 --dbname Null --dbusername Null --dbpassword Null

````

2. What did you expect to see?
Solidity node to sync

3. What did you see instead?
```
13:56:34.696 ERROR [Thread-18] [app](SolidityNode.java:109) Failed to process block BlockCapsule 
[ hash=0000000000000fb6c3220676c3feacfe087f29bd40541aa4660d81183640a39d
number=4022
parentId=0000000000000fb54e07e644a3a1b626ed33a59cfb2cb839b5dfdde98dd28023
witness address=41318b2b6b4c7fcaa4b62f25a282329e1952a3c0d1
generated by myself=false
generate time=2018-06-25 07:13:24.0
merkle root=fbb5e5bdb0e59a6743ab638cfb37ae603ffa73412d0558fea798e59d683425ff
account root=0000000000000000000000000000000000000000000000000000000000000000
txs size=1
].
org.tron.core.exception.ContractValidateException: assetName can't be trx
	at org.tron.core.actuator.AssetIssueActuator.validate(AssetIssueActuator.java:167)
	at org.tron.common.runtime.RuntimeImpl.precompiled(RuntimeImpl.java:172)
	at org.tron.common.runtime.RuntimeImpl.execute(RuntimeImpl.java:181)
	at org.tron.core.db.TransactionTrace.exec(TransactionTrace.java:167)
	at org.tron.core.db.Manager.processTransaction(Manager.java:1240)
	at org.tron.core.db.Manager.processBlock(Manager.java:1552)
	at org.tron.core.db.Manager.applyBlock(Manager.java:853)
	at org.tron.core.db.Manager.pushBlock(Manager.java:1060)
	at org.tron.core.db.Manager.pushVerifiedBlock(Manager.java:840)
	at org.tron.program.SolidityNode.loopProcessBlock(SolidityNode.java:103)
	at org.tron.program.SolidityNode.processBlock(SolidityNode.java:91)
	at org.tron.program.SolidityNode.lambda$start$1(SolidityNode.java:58)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by zk19862018** [comment]
what’s your solidity node configuration file?

**Comment by zk19862018** [comment]
can you try java-tron version 3.6?

**Comment by risyasin** [comment]
This the configuration downloaded by tron-cli for solidity node. 
But I no longer use Solidity node. Switched to Fullnode with deploy.sh (uses Odyssey-v3.6.2) which is working fine now. I've changed my business requirements and implementation that's aware of transactions' confirmations. 
I believe we need to update tron-cli tool for good. Some of the documentation can be found easily on web search leads people to use outdated tron-cli tool which sounds official to my opinion. 

```
net {
  type = mainnet
  # type = testnet
}

storage {
  # Directory for storing persistent data
  db.version = 2,
  db.engine = "LEVELDB",
  db.directory = "database",
  index.directory = "index",
  
  # This configuration item is only for SolidityNode.
  # Turn off the index is "off", else "on".
  # Turning off the index will significantly improve the performance of the SolidityNode sync block.
  # You can turn off the index if you don't use the two interfaces getTransactionsToThis and getTransactionsFromThis.
  index.switch = "off"
  
  # This configuration item is used to database write strategy.
  # Synchronous writing is "true", else Asynchronous writing is "false".
  # Asynchronous writing significantly improves the performance of the FullNode sync block.
  # 1. If asynchronous, the write will be flushed from the operating system buffer cache.
  #    the machine crashes, some recent writes may be lost. Note that if it is just the process that
  #    crashes (i.e., the machine does not reboot), no writes will be lost;
  # 2. If synchronous, writes will be flush into leveldb directly.
  #     No writes will be lost when machine crashes, but it is slow.
  db.sync = false,
  
  # This configuration item controls the transaction result be put into transactionHistory database.
  # Turn off the switch is "off", else "on".
  # Turning off the switch, transaction result will not be put into transactionHistory database;
  # You can turn off the switch if you don't use the interface getransactioninfobyid.
  transHistory.switch = "on",
  

  # You can custom these 14 databases' configs:

  # account, account-index, asset-issue, block, block-index,
  # block_KDB, peers, properties, recent-block, trans,
  # utxo, votes, witness, witness_schedule.

  # Otherwise, db configs will remain defualt and data will be stored in
  # the path of "output-directory" or which is set by "-d" ("--output-directory").

  # Attention: name is a required field that must be set !!!
  properties = [
//    {
//      name = "account",
//      path = "storage_directory_test",
//      createIfMissing = true,
//      paranoidChecks = true,
//      verifyChecksums = true,
    //      compressionType = 1,        // compressed with snappy
    //      blockSize = 4096,           // 4  KB =         4 * 1024 B
    //      writeBufferSize = 10485760, // 10 MB = 10 * 1024 * 1024 B
    //      cacheSize = 10485760,       // 10 MB = 10 * 1024 * 1024 B
    //      maxOpenFiles = 100
    //    },
//    {
//      name = "account-index",
//      path = "storage_directory_test",
//      createIfMissing = true,
//      paranoidChecks = true,
//      verifyChecksums = true,
    //      compressionType = 1,        // compressed with snappy
    //      blockSize = 4096,           // 4  KB =         4 * 1024 B
    //      writeBufferSize = 10485760, // 10 MB = 10 * 1024 * 1024 B
    //      cacheSize = 10485760,       // 10 MB = 10 * 1024 * 1024 B
    //      maxOpenFiles = 100
    //    },
  ]

}

node.discovery = {
  enable = true
  persist = true
  bind.ip = ""
  external.ip = null
}

node.backup {
  port = 10001
  priority = 8
  members = [
  ]
}

node {
  # trust node for solidity node
  # trustNode = "ip:port"
  # trustNode = "127.0.0.1:50051"

  # expose extension api to public or not
  walletExtensionApi = true

  listen.port = 18888

  connection.timeout = 2

  tcpNettyWorkThreadNum = 0

  udpNettyWorkThreadNum = 1

  # Number of validate sign thread, default availableProcessors / 2
  # validateSignThreadNum = 16

  connectFactor = 0.3
  activeConnectFactor = 0.1

  maxActiveNodes = 30

  maxActiveNodesWithSameIp = 2

  minParticipationRate = 15
  
  maxHttpConnectNumber = 50

  # check the peer data transfer ,disconnect factor
  disconnectNumberFactor = 0.4
  maxConnectNumberFactor = 0.8
  maxHttpConnectNumber = 50
  receiveTcpMinDataLength = 2048
  isOpenFullTcpDisconnect = true

  p2p {
    version = 11111 # 11111: mainnet; 20180622: testnet
  }

  active = [
    # Active establish connection in any case
    # Sample entries:
    # "ip:port",
    # "ip:port"
  ]

  passive = [
    # Passive accept connection in any case
    # Sample entries:
    # "ip:port",
    # "ip:port"
  ]
  
  fastForward = [
    "100.26.245.209:18888",
    "15.188.6.125:18888"
  ]

  http {
    fullNodePort = 8090
    solidityPort = 8091
  }

  rpc {
    port = 50051
    solidityPort = 50061
    # Number of gRPC thread, default availableProcessors / 2
    # thread = 16

    # The maximum number of concurrent calls permitted for each incoming connection
    # maxConcurrentCallsPerConnection =

    # The HTTP/2 flow control window, default 1MB
    # flowControlWindow =

    # Connection being idle for longer than which will be gracefully terminated
    maxConnectionIdleInMillis = 60000

    # Connection lasting longer than which will be gracefully terminated
    # maxConnectionAgeInMillis =

    # The maximum message size allowed to be received on the server, default 4MB
    # maxMessageSize =

    # The maximum size of header list allowed to be received, default 8192
    # maxHeaderListSize =
  }
  blockProducedTimeOut = 50
  # number of solidity thread in the FullNode.
  # If accessing solidity rpc and http interface timeout, could increase the number of threads,
  # The default value is the number of cpu cores of the machine.
  #solidity.threads = 8
}



seed.node = {
  # List of the seed nodes
  # Seed nodes are stable full nodes
  # example:
  # ip.list = [
  #   "ip:port",
  #   "ip:port"
  # ]
  ip.list = [
    "3.225.171.164:18888",
    "52.53.189.99:18888",
    "18.196.99.16:18888",
    "34.253.187.192:18888",
    "52.56.56.149:18888",
    "35.180.51.163:18888",
    "54.252.224.209:18888",
    "18.228.15.36:18888",
    "52.15.93.92:18888",
    "34.220.77.106:18888",
    "13.127.47.162:18888",
    "13.124.62.58:18888",
    "35.182.229.162:18888",
    "18.209.42.127:18888",
    "3.218.137.187:18888",
    "34.237.210.82:18888"
  ]
}

genesis.block = {
  # Reserve balance
  assets = [
    {
      accountName = "Zion"
      accountType = "AssetIssue"
      address = "TLLM21wteSPs4hKjbxgmH1L6poyMjeTbHm"
      balance = "99000000000000000"
    },
    {
      accountName = "Sun"
      accountType = "AssetIssue"
      address = "TXmVpin5vq5gdZsciyyjdZgKRUju4st1wM"
      balance = "0"
    },
    {
      accountName = "Blackhole"
      accountType = "AssetIssue"
      address = "TLsV52sRDL79HXGGm9yzwKibb6BeruhUzy"
      balance = "-9223372036854775808"
    }
  ]

  witnesses = [
    {
      address: THKJYuUmMKKARNf7s2VT51g5uPY6KEqnat,
      url = "http://GR1.com",
      voteCount = 100000026
    },
    {
      address: TVDmPWGYxgi5DNeW8hXrzrhY8Y6zgxPNg4,
      url = "http://GR2.com",
      voteCount = 100000025
    },
    {
      address: TWKZN1JJPFydd5rMgMCV5aZTSiwmoksSZv,
      url = "http://GR3.com",
      voteCount = 100000024
    },
    {
      address: TDarXEG2rAD57oa7JTK785Yb2Et32UzY32,
      url = "http://GR4.com",
      voteCount = 100000023
    },
    {
      address: TAmFfS4Tmm8yKeoqZN8x51ASwdQBdnVizt,
      url = "http://GR5.com",
      voteCount = 100000022
    },
    {
      address: TK6V5Pw2UWQWpySnZyCDZaAvu1y48oRgXN,
      url = "http://GR6.com",
      voteCount = 100000021
    },
    {
      address: TGqFJPFiEqdZx52ZR4QcKHz4Zr3QXA24VL,
      url = "http://GR7.com",
      voteCount = 100000020
    },
    {
      address: TC1ZCj9Ne3j5v3TLx5ZCDLD55MU9g3XqQW,
      url = "http://GR8.com",
      voteCount = 100000019
    },
    {
      address: TWm3id3mrQ42guf7c4oVpYExyTYnEGy3JL,
      url = "http://GR9.com",
      voteCount = 100000018
    },
    {
      address: TCvwc3FV3ssq2rD82rMmjhT4PVXYTsFcKV,
      url = "http://GR10.com",
      voteCount = 100000017
    },
    {
      address: TFuC2Qge4GxA2U9abKxk1pw3YZvGM5XRir,
      url = "http://GR11.com",
      voteCount = 100000016
    },
    {
      address: TNGoca1VHC6Y5Jd2B1VFpFEhizVk92Rz85,
      url = "http://GR12.com",
      voteCount = 100000015
    },
    {
      address: TLCjmH6SqGK8twZ9XrBDWpBbfyvEXihhNS,
      url = "http://GR13.com",
      voteCount = 100000014
    },
    {
      address: TEEzguTtCihbRPfjf1CvW8Euxz1kKuvtR9,
      url = "http://GR14.com",
      voteCount = 100000013
    },
    {
      address: TZHvwiw9cehbMxrtTbmAexm9oPo4eFFvLS,
      url = "http://GR15.com",
      voteCount = 100000012
    },
    {
      address: TGK6iAKgBmHeQyp5hn3imB71EDnFPkXiPR,
      url = "http://GR16.com",
      voteCount = 100000011
    },
    {
      address: TLaqfGrxZ3dykAFps7M2B4gETTX1yixPgN,
      url = "http://GR17.com",
      voteCount = 100000010
    },
    {
      address: TX3ZceVew6yLC5hWTXnjrUFtiFfUDGKGty,
      url = "http://GR18.com",
      voteCount = 100000009
    },
    {
      address: TYednHaV9zXpnPchSywVpnseQxY9Pxw4do,
      url = "http://GR19.com",
      voteCount = 100000008
    },
    {
      address: TCf5cqLffPccEY7hcsabiFnMfdipfyryvr,
      url = "http://GR20.com",
      voteCount = 100000007
    },
    {
      address: TAa14iLEKPAetX49mzaxZmH6saRxcX7dT5,
      url = "http://GR21.com",
      voteCount = 100000006
    },
    {
      address: TBYsHxDmFaRmfCF3jZNmgeJE8sDnTNKHbz,
      url = "http://GR22.com",
      voteCount = 100000005
    },
    {
      address: TEVAq8dmSQyTYK7uP1ZnZpa6MBVR83GsV6,
      url = "http://GR23.com",
      voteCount = 100000004
    },
    {
      address: TRKJzrZxN34YyB8aBqqPDt7g4fv6sieemz,
      url = "http://GR24.com",
      voteCount = 100000003
    },
    {
      address: TRMP6SKeFUt5NtMLzJv8kdpYuHRnEGjGfe,
      url = "http://GR25.com",
      voteCount = 100000002
    },
    {
      address: TDbNE1VajxjpgM5p7FyGNDASt3UVoFbiD3,
      url = "http://GR26.com",
      voteCount = 100000001
    },
    {
      address: TLTDZBcPoJ8tZ6TTEeEqEvwYFk2wgotSfD,
      url = "http://GR27.com",
      voteCount = 100000000
    }
  ]

  timestamp = "0" #2017-8-26 12:00:00

  parentHash = "0xe58f33f9baf9305dc6f82b9f1934ea8f0ade2defb951258d50167028c780351f"
}

localwitness = [
]

#localwitnesskeystore = [
#  "localwitnesskeystore.json"
#]

block = {
  needSyncCheck = true
  maintenanceTimeInterval = 21600000
  proposalExpireTime = 259200000 // 3 day: 259200000(ms)
}

# Transaction reference block, default is "head", configure to "solid" can avoid TaPos error
trx.reference.block = "head" // head;solid;

# This property sets the number of milliseconds after the creation of the transaction that is expired, default value is 60000.
# trx.expiration.timeInMilliseconds = 60000

vm = {
  supportConstant = false
  minTimeRatio = 0.0
  maxTimeRatio = 5.0
  saveInternalTx = false
}

committee = {
  allowCreationOfContracts = 0  //mainnet:0 (reset by committee),test:1
}

```

**Comment by zk19862018** [comment]
You can refer to https://tronprotocol.github.io/documentation-EN/ 
If your problem is solved, can you close this issue? 
Thank you.

**Comment by risyasin** [comment]
.
