### ISSUE TITLE
Sync stuck on block 14000439 ( DB Bad chain parameter id )

### ISSUE THREAD

**Issue by astudnev** [tronprotocol/java-tron#2618]
The node stopped syncing new blocks, the last one is 14000439

Log is attached, connectivity is good.

Node re-start did not help. 

Attaching config and logs
[config.conf.txt](https://github.com/tronprotocol/java-tron/files/3788725/config.conf.txt)
[tron.log.txt](https://github.com/tronprotocol/java-tron/files/3788726/tron.log.txt)

**Comment by astudnev** [comment]
12:03:24.576 ERROR [pool-36-thread-1] [DB](Manager.java:1065) Bad chain parameter id
org.tron.core.exception.ContractValidateException: Bad chain parameter id
        at org.tron.core.actuator.ProposalCreateActuator.validate(ProposalCreateActuator.java:134)
        at org.tron.common.runtime.RuntimeImpl.precompiled(RuntimeImpl.java:172)
        at org.tron.common.runtime.RuntimeImpl.execute(RuntimeImpl.java:181)
        at org.tron.core.db.TransactionTrace.exec(TransactionTrace.java:167)
        at org.tron.core.db.Manager.processTransaction(Manager.java:1240)
        at org.tron.core.db.Manager.processBlock(Manager.java:1552)
        at org.tron.core.db.Manager.applyBlock(Manager.java:853)
        at org.tron.core.db.Manager.pushBlock(Manager.java:1060)
        at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:187)
        at org.tron.core.net.service.SyncService.processSyncBlock(SyncService.java:262)
        at org.tron.core.net.service.SyncService.lambda$handleSyncBlock$8(SyncService.java:251)
        at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
        at org.tron.core.net.service.SyncService.handleSyncBlock(SyncService.java:234)
        at org.tron.core.net.service.SyncService.lambda$init$1(SyncService.java:77)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by astudnev** [comment]
12:03:24.578 ERROR [pool-36-thread-1] [net](SyncService.java:264) Process sync block Num:14000440,ID:0000000000d5a13857dd651d4380cfad8576f8a6fa01a4a6860cca4d1738433b failed.
org.tron.core.exception.P2pException: org.tron.core.exception.ContractValidateException: Bad chain parameter id
        at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:207)
        at org.tron.core.net.service.SyncService.processSyncBlock(SyncService.java:262)
        at org.tron.core.net.service.SyncService.lambda$handleSyncBlock$8(SyncService.java:251)
        at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
        at org.tron.core.net.service.SyncService.handleSyncBlock(SyncService.java:234)
        at org.tron.core.net.service.SyncService.lambda$init$1(SyncService.java:77)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.tron.core.exception.ContractValidateException: Bad chain parameter id
        at org.tron.core.actuator.ProposalCreateActuator.validate(ProposalCreateActuator.java:134)
        at org.tron.common.runtime.RuntimeImpl.precompiled(RuntimeImpl.java:172)
        at org.tron.common.runtime.RuntimeImpl.execute(RuntimeImpl.java:181)
        at org.tron.core.db.TransactionTrace.exec(TransactionTrace.java:167)
        at org.tron.core.db.Manager.processTransaction(Manager.java:1240)
        at org.tron.core.db.Manager.processBlock(Manager.java:1552)
        at org.tron.core.db.Manager.applyBlock(Manager.java:853)
        at org.tron.core.db.Manager.pushBlock(Manager.java:1060)
        at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:187)
        ... 12 common frames omitted

**Comment by astudnev** [comment]
Update to master head helped

**Comment by wubin01** [comment]
Should update java-tron version 3.6.5
