### ISSUE TITLE
when i start the fullnode and solitynode the following error happend that make  the node sync error in testnetwork

### ISSUE THREAD

**Issue by listenyear** [tronprotocol/java-tron#2630]
### 1. What did you do?

        deploy the fullnode.jar and solitynode.jar  from testnetwork

### 2. What did you expect to see?
my local node sync all  the blockchain info  from the testnetwork 
>

### 3. What did you see instead?
  `
### **the fullnode log is:**
org.tron.core.exception.ContractValidateException: Bad chain parameter id [ALLOW_SHIELDED_TRANSACTION]
	at org.tron.core.utils.ProposalUtil.validator(ProposalUtil.java:255)
	at org.tron.core.actuator.ProposalCreateActuator.validateValue(ProposalCreateActuator.java:123)
	at org.tron.core.actuator.ProposalCreateActuator.validate(ProposalCreateActuator.java:116)
	at org.tron.common.runtime.RuntimeImpl.execute(RuntimeImpl.java:64)
	at org.tron.core.db.TransactionTrace.exec(TransactionTrace.java:168)
	at org.tron.core.db.Manager.processTransaction(Manager.java:1297)
	at org.tron.core.db.Manager.processBlock(Manager.java:1533)
	at org.tron.core.db.Manager.applyBlock(Manager.java:922)
	at org.tron.core.db.Manager.pushBlock(Manager.java:1135)
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:197)
	at org.tron.core.net.service.SyncService.processSyncBlock(SyncService.java:262)
	at org.tron.core.net.service.SyncService.lambda$handleSyncBlock$8(SyncService.java:251)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.tron.core.net.service.SyncService.handleSyncBlock(SyncService.java:234)
	at org.tron.core.net.service.SyncService.lambda$init$1(SyncService.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by jiangyy0824** [comment]
@listenyear 

In order to keep up with online anonymous transactions, synchronize the database from the beginning will encounter problems, so you need to start syncing from this database:http://47.252.81.247

**Comment by listenyear** [comment]
@jiangyy0824
 
  where and which line i should set the database address ?

**Comment by jiangyy0824** [comment]
@listenyear you can use http://47.252.81.247/backup20191107/FullNode_output-directory.tgz, unzip it and replace your local output folder.

**Comment by listenyear** [comment]
@jiangyy0824 
  i got it, thank you
