### ISSUE TITLE
initCacheTxs error after a few short regional power failures

### ISSUE THREAD

**Issue by jiangyy0824** [tronprotocol/java-tron#2938]
### 1. What did you do?

Hi.
After a few short regional power failures I now have the following problem with the node. Maybe someone can give me a hint.

Feb 16, 2020 5:05:13 PM com.google.common.util.concurrent.AggregateFuture$RunningState handleException
SCHWERWIEGEND: Got more than one input Future failure. Logging failures after the first
java.lang.IllegalStateException: init txs cache error.
        at org.tron.core.db.Manager.lambda$null$7(Manager.java:633)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

******** begin to pop revokingDb ********
******** before revokingDb size:0
******** end to pop revokingDb ********

A complete restart has helped, although it has been restarted several times now. Problem solved.

### 2. What did you expect to see?
iinitCacheTxs successfully.

### 3. What did you see instead?

IllegalStateException

**Comment by jiangyy0824** [comment]
This issue is from Marco (SR© TRON-Family). More information is needed.

**Comment by Yrp** [comment]
Hi,
I'm very sorry for this situation at your node.

If the machine running the node is down or powered off, and the data is too late to write back to the database, the database will be damaged. 

Therefore, you need to replace a good database or resynchronize the blocks from Genesis.
