### ISSUE TITLE
`BeanCreationException` on startup

### ISSUE THREAD

**Issue by marktoda** [tronprotocol/java-tron#3103]
I am trying to sync a FullNode in the `Tronex` network using the configuration found here: http://testnet.tronex.io/join/getJoinPage. 

I am using Odyssey version 3.7 as downloaded from https://github.com/tronprotocol/java-tron/releases/tag/Odyssey-v3.7. 

### 2. What did you expect to see?
A syncing FullNode

### 3. What did you see instead?

```
01:05:33.984 INFO  [main] [app](FullNode.java:57) not in debug mode, it will check energy time
01:05:34.101 INFO  [main] [o.t.c.a.TronApplicationContext](AbstractApplicationContext.java:578) Refreshing org.tron.common.application.TronApplicationContext@11fc564b: startup date [Tue Apr 21 01:05:34 UTC 2020]; root of context hierarchy
01:05:35.605 INFO  [main] [o.s.b.f.a.AutowiredAnnotationBeanPostProcessor](AutowiredAnnotationBeanPostProcessor.java:153) JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
01:05:35.995 INFO  [main] [app](DefaultConfig.java:55) key-value data source created.
01:05:36.707 INFO  [main] [DB](Manager.java:638) begin to init txs cache.
01:05:41.921 INFO  [main] [DB](Manager.java:680) end to init txs cache. trxids:88068, block count:65536, empty block count:3336, cost:5213
01:05:42.367 INFO  [main] [o.r.Reflections](Reflections.java:232) Reflections took 431 ms to scan 1 urls, producing 374 keys and 2015 values 
01:05:42.428 WARN  [main] [o.t.c.a.TronApplicationContext](AbstractApplicationContext.java:546) Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'applicationImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.net.TronNetService org.tron.common.application.ApplicationImpl.tronNetService; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tronNetService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.server.ChannelManager org.tron.core.net.TronNetService.channelManager; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'channelManager': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.server.SyncPool org.tron.common.overlay.server.ChannelManager.syncPool; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'syncPool': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.discover.node.NodeManager org.tron.common.overlay.server.SyncPool.nodeManager; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nodeManager' defined in URL [jar:file:/home/fullnode/FullNodeRelease.jar!/org/tron/common/overlay/discover/node/NodeManager.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.tron.common.overlay.discover.node.NodeManager]: Constructor threw exception; nested exception is org.spongycastle.util.encoders.DecoderException: exception decoding Hex string: null

01:05:42.458 ERROR [main] [app](DefaultConfig.java:37) Uncaught exception
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'applicationImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.net.TronNetService org.tron.common.application.ApplicationImpl.tronNetService; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tronNetService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.server.ChannelManager org.tron.core.net.TronNetService.channelManager; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'channelManager': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.server.SyncPool org.tron.common.overlay.server.ChannelManager.syncPool; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'syncPool': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.discover.node.NodeManager org.tron.common.overlay.server.SyncPool.nodeManager; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nodeManager' defined in URL [jar:file:/home/fullnode/FullNodeRelease.jar!/org/tron/common/overlay/discover/node/NodeManager.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.tron.common.overlay.discover.node.NodeManager]: Constructor threw exception; nested exception is org.spongycastle.util.encoders.DecoderException: exception decoding Hex string: null
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
	at org.tron.program.FullNode.main(FullNode.java:66)
```

**Comment by andelf** [comment]
According to the Tronex testnet homepage:

The branch name is: `release_3.7_nodes_multi_witness`.

The last error in stack is `org.spongycastle.util.encoders.DecoderException: exception decoding Hex string: null`

There might be some typo in any of:

- config file
- command-line arguments

**Comment by marktoda** [comment]
I don't think there is a typo in my config or command:

Command: `exec java -jar FullNodeRelease.jar --log-config logback.xml -c testnet-config.conf -d /data`
Config:
```
# Based on: http://testnet.tronex.io/join/getJoinPage
net {
  type = mainnet
  # type = testnet
}
enery.limit.block.num = 0
storage {
  # Directory for storing persistent data
  db.version = 2,
  db.engine = "LEVELDB",
  db.sync = false,
  db.directory = "database",
  index.directory = "index",
  transHistory.switch = "on",

  # You can custom these 14 databases' configs:
# account, account-index, asset-issue, block, block-index,
  # block_KDB, peers, properties, recent-block, trans,
  # utxo, votes, witness, witness_schedule.

  # Otherwise, db configs will remain defualt and data will be stored in
  # the path of "output-directory" or which is set by "-d" ("--output-directory").

  # Attention: name is a required field that must be set !!!
  properties = [
    //    {
    //      name = "account",
    //      path = "storage_directory_test",
    //      createIfMissing = true,
    //      paranoidChecks = true,
    //      verifyChecksums = true,
    //      compressionType = 1,        // compressed with snappy
    //      blockSize = 4096,           // 4  KB =         4 * 1024 B
    //      writeBufferSize = 10485760, // 10 MB = 10 * 1024 * 1024 B
    //      cacheSize = 10485760,       // 10 MB = 10 * 1024 * 1024 B
    //      maxOpenFiles = 100
    //    },
    //    {
    //      name = "account-index",
    //      path = "storage_directory_test",
    //      createIfMissing = true,
    //      paranoidChecks = true,
    //      verifyChecksums = true,
    //      compressionType = 1,        // compressed with snappy
    //      blockSize = 4096,           // 4  KB =         4 * 1024 B
    //      writeBufferSize = 10485760, // 10 MB = 10 * 1024 * 1024 B
    //      cacheSize = 10485760,       // 10 MB = 10 * 1024 * 1024 B
    //      maxOpenFiles = 100
    //    },
  ]

}
node.discovery = {
  enable = true
  persist = true
  bind.ip = ""
  external.ip = null
}

node.backup {
  port = 10001
  priority = 8
  members = [
  ]
}

node {
  # trust node for solidity node
  # trustNode = "ip:port"
  trustNode = "127.0.0.1:50051"
  zenTokenId = 1000003
  fullNodeAllowShieldedTransaction = true


  # expose extension api to public or not
  walletExtensionApi = true

  listen.port = 18888

  connection.timeout = 2

  tcpNettyWorkThreadNum = 0

  udpNettyWorkThreadNum = 1

  # Number of validate sign thread, default availableProcessors / 2
  validateSignThreadNum = 16

  maxActiveNodes = 30

  maxActiveNodesWithSameIp = 2

  minParticipationRate = 0

  maxConnectNumberFactor = 1
  receiveTcpMinDataLength = 512

  p2p {
    version = 09251646
  }

active = [
    # Active establish connection in any case
    # Sample entries:
    # "ip:port",
    # "ip:port"
  ]

  passive = [
    # Passive accept connection in any case
    # Sample entries:
    # "ip:port",
    # "ip:port"
  ]
#  fastForward = [
#    "47.75.38.145:18888"
#  ]
  http {
    fullNodePort = 8443
    solidityPort = 8091
  }

rpc {
    port = 50051

    # Number of gRPC thread, default availableProcessors / 2
    thread = 16

    # The maximum number of concurrent calls permitted for each incoming connection
    # maxConcurrentCallsPerConnection =

    # The HTTP/2 flow control window, default 1MB
    # flowControlWindow =

    # Connection being idle for longer than which will be gracefully terminated
    maxConnectionIdleInMillis = 60000

    # Connection lasting longer than which will be gracefully terminated
    # maxConnectionAgeInMillis =

    # The maximum message size allowed to be received on the server, default 4MB
    # maxMessageSize =

    # The maximum size of header list allowed to be received, default 8192
    # maxHeaderListSize =
  }

}
```

I am running Odyssey 3.7 -- will try pegging to the branch `release_3.7_nodes_multi_witness`. Thanks

**Comment by marktoda** [comment]
I tried `release_3.7_nodes_multi_witness` and had the same issue as before.

**Comment by trnhgquan** [comment]
Did you solve this issues?

**Comment by kevinchangg** [comment]
I have the same problem. Have you solved it?
