### ISSUE TITLE
Full node that won't complete synchronize

### ISSUE THREAD

**Issue by guoquanwu** [tronprotocol/java-tron#3136]
### 1. What did you do?

Ours has been working fine for about a year, but recently it's no longer able to keep up with the latest blocks.  This isn't a CPU/disk/memory issue; rather, our node downloads blocks for about 60 seconds after startup and then no longer downloads anymore.  If I restart the node, it downloads more blocks for about a minute then stops downloading again.  I feel like this is a configuration issue but I'm not sure what parameter might need to be changed

### 2. What did you expect to see?

Fullnode keeps on syncing the blocks

### 3. What did you see instead?

Fullnode downloads blocks for about 60 seconds after startup and then no longer downloads anymore

23:17:16.023 INFO  [pool-42-thread-1] [DB](Manager.java:1306) Retry for tx id: 9f9e9d44c614134e3efa8668f35b0efb3419ea87ade0c84f41da6258111a4b5b
23:17:16.388 INFO  [pool-42-thread-1] [VM](Program.java:978) minTimeRatio: 0.0, maxTimeRatio: 5.0, vm should end time in us: 432868158570, vm now time in us: 432868183926, vm start time in us: 432868147173
23:17:16.392 INFO  [pool-42-thread-1] [VM](VM.java:1445) VM halted: [CPU timeout for 'DUP2' operation executing]
23:17:16.397 INFO  [pool-42-thread-1] [VM](VM.java:1445) VM halted: [CPU timeout for 'DUP2' operation executing]
23:17:16.399 INFO  [pool-42-thread-1] [VM](VM.java:1445) VM halted: [CPU timeout for 'DUP2' operation executing]
23:17:16.400 INFO  [pool-42-thread-1] [VM](VM.java:1445) VM halted: [CPU timeout for 'DUP2' operation executing]
23:17:16.400 INFO  [pool-42-thread-1] [VM](VMActuator.java:248) timeout: CPU timeout for 'DUP2' operation executing
23:17:16.401 INFO  [pool-42-thread-1] [DB](Manager.java:1311) Retry result for tx id: 9f9e9d44c614134e3efa8668f35b0efb3419ea87ade0c84f41da6258111a4b5b, tx resultCode in receipt: OUT_OF_TIME
23:17:16.404 INFO  [pool-42-thread-1] [TransactionTrace](TransactionTrace.java:254) this tx id: 9f9e9d44c614134e3efa8668f35b0efb3419ea87ade0c84f41da6258111a4b5b, the resultCode in received block: SUCCESS, the resultCode in self: OUT_OF_TIME
23:17:16.454 ERROR [pool-42-thread-1] [DB](Manager.java:1142) Different resultCode
org.tron.core.exception.ReceiptCheckErrException: Different resultCode
	at org.tron.core.db.TransactionTrace.check(TransactionTrace.java:258)
	at org.tron.core.db.Manager.processTransaction(Manager.java:1314)
	at org.tron.core.db.Manager.processBlock(Manager.java:1535)
	at org.tron.core.db.Manager.applyBlock(Manager.java:922)
	at org.tron.core.db.Manager.pushBlock(Manager.java:1135)
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:197)
	at org.tron.core.net.service.SyncService.processSyncBlock(SyncService.java:262)
	at org.tron.core.net.service.SyncService.lambda$handleSyncBlock$8(SyncService.java:251)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.tron.core.net.service.SyncService.handleSyncBlock(SyncService.java:234)
	at org.tron.core.net.service.SyncService.lambda$init$1(SyncService.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
23:17:16.469 INFO  [pool-25-thread-1] [net](PeerClient.java:70) connect peer 47.90.247.55 18888

**Comment by xueyafighting** [comment]
Try to change **maxTimeRatio** bigger, to see whether it works.
In the log, vm timeout when execute some contract, it may be caused by high cpu load, so try to increase the maxTimeRatio to give a longer time for executing the contract

**Comment by ccdonn** [comment]
same situation, but different Exception. Any idea?

```
12:30:54.086 INFO  [pool-42-thread-1] [DB](Manager.java:1715) PreValidate Transaction Sign, size:2,block num:6359585
12:30:54.118 ERROR [pool-42-thread-1] [DB](Manager.java:1142) record is fail, skip proof
org.tron.core.exception.ZkProofValidateException: record is fail, skip proof
	at org.tron.core.actuator.ShieldedTransferActuator.checkProof(ShieldedTransferActuator.java:284)
	at org.tron.core.actuator.ShieldedTransferActuator.validate(ShieldedTransferActuator.java:265)
	at org.tron.common.runtime.RuntimeImpl.execute(RuntimeImpl.java:64)
	at org.tron.core.db.TransactionTrace.exec(TransactionTrace.java:169)
	at org.tron.core.db.Manager.processTransaction(Manager.java:1299)
	at org.tron.core.db.Manager.processBlock(Manager.java:1535)
	at org.tron.core.db.Manager.applyBlock(Manager.java:922)
	at org.tron.core.db.Manager.pushBlock(Manager.java:1135)
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:197)
	at org.tron.core.net.service.SyncService.processSyncBlock(SyncService.java:262)
	at org.tron.core.net.service.SyncService.lambda$handleSyncBlock$8(SyncService.java:251)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.tron.core.net.service.SyncService.handleSyncBlock(SyncService.java:234)
	at org.tron.core.net.service.SyncService.lambda$init$1(SyncService.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
12:30:54.120 ERROR [pool-42-thread-1] [net](TronNetDelegate.java:223) Process block failed, Num:6359585,ID:0000000000610a215fada79175f763d5372374597bf7ce33741fa8da0380a8af, reason: record is fail, skip proof.
12:30:54.121 ERROR [pool-42-thread-1] [net](SyncService.java:264) Process sync block Num:6359585,ID:0000000000610a215fada79175f763d5372374597bf7ce33741fa8da0380a8af failed.
org.tron.core.exception.P2pException: org.tron.core.exception.ZkProofValidateException: record is fail, skip proof
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:224)
	at org.tron.core.net.service.SyncService.processSyncBlock(SyncService.java:262)
	at org.tron.core.net.service.SyncService.lambda$handleSyncBlock$8(SyncService.java:251)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.tron.core.net.service.SyncService.handleSyncBlock(SyncService.java:234)
	at org.tron.core.net.service.SyncService.lambda$init$1(SyncService.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.tron.core.exception.ZkProofValidateException: record is fail, skip proof
	at org.tron.core.actuator.ShieldedTransferActuator.checkProof(ShieldedTransferActuator.java:284)
	at org.tron.core.actuator.ShieldedTransferActuator.validate(ShieldedTransferActuator.java:265)
	at org.tron.common.runtime.RuntimeImpl.execute(RuntimeImpl.java:64)
	at org.tron.core.db.TransactionTrace.exec(TransactionTrace.java:169)
	at org.tron.core.db.Manager.processTransaction(Manager.java:1299)
	at org.tron.core.db.Manager.processBlock(Manager.java:1535)
	at org.tron.core.db.Manager.applyBlock(Manager.java:922)
	at org.tron.core.db.Manager.pushBlock(Manager.java:1135)
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:197)
	... 12 common frames omitted
```

**Comment by guoquanwu** [comment]
> same situation, but different Exception. Any idea?
> 
> ```
> 12:30:54.086 INFO  [pool-42-thread-1] [DB](Manager.java:1715) PreValidate Transaction Sign, size:2,block num:6359585
> 12:30:54.118 ERROR [pool-42-thread-1] [DB](Manager.java:1142) record is fail, skip proof
> org.tron.core.exception.ZkProofValidateException: record is fail, skip proof
> 	at org.tron.core.actuator.ShieldedTransferActuator.checkProof(ShieldedTransferActuator.java:284)
> 	at org.tron.core.actuator.ShieldedTransferActuator.validate(ShieldedTransferActuator.java:265)
> 	at org.tron.common.runtime.RuntimeImpl.execute(RuntimeImpl.java:64)
> 	at org.tron.core.db.TransactionTrace.exec(TransactionTrace.java:169)
> 	at org.tron.core.db.Manager.processTransaction(Manager.java:1299)
> 	at org.tron.core.db.Manager.processBlock(Manager.java:1535)
> 	at org.tron.core.db.Manager.applyBlock(Manager.java:922)
> 	at org.tron.core.db.Manager.pushBlock(Manager.java:1135)
> 	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:197)
> 	at org.tron.core.net.service.SyncService.processSyncBlock(SyncService.java:262)
> 	at org.tron.core.net.service.SyncService.lambda$handleSyncBlock$8(SyncService.java:251)
> 	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
> 	at org.tron.core.net.service.SyncService.handleSyncBlock(SyncService.java:234)
> 	at org.tron.core.net.service.SyncService.lambda$init$1(SyncService.java:77)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> 12:30:54.120 ERROR [pool-42-thread-1] [net](TronNetDelegate.java:223) Process block failed, Num:6359585,ID:0000000000610a215fada79175f763d5372374597bf7ce33741fa8da0380a8af, reason: record is fail, skip proof.
> 12:30:54.121 ERROR [pool-42-thread-1] [net](SyncService.java:264) Process sync block Num:6359585,ID:0000000000610a215fada79175f763d5372374597bf7ce33741fa8da0380a8af failed.
> org.tron.core.exception.P2pException: org.tron.core.exception.ZkProofValidateException: record is fail, skip proof
> 	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:224)
> 	at org.tron.core.net.service.SyncService.processSyncBlock(SyncService.java:262)
> 	at org.tron.core.net.service.SyncService.lambda$handleSyncBlock$8(SyncService.java:251)
> 	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
> 	at org.tron.core.net.service.SyncService.handleSyncBlock(SyncService.java:234)
> 	at org.tron.core.net.service.SyncService.lambda$init$1(SyncService.java:77)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: org.tron.core.exception.ZkProofValidateException: record is fail, skip proof
> 	at org.tron.core.actuator.ShieldedTransferActuator.checkProof(ShieldedTransferActuator.java:284)
> 	at org.tron.core.actuator.ShieldedTransferActuator.validate(ShieldedTransferActuator.java:265)
> 	at org.tron.common.runtime.RuntimeImpl.execute(RuntimeImpl.java:64)
> 	at org.tron.core.db.TransactionTrace.exec(TransactionTrace.java:169)
> 	at org.tron.core.db.Manager.processTransaction(Manager.java:1299)
> 	at org.tron.core.db.Manager.processBlock(Manager.java:1535)
> 	at org.tron.core.db.Manager.applyBlock(Manager.java:922)
> 	at org.tron.core.db.Manager.pushBlock(Manager.java:1135)
> 	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:197)
> 	... 12 common frames omitted
> ```

which branch do you use?  If you are accessing the nile net, compile and use this branch: vm_shielded_nile

**Comment by ccdonn** [comment]
i use nile testnet, sorry for did not mention that.
but i did build by feature/vm_shielded_nile, commit 67f20f404988b0cb0f4a157240a7338b4048ab7a.

**Comment by Benson0224** [comment]
Please download the backup data from "http://47.90.243.177/" and start sync based on the latest backup data if you want to join nile.
Due to some historical reasons, sync from 0 will leads to issues.
