### ISSUE TITLE
NullPointerException in BlockchainTest.testFindTransaction

### ISSUE THREAD

**Issue by seanrobbins** [tronprotocol/java-tron#32]
1. What did you do?
- Clone java-tron repository
- Import java-tron into IntelliJ
- Open BlockchainTest.java
- Run test testFindTransaction

2. What did you expect to see?
- Test pass

3. What did you see instead?
- Test fails with a NullPointerException

java.lang.NullPointerException
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:209)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:214)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at org.tron.protos.core.TronBlock$Block.parseFrom(TronBlock.java:313)
	at org.tron.core.BlockchainIterator.next(BlockchainIterator.java:46)
	at org.tron.core.Blockchain.findTransaction(Blockchain.java:116)
	at org.tron.core.BlockchainTest.testFindTransaction(BlockchainTest.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

Exception thrown is from the following code in BlockchainIterator. The following returns null:

`byte[] value = blockchain.getBlockDB().get(index);`

And the exception is thrown when the following line executes with null as the value:

` block = TronBlock.Block.parseFrom(value);`

**Comment by seanrobbins** [comment]
Attempted a fix for these unit test issues in https://github.com/tronprotocol/java-tron/pull/33

**Comment by seanrobbins** [comment]
Fixes for the issues with these unit tests were merged to the develop branch in these PRs:
https://github.com/tronprotocol/java-tron/pull/33
https://github.com/tronprotocol/java-tron/pull/34

I'm going to close this issue.
