### ISSUE TITLE
Full node sometimes stuck in a specific block

### ISSUE THREAD

**Issue by mmo2112** [tronprotocol/java-tron#3481]
### 1. What did you do?

Hi, a few days ago my node has been stuck many times at a specific block. I have cleared previous data by removing the output-directory then getting the latest backup on Trongrid but this issue can not be resolved well. After extracting the data completely, the node can sync for only a few blocks then stopping at an undefined block... Please help me to fix it.
I have also tried with 3 latest binary version 4.0.1, 4.0.2, 4.1.0 but none of them work, here is the log:
```
03:57:35.358 INFO  [pool-43-thread-1] [DB](Manager.java:1163) pushBlock block number:24680930, cost/txs:205/42
03:57:35.358 INFO  [pool-43-thread-1] [net](TronNetDelegate.java:199) Success process block Num:24680930,ID:00000000017899e2d0c1576530f5e94d72d43aea0434ed61662419f9521c5b66.
03:57:35.362 INFO  [pool-43-thread-1] [DB](Manager.java:1715) PreValidate Transaction Sign, size:53,block num:24680931
03:57:35.532 INFO  [pool-43-thread-1] [TransactionTrace](TransactionTrace.java:254) this tx id: 4ecc54d3f1d797ba04679f561b5ffdd49b004c22e25b65d827d7fe83432d22ae, the resultCode in received block: OUT_OF_TIME, the resultCode in self: SUCCESS
03:57:35.533 ERROR [pool-43-thread-1] [DB](Manager.java:1142) Different resultCode
org.tron.core.exception.ReceiptCheckErrException: Different resultCode
	at org.tron.core.db.TransactionTrace.check(TransactionTrace.java:258)
	at org.tron.core.db.Manager.processTransaction(Manager.java:1314)
	at org.tron.core.db.Manager.processBlock(Manager.java:1535)
	at org.tron.core.db.Manager.applyBlock(Manager.java:922)
	at org.tron.core.db.Manager.pushBlock(Manager.java:1135)
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:197)
	at org.tron.core.net.service.SyncService.processSyncBlock(SyncService.java:262)
	at org.tron.core.net.service.SyncService.lambda$handleSyncBlock$8(SyncService.java:251)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.tron.core.net.service.SyncService.handleSyncBlock(SyncService.java:234)
	at org.tron.core.net.service.SyncService.lambda$init$1(SyncService.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
03:57:35.536 ERROR [pool-43-thread-1] [net](TronNetDelegate.java:223) Process block failed, Num:24680931,ID:00000000017899e38abb4491aeee19cf13dfd1e0750b5a81b0684abfd20b560e, reason: Different resultCode.
03:57:35.537 ERROR [pool-43-thread-1] [net](SyncService.java:264) Process sync block Num:24680931,ID:00000000017899e38abb4491aeee19cf13dfd1e0750b5a81b0684abfd20b560e failed.
org.tron.core.exception.P2pException: org.tron.core.exception.ReceiptCheckErrException: Different resultCode
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:224)
	at org.tron.core.net.service.SyncService.processSyncBlock(SyncService.java:262)
	at org.tron.core.net.service.SyncService.lambda$handleSyncBlock$8(SyncService.java:251)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.tron.core.net.service.SyncService.handleSyncBlock(SyncService.java:234)
	at org.tron.core.net.service.SyncService.lambda$init$1(SyncService.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.tron.core.exception.ReceiptCheckErrException: Different resultCode
	at org.tron.core.db.TransactionTrace.check(TransactionTrace.java:258)
	at org.tron.core.db.Manager.processTransaction(Manager.java:1314)
	at org.tron.core.db.Manager.processBlock(Manager.java:1535)
	at org.tron.core.db.Manager.applyBlock(Manager.java:922)
	at org.tron.core.db.Manager.pushBlock(Manager.java:1135)
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:197)
```

### 2. What did you expect to see?
I have searched but not found any related to my issue. Another inverse issue is "the resultCode in received block: SUCESS, the resultCode in self: OUT_OF_TIME" is fixed by increasing maxTimeRatio, I have also increased it to 60 but it's still not working.
https://github.com/tronprotocol/java-tron/issues/3136

**Comment by mmo2112** [comment]
I downloaded the latest data again (FullNode-24708645-4.0.1-output-directory.tgz), it was stuck on another block, please help me resolve it...
Here is log:
```
09:38:25.441 INFO  [pool-43-thread-1] [DB](Manager.java:1163) pushBlock block number:24708648, cost/txs:434/75
09:38:25.441 INFO  [pool-43-thread-1] [net](TronNetDelegate.java:199) Success process block Num:24708648,ID:000000000179062869092774993ca6c056701a103c4015d0b50a9e2ec0b3489d.
09:38:25.445 INFO  [pool-43-thread-1] [DB](Manager.java:1715) PreValidate Transaction Sign, size:70,block num:24708649
09:38:25.598 INFO  [pool-43-thread-1] [TransactionTrace](TransactionTrace.java:254) this tx id: 3ee00a0b7a355953a5ec7b8ad3941b514d4c946554d73a89c7eb2f03b7d47e9f, the resultCode in received block: OUT_OF_TIME, the resultCode in self: SUCCESS
09:38:25.600 ERROR [pool-43-thread-1] [DB](Manager.java:1142) Different resultCode
org.tron.core.exception.ReceiptCheckErrException: Different resultCode
	at org.tron.core.db.TransactionTrace.check(TransactionTrace.java:258)
	at org.tron.core.db.Manager.processTransaction(Manager.java:1314)
	at org.tron.core.db.Manager.processBlock(Manager.java:1535)
	at org.tron.core.db.Manager.applyBlock(Manager.java:922)
	at org.tron.core.db.Manager.pushBlock(Manager.java:1135)
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:197)
	at org.tron.core.net.service.SyncService.processSyncBlock(SyncService.java:262)
	at org.tron.core.net.service.SyncService.lambda$handleSyncBlock$8(SyncService.java:251)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.tron.core.net.service.SyncService.handleSyncBlock(SyncService.java:234)
	at org.tron.core.net.service.SyncService.lambda$init$1(SyncService.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
09:38:25.603 ERROR [pool-43-thread-1] [net](TronNetDelegate.java:223) Process block failed, Num:24708649,ID:00000000017906292cd3f32d0c02f9a51cb621969279b75c0c58bf04a90c1219, reason: Different resultCode.
09:38:25.604 ERROR [pool-43-thread-1] [net](SyncService.java:264) Process sync block Num:24708649,ID:00000000017906292cd3f32d0c02f9a51cb621969279b75c0c58bf04a90c1219 failed.
org.tron.core.exception.P2pException: org.tron.core.exception.ReceiptCheckErrException: Different resultCode
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:224)
	at org.tron.core.net.service.SyncService.processSyncBlock(SyncService.java:262)
	at org.tron.core.net.service.SyncService.lambda$handleSyncBlock$8(SyncService.java:251)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.tron.core.net.service.SyncService.handleSyncBlock(SyncService.java:234)
	at org.tron.core.net.service.SyncService.lambda$init$1(SyncService.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.tron.core.exception.ReceiptCheckErrException: Different resultCode
	at org.tron.core.db.TransactionTrace.check(TransactionTrace.java:258)
	at org.tron.core.db.Manager.processTransaction(Manager.java:1314)
	at org.tron.core.db.Manager.processBlock(Manager.java:1535)
	at org.tron.core.db.Manager.applyBlock(Manager.java:922)
	at org.tron.core.db.Manager.pushBlock(Manager.java:1135)
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:197)
```

**Comment by mmo2112** [comment]
Hi there, I have found the VM executed for this transaction `3ee00a0b7a355953a5ec7b8ad3941b514d4c946554d73a89c7eb2f03b7d47e9f` success:
![image](https://user-images.githubusercontent.com/19829652/98225855-d5073f00-1f87-11eb-8e23-a643d6e6ba7e.png)
But the data from the public API `https://developers.tron.network/reference#transaction-info-by-id` is different:
`{"id": "3ee00a0b7a355953a5ec7b8ad3941b514d4c946554d73a89c7eb2f03b7d47e9f","blockNumber": 24708649,"blockTimeStamp": 1604448612000,"contractResult": [""],"contract_address": "4190fac53bae5861145cc2d9ffc230af43802fc326","receipt": {"energy_usage": 1000000,"origin_energy_usage": 92972,"energy_usage_total": 1092972,"net_usage": 345,"result": "OUT_OF_TIME"},"result": "FAILED","resMessage": "4350552074696d656f757420666f722027505553483127206f7065726174696f6e20657865637574696e67"}`
//
So the different result code is thrown and I can't sync the next block.
`09:38:25.598 INFO  [pool-43-thread-1] [TransactionTrace](TransactionTrace.java:254) this tx id: 3ee00a0b7a355953a5ec7b8ad3941b514d4c946554d73a89c7eb2f03b7d47e9f, the resultCode in received block: OUT_OF_TIME, the resultCode in self: SUCCESS
09:38:25.600 ERROR [pool-43-thread-1] [DB](Manager.java:1142) Different resultCode
org.tron.core.exception.ReceiptCheckErrException: Different resultCode`

**Comment by mmo2112** [comment]
Update: I don't know what is wrong with the data from https://backups.trongrid.io/, I have downloaded many backups there, for this try is `FullNode-24737428-4.0.1-output-directory.tgz` but it seems the data has damaged, not original.
Now, I stuck at block #24738085 on tx id https://tronscan.org/#/transaction/54f65a9aba4210a3b79678c6503ca01726974ba44f3f2cefcde98ede541be15c
I have logged in the latest master branch:
```
error from: 41aebdfb88a86985589c457f2755d161a526910633
error to: 41ab76044ab36a9efdca55f72e7b6e74eac79a0812
error amount: 37888148
10:16:14.073 ERROR [pool-46-thread-1] [DB](Manager.java:982) Validate TransferContract error, balance is not sufficient.
org.tron.core.exception.ContractValidateException: Validate TransferContract error, balance is not sufficient.
10:16:14.075 ERROR [pool-46-thread-1] [net](TronNetDelegate.java:237) Process block failed, Num:24738085,ID:0000000001797925be8782785937e687db716358f9885d8627592dfdf809fe9e, reason: Validate TransferContract error, balance is not sufficient..
```
While the node contains data:
`{"address": "41aebdfb88a86985589c457f2755d161a526910633","balance": 37888135...}`
I really need a fresh backup of data, anyone from Asia may zip it and upload it to any cloud platform for me, I'm really upset about this stuck syncing problem for a week. If you don't have a high storage cloud, please contact me via mmo2112@gmail.com. Many thanks and have a good day.

**Comment by shydesky** [comment]
> Update: I don't know what is wrong with the data from https://backups.trongrid.io/, I have downloaded many backups there, for this try is `FullNode-24737428-4.0.1-output-directory.tgz` but it seems the data has damaged, not original.
> Now, I stuck at block #24738085 on tx id https://tronscan.org/#/transaction/54f65a9aba4210a3b79678c6503ca01726974ba44f3f2cefcde98ede541be15c
> I have logged in the latest master branch:
> 
> ```
> error from: 41aebdfb88a86985589c457f2755d161a526910633
> error to: 41ab76044ab36a9efdca55f72e7b6e74eac79a0812
> error amount: 37888148
> 10:16:14.073 ERROR [pool-46-thread-1] [DB](Manager.java:982) Validate TransferContract error, balance is not sufficient.
> org.tron.core.exception.ContractValidateException: Validate TransferContract error, balance is not sufficient.
> 10:16:14.075 ERROR [pool-46-thread-1] [net](TronNetDelegate.java:237) Process block failed, Num:24738085,ID:0000000001797925be8782785937e687db716358f9885d8627592dfdf809fe9e, reason: Validate TransferContract error, balance is not sufficient..
> ```
> 
> While the node contains data:
> `{"address": "41aebdfb88a86985589c457f2755d161a526910633","balance": 37888135...}`
> 
> I really need a fresh backup of data, anyone from Asia may zip it and upload it to any cloud platform for me, I'm really upset about this stuck syncing problem for a week. If you don't have a high storage cloud, please contact me via [mmo2112@gmail.com](mailto:mmo2112@gmail.com). Many thanks and have a good day.

hi, you can download the database here:
https://developers.tron.network/docs/mainnet-backups
if you encounter the "Different result code" problem, you can increase the maxTimeRatio. If the problem can not be fixed, you should improve the machine performance. 16cores and 32G RAM is recommended when syncing with the mainnet.

**Comment by mmo2112** [comment]
> > Update: I don't know what is wrong with the data from https://backups.trongrid.io/, I have downloaded many backups there, for this try is `FullNode-24737428-4.0.1-output-directory.tgz` but it seems the data has damaged, not original.
> > Now, I stuck at block #24738085 on tx id https://tronscan.org/#/transaction/54f65a9aba4210a3b79678c6503ca01726974ba44f3f2cefcde98ede541be15c
> > I have logged in the latest master branch:
> > ```
> > error from: 41aebdfb88a86985589c457f2755d161a526910633
> > error to: 41ab76044ab36a9efdca55f72e7b6e74eac79a0812
> > error amount: 37888148
> > 10:16:14.073 ERROR [pool-46-thread-1] [DB](Manager.java:982) Validate TransferContract error, balance is not sufficient.
> > org.tron.core.exception.ContractValidateException: Validate TransferContract error, balance is not sufficient.
> > 10:16:14.075 ERROR [pool-46-thread-1] [net](TronNetDelegate.java:237) Process block failed, Num:24738085,ID:0000000001797925be8782785937e687db716358f9885d8627592dfdf809fe9e, reason: Validate TransferContract error, balance is not sufficient..
> > ```
> > 
> > 
> > While the node contains data:
> > `{"address": "41aebdfb88a86985589c457f2755d161a526910633","balance": 37888135...}`
> > I really need a fresh backup of data, anyone from Asia may zip it and upload it to any cloud platform for me, I'm really upset about this stuck syncing problem for a week. If you don't have a high storage cloud, please contact me via [mmo2112@gmail.com](mailto:mmo2112@gmail.com). Many thanks and have a good day.
> 
> hi, you can download the database here:
> https://developers.tron.network/docs/mainnet-backups
> if you encounter the "Different result code" problem, you can increase the maxTimeRatio. If the problem can not be fixed, you should improve the machine performance. 16cores and 32G RAM is recommended when syncing with the mainnet.

Hi, thanks for your response. I have increased the ratio to 20. But I think this is an inverse case due to my VM not timeout, my VM execute it successfully while the receipt from the capsule is timeout. I will try on Sigapore official data and respond soon, thank you again and have a good day.

**Comment by mmo2112** [comment]
@shychrdw ,
Started with the option --debug causes VM error and can not sync. I've restart the node without it and it syncs successfully. Thank you for your support, case closed.
