### ISSUE TITLE
GreatVoyage-v4.1.1 java error on Ubuntu 20.04.1 LTS (Focal Fossa)

### ISSUE THREAD

**Issue by neshala** [tronprotocol/java-tron#3504]
Any idea what I am doing wrong?

### 1. What did you do?
I have downloaded FullNode.jar (GreatVoyage-v4.1.1) and installed jre and jdk from Oracle (java 11.0.9 2020-10-20 LTS and javac 11.0.9) but when I am getting errors. OS: Ubuntu Server 20.04.1 LTS (Focal Fossa)

### 2. What did you expect to see?
Active peers and blocks synced

### 3. What did you see instead?
The following errors:

`19:31:38.967 INFO  [TronJClientWorker-2] [net](TronChannelInitializer.java:48) Close channel:/47.245.129.144:18888 | 729678f74f1cd15ab228a4dc91d986d7b4c548c716ec392b5d9775b0ce8f6fc884a88f77c2ed7fe4dc52686bbfe774cf883597a6c8500c65a1793e0f5074617d
19:31:38.967 INFO  [TronJClientWorker-5] [net](TronChannelInitializer.java:48) Close channel:/84.239.4.54:18888 | 57e0aeb92e593d6094ec3d5908278d0cdd792ba9dd59a25394ea70999f0d98ec604e0bf6e54fe9570215f8dd144cd795b981327aaaee36056f17e6c9b9d83591
19:31:38.971 INFO  [TronJClientWorker-4] [net](HandshakeHandler.java:77) channel active, /195.201.167.237:18888
19:31:38.972 ERROR [TronJClientWorker-4] [net](Channel.java:150) Close peer /195.201.167.237:18888, exception caught
java.lang.NullPointerException: null
	at org.tron.core.ChainBaseManager.getGenesisBlockId(ChainBaseManager.java:349)
	at org.tron.common.overlay.server.HandshakeHandler.sendHelloMsg(HandshakeHandler.java:123)
	at org.tron.common.overlay.server.HandshakeHandler.channelActive(HandshakeHandler.java:81)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64)
	at io.netty.handler.timeout.IdleStateHandler.channelActive(IdleStateHandler.java:271)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199)
	at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:941)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:311)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:341)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:634)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:546)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by shydesky** [comment]
The JDK version should be Oracle JDK 1.8

**Comment by neshala** [comment]
Thanks a lot, that worked out.
