### ISSUE TITLE
Node does not sync, UnLinkedBlockException at 4.1.1 version

### ISSUE THREAD

**Issue by astudnev** [tronprotocol/java-tron#3581]
v 4.1.1 node does not sync today with errors:

```
15:51:08.461 ERROR [pool-46-thread-1] [net](SyncService.java:269) Process sync block Num:26036260,ID:00000000018d48245544fab7da72f92103bb732c6cd7e668f00e523823c6c528 failed.
org.tron.core.exception.P2pException: org.tron.core.exception.UnLinkedBlockException
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:238)
	at org.tron.core.net.service.SyncService.processSyncBlock(SyncService.java:266)
	at org.tron.core.net.service.SyncService.lambda$handleSyncBlock$8(SyncService.java:255)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.tron.core.net.service.SyncService.handleSyncBlock(SyncService.java:238)
	at org.tron.core.net.service.SyncService.lambda$init$1(SyncService.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.tron.core.exception.UnLinkedBlockException: null
	at org.tron.core.db.KhaosDatabase.push(KhaosDatabase.java:123)
	at org.tron.core.db.Manager.pushBlock(Manager.java:903)
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:210)
	... 12 common frames omitted

```

It stuck on block 26036259

**Comment by astudnev** [comment]
[tron.log](https://github.com/tronprotocol/java-tron/files/5721138/tron.log)

Full log on service re-start

**Comment by Yrp** [comment]
Was the server down or powered off while the process was running?

**Comment by astudnev** [comment]
Yes, very likely it was re-started for some reason

**Comment by Yrp** [comment]
> Yes, very likely it was re-started for some reason

It is highly likely that the database has been corrupted by server downtime or power failure.
You can download the snapshot of database

**Comment by astudnev** [comment]
Yes, thank i already did that. However is it possible to make some way of starting from corrupted state? Other cool feature will be able to clear state till some stable block.

**Comment by Yrp** [comment]
> Yes, thank i already did that. However is it possible to make some way of starting from corrupted state? Other cool feature will be able to clear state till some stable block.

Cool. I currently have a draft about starting from corrupted state and will refine it.
This issue will be closed and you can reopen it if you have problems about this.
