### ISSUE TITLE
Syncing Issue

### ISSUE THREAD

**Issue by m-e-r-k-l-e-root** [tronprotocol/java-tron#3604]
### 1. What did you do?
Attempt to start/sync tron full node (Great Voyage - v4.1.1)

### 2. What did you expect to see?
Successful block syncing.

### 3. What did you see instead?
/logs/tron.log fills with java exceptions, along with errors in which indicate peer connection has been closed, etc.

i.e.

my tron.log file consists of primarily errors such as the following:

`09:30:54.208 INFO  [TronJClientWorker-5] [net](TronChannelInitializer.java:48) Close channel:/47.74.131.233:18888 | 2bf048f5433c86d54af84887a225627e40d7a8a80a9843718fa967ec5d45fdec7883dc54e05a6c0607d86b242213b2bb2c7fa1a7027bbf8ce426a65d3b79f758
09:30:54.212 INFO  [TronJClientWorker-2] [net](HandshakeHandler.java:77) channel active, /47.74.226.54:18888
09:30:54.212 ERROR [TronJClientWorker-2] [net](Channel.java:150) Close peer /47.74.226.54:18888, exception caught
java.lang.NullPointerException: null
        at org.tron.core.ChainBaseManager.getGenesisBlockId(ChainBaseManager.java:349)
        at org.tron.common.overlay.server.HandshakeHandler.sendHelloMsg(HandshakeHandler.java:123)
        at org.tron.common.overlay.server.HandshakeHandler.channelActive(HandshakeHandler.java:81)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64)
        at io.netty.handler.timeout.IdleStateHandler.channelActive(IdleStateHandler.java:271)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1422)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199)
        at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:941)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:311)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:341)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:634)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:546)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at java.base/java.lang.Thread.run(Thread.java:834)
`

along with errors that look like:

`09:31:08.631 INFO  [TronJClientWorker-4] [net](TronChannelInitializer.java:48) Close channel:/161.117.184.66:18888 | 8099a6785ad391664a56d7bc4ec1ab5ee9579be7149c6c6d89165ff23afee0e416f91cf7b78d7c2aed665f52241ac02be4c506ac4f861622263607265c16fc58
09:31:10.393 WARN  [TronJClientWorker-5] [net](PeerClient.java:58) connect to 47.242.229.146:18888 fail,cause:connection timed out: /47.242.229.146:18888
09:31:10.394 INFO  [TronJClientWorker-5] [net](TronChannelInitializer.java:48) Close channel:null | <null>`

- I am using this config file: [config.conf](https://github.com/tronprotocol/tron-deployment/blob/master/main_net_config.conf)
- all ports java-tron requires to be opened are open (i.e. UDP port 18888, etc., etc.)
- tried increasing `minTimeRatio` to 25.0+ in config
- added a few nodes to the `active [ ]` block in config

nothing seems to be working.

here is my full /logs/tron.log file: [tron.log](https://github.com/tronprotocol/java-tron/files/5756984/tron.log)
and here is the exact config file I'm using: [config.conf](https://github.com/tronprotocol/tron-deployment/blob/master/main_net_config.conf)

system specs:
3 TB SSD
16 Cores
Bandwidth 500M
32GB RAM

any help would be appreciated, thanks!

**Comment by m-e-r-k-l-e-root** [comment]
I've managed to resolve the issue. It was an issue with the machine I was using rather than java-tron itself. Running smooth like butter!

**Comment by FatNerdPeng** [comment]
Hey  guy,I got the same error as you and I want to know how you solved it,thanks!

**Comment by FatNerdPeng** [comment]
> Hey guy,I got the same error as you and I want to know how you solved it,thanks!

I got it done, the jdk environment is wrong, only version 1.8 can be used.
