### ISSUE TITLE
Unable to run a Nile node

### ISSUE THREAD

**Issue by oikos1** [tronprotocol/java-tron#3621]
I am having trouble setting up a Nile node. Here are the steps I followed:

1) Git clone tronprotocol/javatron git checkout branch nile_4.1.2 and compile with gradlew build
2) Fetch config file from https://nileex.io/join/getJoinPage
3) Download backup from http://47.90.243.177/ and restore output-directory

 ```
Jan 19 01:35:58 NLDW3-5-38-2 java[27510]: 2021-01-19 01:35:58.432 INFO  [TronJClientWorker-10] net [HandshakeHandler.java:77] - channel active, /47.90.214.183:18888
Jan 19 01:35:58 NLDW3-5-38-2 java[27510]: 2021-01-19 01:35:58.432 ERROR [TronJClientWorker-10] net [Channel.java:150] - Close peer /47.90.214.183:18888, exception caught
Jan 19 01:35:58 NLDW3-5-38-2 java[27510]: java.lang.NullPointerException: null
Jan 19 01:35:58 NLDW3-5-38-2 java[27510]:         at org.tron.core.ChainBaseManager.getGenesisBlockId(ChainBaseManager.java:359)
Jan 19 01:35:58 NLDW3-5-38-2 java[27510]:         at org.tron.common.overlay.server.HandshakeHandler.sendHelloMsg(HandshakeHandler.java:123)
Jan 19 01:35:58 NLDW3-5-38-2 java[27510]:         at org.tron.common.overlay.server.HandshakeHandler.channelActive(HandshakeHandler.java:81)
Jan 19 01:35:58 NLDW3-5-38-2 java[27510]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213)```

**Comment by Benson0224** [comment]
can you please help to provide the full log, thanks.

**Comment by oikos1** [comment]
The culprit was that when I was starting java-tron from a service file without setting the JAVA_HOME environment variable to the correct value. The error message should be a bit more informative though. I am closing this, thank you.
