### ISSUE TITLE
The height of the Shasta testnet can only be synchronized to 111842

### ISSUE THREAD

**Issue by bwcsswcx** [tronprotocol/java-tron#3676]
Hello,

The height of the Shasta testnet can only be synchronized to 111842 ，The versions of the program I tried are **Odyssey-v3.6.5** and **GreatVoyage-v4.1.2**,the configuration file used is **https://raw.githubusercontent.com/tronprotocol/TronDeployment/master/test_net_config.conf**, and the startup method is  **java -Xmx12g -XX:+UseConcMarkSweepGC -jar FullNode.jar -c test_net_config.conf**, try to delete the **log** and **output-directory** files and re-synchronize, the synchronization height can only reach 111842.

[root@localhost ~]#   curl -X POST http://127.0.0.1:8090/wallet/getnowblock
{"blockID":"000000000001b4e2ce2918536b4bd6e865cc14a6acbd1fd35ffe9ec21389f205","block_header":{"raw_data":{"number":111842,"txTrieRoot":"0000000000000000000000000000000000000000000000000000000000000000","witness_address":"41a6d8443e85fe275b5ca6e8eb895bdfde60f4f261","parentHash":"000000000001b4e16fca040e61e304447b737c52f34d66164860abc6fe3a4caa","version":9,"timestamp":1562314029000},"witness_signature":"c4ba9c3c6e1ae48b7c3e8b3b994f2ce1a89241cf63bc6606b187c256b0b4b4d95371ad0195237a57dafe06952e093d4f6fab49702e219d55d9239809b80b8f6700"}}

 Please help

**Comment by bwcsswcx** [comment]
error log:
11:42:29.241 INFO  [pool-37-thread-1] [DB](Manager.java:1095) pushBlock block number:111842, cost/txs:2/0
11:42:29.241 INFO  [pool-37-thread-1] [net](TronNetDelegate.java:189) Success process block Num:111842,ID:000000000001b4e2ce2918536b4bd6e865cc14a6acbd1fd35ffe9ec21389f205.
11:42:29.242 INFO  [pool-37-thread-1] [witness](WitnessController.java:222) scheduledWitness:41103181fb567cced7693d9de7ff5818d44695571b, currentSlot:520771344
11:42:29.243 INFO  [pool-37-thread-1] [DB](Manager.java:1865) PreValidate Transaction Sign, size:1,block num:111843
11:42:29.246 ERROR [pool-37-thread-1] [DB](Manager.java:1074) not support code : 27
org.tron.core.exception.ContractValidateException: not support code : 27
	at org.tron.core.services.ProposalService$ProposalType.getEnum(ProposalService.java:78)
	at org.tron.core.services.ProposalService.validator(ProposalService.java:99)
	at org.tron.core.actuator.ProposalCreateActuator.validateValue(ProposalCreateActuator.java:138)
	at org.tron.core.actuator.ProposalCreateActuator.validate(ProposalCreateActuator.java:131)
	at org.tron.common.runtime.RuntimeImpl.precompiled(RuntimeImpl.java:172)
	at org.tron.common.runtime.RuntimeImpl.execute(RuntimeImpl.java:181)
	at org.tron.core.db.TransactionTrace.exec(TransactionTrace.java:167)
	at org.tron.core.db.Manager.processTransaction(Manager.java:1251)
	at org.tron.core.db.Manager.processBlock(Manager.java:1563)
	at org.tron.core.db.Manager.applyBlock(Manager.java:862)
	at org.tron.core.db.Manager.pushBlock(Manager.java:1069)
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:187)
	at org.tron.core.net.service.SyncService.processSyncBlock(SyncService.java:262)
	at org.tron.core.net.service.SyncService.lambda$handleSyncBlock$8(SyncService.java:251)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.tron.core.net.service.SyncService.handleSyncBlock(SyncService.java:234)
	at org.tron.core.net.service.SyncService.lambda$init$1(SyncService.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
11:42:29.248 ERROR [pool-37-thread-1] [net](SyncService.java:264) Process sync block Num:111843,ID:000000000001b4e3e02203b1f7765948dd53f21bc397b5807237b70cceac7f9f failed.
org.tron.core.exception.P2pException: org.tron.core.exception.ContractValidateException: not support code : 27
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:207)
	at org.tron.core.net.service.SyncService.processSyncBlock(SyncService.java:262)
	at org.tron.core.net.service.SyncService.lambda$handleSyncBlock$8(SyncService.java:251)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.tron.core.net.service.SyncService.handleSyncBlock(SyncService.java:234)
	at org.tron.core.net.service.SyncService.lambda$init$1(SyncService.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.tron.core.exception.ContractValidateException: not support code : 27
	at org.tron.core.services.ProposalService$ProposalType.getEnum(ProposalService.java:78)
	at org.tron.core.services.ProposalService.validator(ProposalService.java:99)
	at org.tron.core.actuator.ProposalCreateActuator.validateValue(ProposalCreateActuator.java:138)
	at org.tron.core.actuator.ProposalCreateActuator.validate(ProposalCreateActuator.java:131)
	at org.tron.common.runtime.RuntimeImpl.precompiled(RuntimeImpl.java:172)
	at org.tron.common.runtime.RuntimeImpl.execute(RuntimeImpl.java:181)
	at org.tron.core.db.TransactionTrace.exec(TransactionTrace.java:167)
	at org.tron.core.db.Manager.processTransaction(Manager.java:1251)
	at org.tron.core.db.Manager.processBlock(Manager.java:1563)
	at org.tron.core.db.Manager.applyBlock(Manager.java:862)
	at org.tron.core.db.Manager.pushBlock(Manager.java:1069)
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:187)
	... 12 common frames omitted
11:42:29.249 INFO  [pool-37-thread-1] [net](Channel.java:138) Send to /18.166.30.26:18888 online-time 264s, type: P2P_DISCONNECT
reason: BAD_BLOCK
11:42:29.250 INFO  [pool-37-thread-1] [net](Channel.java:138) Send to /47.252.81.247:18888 online-time 426s, type: P2P_DISCONNECT
reason: BAD_BLOCK

**Comment by kunlunxuejue11** [comment]
Unable to build a node to link the shasta network, Which configuration file you use is not Shasta's configuration file.

**Comment by bwcsswcx** [comment]
> Unable to build a node to link the shasta network, Which configuration file you use is not Shasta's configuration file.

Can you share the template configuration file of the Shasta test network? Thank you.

**Comment by Benson0224** [comment]
as @kunlunxuejue11  mentioned, You cannot join shasta testnet. 
You can join Nile testnet if you really want to join our testnet. 
here is the guide on how to join Nile. thanks: https://nileex.io/join/getJoinPage

**Comment by Benson0224** [comment]
We will close this issue since no update for a long time.
Please feel free to reopen it if you still see the issue. thanks
