### ISSUE TITLE
Fullnode with event subscribe enabled

### ISSUE THREAD

**Issue by CerberusGR** [tronprotocol/java-tron#3724]
### 1. What did you do?
I tried to run FullNode.jar with event subscribe enabled on Ubuntu 20.04 
__java -jar FullNode4.1.3.jar -c main_net_config.conf -es__

FullNode without event subscribe works fine.

__java -version:
java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)__

### 2. What did you expect to see?
No errors

### 3. What did you see instead?

07:26:48.656 INFO  [main] [app](FullNode.java:48) Full node running.
07:26:49.507 WARN  [main] [app](LocalWitnesses.java:104) privateKey is null
07:26:49.869 INFO  [main] [app](Args.java:942) Bind address wasn't set, Punching to identify it...
07:26:50.198 INFO  [main] [app](Args.java:945) UDP local bound to: 192.168.145.130
07:26:50.199 INFO  [main] [app](Args.java:960) External IP wasn't set, using checkip.amazonaws.com to identify it...
07:26:50.597 INFO  [main] [app](Args.java:974) External address identified: 85.75.4.247
07:26:50.629 INFO  [main] [app](Args.java:1057) 

07:26:50.630 INFO  [main] [app](Args.java:1058) ************************ Net config ************************
07:26:50.630 INFO  [main] [app](Args.java:1059) P2P version: 11111
07:26:50.631 INFO  [main] [app](Args.java:1060) Bind IP: 192.168.145.130
07:26:50.632 INFO  [main] [app](Args.java:1061) External IP: 85.75.4.247
07:26:50.632 INFO  [main] [app](Args.java:1062) Listen port: 18888
07:26:50.634 INFO  [main] [app](Args.java:1063) Discover enable: true
07:26:50.634 INFO  [main] [app](Args.java:1064) Active node size: 0
07:26:50.635 INFO  [main] [app](Args.java:1065) Passive node size: 0
07:26:50.635 INFO  [main] [app](Args.java:1066) FastForward node size: 2
07:26:50.636 INFO  [main] [app](Args.java:1067) Seed node size: 1
07:26:50.637 INFO  [main] [app](Args.java:1068) Max connection: 30
07:26:50.638 INFO  [main] [app](Args.java:1069) Max connection with same IP: 2
07:26:50.639 INFO  [main] [app](Args.java:1070) Solidity threads: 2
07:26:50.639 INFO  [main] [app](Args.java:1071) ************************ Backup config ************************
07:26:50.640 INFO  [main] [app](Args.java:1072) Backup priority: 8
07:26:50.640 INFO  [main] [app](Args.java:1073) Backup listen port: 10001
07:26:50.641 INFO  [main] [app](Args.java:1074) Backup listen keepAliveInterval: 3000
07:26:50.642 INFO  [main] [app](Args.java:1075) Backup member size: 0
07:26:50.643 INFO  [main] [app](Args.java:1076) ************************ Code version *************************
07:26:50.643 INFO  [main] [app](Args.java:1077) Code version : 4.1.3
07:26:50.644 INFO  [main] [app](Args.java:1078) Version code: 15309
07:26:50.644 INFO  [main] [app](Args.java:1079) ************************ DB config *************************
07:26:50.645 INFO  [main] [app](Args.java:1080) DB version : 2
07:26:50.645 INFO  [main] [app](Args.java:1081) DB engine : LEVELDB
07:26:50.648 INFO  [main] [app](Args.java:1082) ***************************************************************
07:26:50.649 INFO  [main] [app](Args.java:1083) 

07:26:50.650 INFO  [main] [app](FullNode.java:62) not in debug mode, it will check energy time
07:26:50.803 INFO  [main] [o.t.c.a.TronApplicationContext](AbstractApplicationContext.java:578) Refreshing org.tron.common.application.TronApplicationContext@3541cb24: startup date [Mon Apr 05 07:26:50 PDT 2021]; root of context hierarchy
07:26:53.726 INFO  [main] [o.s.b.f.a.AutowiredAnnotationBeanPostProcessor](AutowiredAnnotationBeanPostProcessor.java:153) JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
07:26:54.278 INFO  [main] [app](DefaultConfig.java:58) key-value data source created.
07:26:55.075 WARN  [main] [o.s.b.f.a.AutowiredAnnotationBeanPostProcessor](AutowiredAnnotationBeanPostProcessor.java:398) Autowired annotation is not supported on static fields: private static java.util.concurrent.ConcurrentHashMap org.tron.core.config.args.Args.solidityContractLogTriggerMap
07:26:55.076 WARN  [main] [o.s.b.f.a.AutowiredAnnotationBeanPostProcessor](AutowiredAnnotationBeanPostProcessor.java:398) Autowired annotation is not supported on static fields: private static java.util.concurrent.ConcurrentHashMap org.tron.core.config.args.Args.solidityContractEventTriggerMap
**07:26:55.156 ERROR [main] [discover](Node.java:52) Parse node failed, -es**
07:26:55.157 WARN  [main] [o.t.c.a.TronApplicationContext](AbstractApplicationContext.java:546) Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'applicationImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.net.TronNetService org.tron.common.application.ApplicationImpl.tronNetService; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tronNetService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.server.ChannelManager org.tron.core.net.TronNetService.channelManager; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'channelManager': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.server.SyncPool org.tron.common.overlay.server.ChannelManager.syncPool; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'syncPool': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.discover.node.NodeManager org.tron.common.overlay.server.SyncPool.nodeManager; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nodeManager' defined in URL [jar:file:/home/user/tron/java-tron2/deploy/fullnode/FullNode4.1.3.jar!/org/tron/common/overlay/discover/node/NodeManager.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.tron.common.overlay.discover.node.NodeManager]: Constructor threw exception; nested exception is java.lang.ArrayIndexOutOfBoundsException: 1
**07:26:55.174 ERROR [main] [app](DefaultConfig.java:40) Uncaught exception**
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'applicationImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.net.TronNetService org.tron.common.application.ApplicationImpl.tronNetService; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tronNetService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.server.ChannelManager org.tron.core.net.TronNetService.channelManager; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'channelManager': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.server.SyncPool org.tron.common.overlay.server.ChannelManager.syncPool; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'syncPool': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.discover.node.NodeManager org.tron.common.overlay.server.SyncPool.nodeManager; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nodeManager' defined in URL [jar:file:/home/user/tron/java-tron2/deploy/fullnode/FullNode4.1.3.jar!/org/tron/common/overlay/discover/node/NodeManager.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.tron.common.overlay.discover.node.NodeManager]: Constructor threw exception; nested exception is java.lang.ArrayIndexOutOfBoundsException: 1
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
	at org.tron.program.FullNode.main(FullNode.java:71)
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.net.TronNetService org.tron.common.application.ApplicationImpl.tronNetService; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tronNetService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.server.ChannelManager org.tron.core.net.TronNetService.channelManager; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'channelManager': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.server.SyncPool org.tron.common.overlay.server.ChannelManager.syncPool; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'syncPool': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.discover.node.NodeManager org.tron.common.overlay.server.SyncPool.nodeManager; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nodeManager' defined in URL [jar:file:/home/user/tron/java-tron2/deploy/fullnode/FullNode4.1.3.jar!/org/tron/common/overlay/discover/node/NodeManager.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.tron.common.overlay.discover.node.NodeManager]: Constructor threw exception; nested exception is java.lang.ArrayIndexOutOfBoundsException: 1
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:573)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 11 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tronNetService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.server.ChannelManager org.tron.core.net.TronNetService.channelManager; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'channelManager': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.server.SyncPool org.tron.common.overlay.server.ChannelManager.syncPool; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'syncPool': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.discover.node.NodeManager org.tron.common.overlay.server.SyncPool.nodeManager; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nodeManager' defined in URL [jar:file:/home/user/tron/java-tron2/deploy/fullnode/FullNode4.1.3.jar!/org/tron/common/overlay/discover/node/NodeManager.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.tron.common.overlay.discover.node.NodeManager]: Constructor threw exception; nested exception is java.lang.ArrayIndexOutOfBoundsException: 1
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1192)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1116)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:545)
	... 13 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.server.ChannelManager org.tron.core.net.TronNetService.channelManager; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'channelManager': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.server.SyncPool org.tron.common.overlay.server.ChannelManager.syncPool; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'syncPool': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.discover.node.NodeManager org.tron.common.overlay.server.SyncPool.nodeManager; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nodeManager' defined in URL [jar:file:/home/user/tron/java-tron2/deploy/fullnode/FullNode4.1.3.jar!/org/tron/common/overlay/discover/node/NodeManager.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.tron.common.overlay.discover.node.NodeManager]: Constructor threw exception; nested exception is java.lang.ArrayIndexOutOfBoundsException: 1
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:573)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 24 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'channelManager': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.server.SyncPool org.tron.common.overlay.server.ChannelManager.syncPool; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'syncPool': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.discover.node.NodeManager org.tron.common.overlay.server.SyncPool.nodeManager; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nodeManager' defined in URL [jar:file:/home/user/tron/java-tron2/deploy/fullnode/FullNode4.1.3.jar!/org/tron/common/overlay/discover/node/NodeManager.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.tron.common.overlay.discover.node.NodeManager]: Constructor threw exception; nested exception is java.lang.ArrayIndexOutOfBoundsException: 1
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1192)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1116)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:545)
	... 26 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.server.SyncPool org.tron.common.overlay.server.ChannelManager.syncPool; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'syncPool': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.discover.node.NodeManager org.tron.common.overlay.server.SyncPool.nodeManager; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nodeManager' defined in URL [jar:file:/home/user/tron/java-tron2/deploy/fullnode/FullNode4.1.3.jar!/org/tron/common/overlay/discover/node/NodeManager.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.tron.common.overlay.discover.node.NodeManager]: Constructor threw exception; nested exception is java.lang.ArrayIndexOutOfBoundsException: 1
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:573)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 37 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'syncPool': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.discover.node.NodeManager org.tron.common.overlay.server.SyncPool.nodeManager; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nodeManager' defined in URL [jar:file:/home/user/tron/java-tron2/deploy/fullnode/FullNode4.1.3.jar!/org/tron/common/overlay/discover/node/NodeManager.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.tron.common.overlay.discover.node.NodeManager]: Constructor threw exception; nested exception is java.lang.ArrayIndexOutOfBoundsException: 1
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1192)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1116)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:545)
	... 39 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.discover.node.NodeManager org.tron.common.overlay.server.SyncPool.nodeManager; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nodeManager' defined in URL [jar:file:/home/user/tron/java-tron2/deploy/fullnode/FullNode4.1.3.jar!/org/tron/common/overlay/discover/node/NodeManager.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.tron.common.overlay.discover.node.NodeManager]: Constructor threw exception; nested exception is java.lang.ArrayIndexOutOfBoundsException: 1
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:573)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 50 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nodeManager' defined in URL [jar:file:/home/user/tron/java-tron2/deploy/fullnode/FullNode4.1.3.jar!/org/tron/common/overlay/discover/node/NodeManager.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.tron.common.overlay.discover.node.NodeManager]: Constructor threw exception; nested exception is java.lang.ArrayIndexOutOfBoundsException: 1
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:275)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1143)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1192)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1116)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:545)
	... 52 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.tron.common.overlay.discover.node.NodeManager]: Constructor threw exception; nested exception is java.lang.ArrayIndexOutOfBoundsException: 1
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:267)
	... 64 common frames omitted
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at org.tron.common.overlay.discover.node.Node.instanceOf(Node.java:49)
	at org.tron.common.overlay.discover.node.NodeManager.<init>(NodeManager.java:75)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
	... 66 common frames omitted

**Comment by Benson0224** [comment]
Please refer to this comments https://github.com/tronprotocol/java-tron/issues/2988#issuecomment-593100171

Make sure your CPU cores are more than 1, thanks.

**Comment by Benson0224** [comment]
We will close this issue since no update for a long time.
Please feel free to reopen it if you still see the issue. thanks

**Comment by CerberusGR** [comment]
I have found a solution for this issue for everyone who has the same problem.

I used "--es" as parameter and not "-es" as I had read in all docs.

You could close it again. Thanks!

**Comment by Benson0224** [comment]
> I have found a solution for this issue for everyone who has the same problem.
> 
> I used "--es" as parameter and not "-es" as I had read in all docs.
> 
> You could close it again. Thanks!

Thanks for your info, it is really helpful.
