### ISSUE TITLE
Getting INFO [HandshakeHandler] exception caught, /39.106.220.120:18888 {}  java.io.IOException: Connection reset by peer

### ISSUE THREAD

**Issue by shymi80** [tronprotocol/java-tron#374]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
- sudo git clone https://github/com/tronprotocol/java-tron.git
- cd java-tron/
- sudo ./gradlew build
- sudo ./ gradlew run -Pwitness=true

2. What did you expect to see?
No exceptions on the screen.

3. What did you see instead?
A lot of exceptions in the log file (with different IPs in brackets). Example below:
_13:03:40.712 INFO [HandshakeHandler] channel active, /185.25.151.32:18888
13:03:40.712 INFO [MessageQueue] send to peer[/185.101.94.98:18888] retry[0], length:2 data:[P2P_PONG]
13:03:40.712 INFO [MessageQueue] send to peer[/185.101.94.98:18888] retry[1], length:2 data:[P2P_PING]
13:03:40.721 INFO [HandshakeHandler] channel active, /95.213.203.84:18888
13:03:40.722 INFO [TronChannelInitializer] Close channel:Node{ host='80.211.160.51', port=18888, id=28df5e92adb456962bc2efdc70f746ed8e2abb8403ce4f16de0ffebedae181625c469b33e6f21b24a0df78027ca0d4c3
72e065cb3032071633bf74fd4857a749}
13:03:40.734 INFO [MessageQueue] rcv from peer[/185.101.94.98:18888], size:2 data:[P2P_PONG]
13:03:40.763 INFO [HandshakeHandler] exception caught, /95.213.203.84:18888 {} 
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1106)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:343)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:748)
13:03:40.763 INFO [TronChannelInitializer] Close channel:Node{ host='95.213.203.84', port=18888, id=7f32cba79ea3788c712e263c579e6aedd826e15bff23d7add032442b80249e201d14ef5e9aeef016958f68b85c1af67b
9560b8ae4e969c0cce9423a2742b8dff}
13:03:40.890 INFO [HandshakeHandler] channel active, /18.188.111.53:18888
13:03:40.890 INFO [TronChannelInitializer] Close channel:null
13:03:40.890 INFO [MessageQueue] rcv from peer[/47.254.146.147:18888], size:3 data:[Message Type: FETCH_INV_DATA, Message Hash: fb8da7eb5b1b399e7321179dac9e9f65773d7331e1e30554e3911e4325e1ef19]
13:03:40.890 INFO [o.t.c.n.n.NodeImpl] Handle Message: [Message Type: FETCH_INV_DATA, Message Hash: fb8da7eb5b1b399e7321179dac9e9f65773d7331e1e30554e3911e4325e1ef19]
13:03:40.890 INFO [o.t.c.n.n.NodeImpl] on handle fetch block message
13:03:40.890 INFO [HandshakeHandler] channel active, /67.207.92.229:18888
13:03:40.891 INFO [HandshakeHandler] channel active, /47.254.16.55:18888
13:03:40.891 INFO [HandshakeHandler] channel active, /34.218.208.163:18888
13:03:40.952 INFO [HandshakeHandler] channel active, /47.91.246.252:18888
13:03:40.987 INFO [TronChannelInitializer] Close channel:Node{ host='18.188.111.53', port=18888, id=001237decaf925f5c24bd3796ab8107105c9136fc7577a59965d8467f51f82a643bdc2c40611ba40d0f06c8a3a09142c
845a0a8d00c2365c8246e5d88f5e172a}_

**Comment by wubin12** [comment]
This happens when the other peer closes the connection and does not notify you,  it's not a  bug, I will modify the log, Don't print the stack information.

**Comment by sasaxie** [comment]
No equals true

```shell
sudo ./ gradlew run -Pwitness
```
