### ISSUE TITLE
Testnet Error The address() must be 21 bytes

### ISSUE THREAD

**Issue by saopaulozeroum** [tronprotocol/java-tron#4049]
Hi, thanks for reading. 

First I downloaded Fullnode 
https://github.com/tronprotocol/java-tron/releases/download/GreatVoyage-v4.3.0/FullNode.jar

I use this configuration file 
https://github.com/tronprotocol/tron-deployment/blob/master/test_net_config.conf

So I started fullnode using the command 
`java -jar FullNode.jar -c test_net_config.conf`

-----------

The error message appears 

`Exception in thread "main" java.lang.IllegalArgumentException: The address() must be 21 bytes.
        at org.tron.common.args.Account.setAddress(Account.java:53)
        at org.tron.core.config.args.Args.createAccount(Args.java:793)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
        at org.tron.core.config.args.Args.getAccountsFromConfig(Args.java:786)
        at org.tron.core.config.args.Args.setParam(Args.java:362)
        at org.tron.program.FullNode.main(FullNode.java:49)`

**Comment by Benson0224** [comment]
Please get the configuration file of Nile test net from: https://nileex.io/join/getJoinPage 
Please download the backup data from https://nileex.io/join/getJoinPage too(This is a must, Nile testnet does not support sync from 0)

after these 2 are ready, you can start the FullNode.

One more message: Nile testnet might be ahead of the mainnet, pay attention to the SW version on Nile homepage.   https://nileex.io/

**Comment by saopaulozeroum** [comment]
> 
> 
> Please get the configuration file of Nile test net from: https://nileex.io/join/getJoinPage
> Please download the backup data from https://nileex.io/join/getJoinPage too(This is a must, Nile testnet does not support sync from 0)
> 
> after these 2 are ready, you can start the FullNode.
> 
> One more message: Nile testnet might be ahead of the mainnet, pay attention to the SW version on Nile homepage. https://nileex.io/

Thank you very much, it worked.
For now, I just used the configuration, it seems that it synchronized starting from 0.
