### ISSUE TITLE
Build failed under JDK 1.8 on ubuntu 16

### ISSUE THREAD

**Issue by huming0618** [tronprotocol/java-tron#407]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
 `git clone https://github.com/tronprotocol/java-tron.git`
`git checkout develop`
`git pull`
`./gradlew build`

2. What did you expect to see?
build should be successful.

3. What did you see instead?
Build failed on following tasks 
```
org.tron.core.db.ManagerTest > fork FAILED
   java.lang.AssertionError
       at org.junit.Assert.fail(Assert.java:86)
       at org.junit.Assert.assertTrue(Assert.java:41)
       at org.junit.Assert.assertNotNull(Assert.java:712)
       at org.junit.Assert.assertNotNull(Assert.java:722)
       at org.tron.core.db.ManagerTest.fork(ManagerTest.java:221)

org.tron.core.db.ManagerTest > setBlockReference FAILED
   java.lang.AssertionError: expected:<1> but was:<0>
       at org.junit.Assert.fail(Assert.java:88)
       at org.junit.Assert.failNotEquals(Assert.java:834)
       at org.junit.Assert.assertEquals(Assert.java:645)
       at org.junit.Assert.assertEquals(Assert.java:631)
       at org.tron.core.db.ManagerTest.setBlockReference(ManagerTest.java:84)
```
my JDK version 
```
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```

**Comment by Cyphernode** [comment]
Use java 8

**Comment by klinth** [comment]
Hello. Try like this.
```
sudo add-apt-repository ppa:webupd8team/java -y
sudo apt-get update
sudo apt-get install oracle-java8-installer
```
To automatically set up the Java 8 environment variables
`sudo apt-get install oracle-java8-set-default`
Check it
`java -version`

**Comment by taihaofu** [comment]
Close it for now. Please reopen it if you still have problem on this topic.
