### ISSUE TITLE
JavaTron Error Stop

### ISSUE THREAD

**Issue by smxxxw** [tronprotocol/java-tron#4263]
17:23:32.602 INFO  [pool-51-thread-1] [net](Channel.java:135) Send to /47.90.216.78:9888 online-time 8s, type: P2P_DISCONNECT
reason: TIME_OUT
17:23:32.617 WARN  [TronJClientWorker-1] [net](PeerClient.java:58) connect to 43.135.50.192:18888 fail,cause:connection timed out: /43.135.50.192:18888
17:23:32.617 INFO  [TronJClientWorker-1] [net](TronChannelInitializer.java:48) Close channel:null | <null>
17:23:33.720 ERROR [pool-50-thread-1] [DB](SnapshotManager.java:321)  Find fatal error , program will be exited soon org.tron.common.error.TronDBException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.iq80.leveldb.DBException: Corruption: block checksum mismatch
	at org.tron.core.db2.core.SnapshotManager.refresh(SnapshotManager.java:273)
	at org.tron.core.db2.core.SnapshotManager.flush(SnapshotManager.java:313)
	at org.tron.core.db2.core.SnapshotManager.buildSession(SnapshotManager.java:115)
	at org.tron.core.db2.core.SnapshotManager.buildSession(SnapshotManager.java:98)
	at org.tron.core.db.Manager.pushBlock(Manager.java:1099)
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:213)
	at org.tron.core.net.service.SyncService.processSyncBlock(SyncService.java:267)
	at org.tron.core.net.service.SyncService.lambda$handleSyncBlock$8(SyncService.java:255)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.tron.core.net.service.SyncService.handleSyncBlock(SyncService.java:238)
	at org.tron.core.net.service.SyncService.lambda$init$1(SyncService.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.iq80.leveldb.DBException: Corruption: block checksum mismatch
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:528)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:509)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:85)
	at org.tron.core.db2.core.SnapshotManager.refresh(SnapshotManager.java:268)
	... 17 common frames omitted
Caused by: java.lang.RuntimeException: org.iq80.leveldb.DBException: Corruption: block checksum mismatch
	at org.tron.common.storage.leveldb.LevelDbDataSourceImpl.updateByBatch(LevelDbDataSourceImpl.java:421)
	at org.tron.core.db2.common.LevelDB.flush(LevelDB.java:63)
	at org.tron.core.db2.core.SnapshotRoot.merge(SnapshotRoot.java:61)
	at org.tron.core.db2.core.SnapshotManager.refreshOne(SnapshotManager.java:291)
	at org.tron.core.db2.core.SnapshotManager.lambda$refresh$6(SnapshotManager.java:264)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	... 3 common frames omitted
Caused by: org.iq80.leveldb.DBException: Corruption: block checksum mismatch
	at org.fusesource.leveldbjni.internal.JniDB.write(JniDB.java:153)
	at org.tron.common.storage.leveldb.LevelDbDataSourceImpl.updateByBatchInner(LevelDbDataSourceImpl.java:398)
	at org.tron.common.storage.leveldb.LevelDbDataSourceImpl.updateByBatch(LevelDbDataSourceImpl.java:416)
	... 11 common frames omitted
Caused by: org.fusesource.leveldbjni.internal.NativeDB$DBException: Corruption: block checksum mismatch
	at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200)
	at org.fusesource.leveldbjni.internal.NativeDB.write(NativeDB.java:285)
	at org.fusesource.leveldbjni.internal.JniDB.write(JniDB.java:150)
	... 13 common frames omitted
17:23:33.723 INFO  [Thread-6] [app](ApplicationImpl.java:66) ******** start to shutdown ********
17:23:33.723 INFO  [Thread-6] [net](PeerServer.java:77) Closing TCP server...
17:23:33.731 INFO  [PeerServerThread] [net](PeerServer.java:63) TCP listener closed
17:23:34.222 INFO  [pool-38-thread-1] [net](PeerClient.java:70) connect peer 47.74.240.136 18888 5bb02c04211b6163a44c6f94b083e568fec1f0925f50b1c239b90f832b22d962b7368ffc7cd892d6c5146fa88c8870832d8e49d9d22c1687cfd3c61a8183d417
17:23:34.224 WARN  [pool-38-thread-1] [i.n.c.AbstractChannel](Slf4JLogger.java:146) Force-closing a channel whose registration task was not accepted by an event loop: [id: 0xfc3ad5b4]
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:842)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:328)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:321)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:765)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:479)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74)
	at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:86)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:333)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:163)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:119)
	at org.tron.common.overlay.client.PeerClient.connectAsync(PeerClient.java:88)
	at org.tron.common.overlay.client.PeerClient.connectAsync(PeerClient.java:55)
	at org.tron.common.overlay.server.SyncPool.lambda$fillUp$4(SyncPool.java:125)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.tron.common.overlay.server.SyncPool.fillUp(SyncPool.java:124)
	at org.tron.common.overlay.server.SyncPool.lambda$init$0(SyncPool.java:73)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
17:23:34.235 ERROR [pool-38-thread-1] [i.n.u.c.D.rejectedExecution](Slf4JLogger.java:181) Failed to submit a listener notification task. Event loop shut down?
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:842)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:328)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:321)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:765)
	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:768)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:432)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:103)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1148)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:490)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74)
	at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:86)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:333)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:163)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:119)
	at org.tron.common.overlay.client.PeerClient.connectAsync(PeerClient.java:88)
	at org.tron.common.overlay.client.PeerClient.connectAsync(PeerClient.java:55)
	at org.tron.common.overlay.server.SyncPool.lambda$fillUp$4(SyncPool.java:125)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.tron.common.overlay.server.SyncPool.fillUp(SyncPool.java:124)
	at org.tron.common.overlay.server.SyncPool.lambda$init$0(SyncPool.java:73)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
17:23:34.235 ERROR [pool-38-thread-1] [i.n.u.c.D.rejectedExecution](Slf4JLogger.java:181) Failed to submit a listener notification task. Event loop shut down?
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:842)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:328)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:321)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:765)
	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:768)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:432)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:987)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:491)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74)
	at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:86)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:333)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:163)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:119)
	at org.tron.common.overlay.client.PeerClient.connectAsync(PeerClient.java:88)
	at org.tron.common.overlay.client.PeerClient.connectAsync(PeerClient.java:55)
	at org.tron.common.overlay.server.SyncPool.lambda$fillUp$4(SyncPool.java:125)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.tron.common.overlay.server.SyncPool.fillUp(SyncPool.java:124)
	at org.tron.common.overlay.server.SyncPool.lambda$init$0(SyncPool.java:73)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
17:23:34.235 ERROR [pool-38-thread-1] [i.n.u.c.D.rejectedExecution](Slf4JLogger.java:181) Failed to submit a listener notification task. Event loop shut down?
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:842)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:328)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:321)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:765)
	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:768)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:432)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:162)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
	at org.tron.common.overlay.client.PeerClient.connectAsync(PeerClient.java:56)
	at org.tron.common.overlay.server.SyncPool.lambda$fillUp$4(SyncPool.java:125)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.tron.common.overlay.server.SyncPool.fillUp(SyncPool.java:124)
	at org.tron.common.overlay.server.SyncPool.lambda$init$0(SyncPool.java:73)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
17:23:34.235 INFO  [pool-38-thread-1] [net](PeerClient.java:70) connect peer 47.74.226.54 18888 2fc3e4d6d8364b55f71f45b001e510f9b4373bfe8d9597670f1ab71d4e98e68a158241a346ca57c844e26238b44e5e5bedb9ab13c3129fb6c3a3a110eb63df3b
17:23:34.236 WARN  [pool-38-thread-1] [i.n.c.AbstractChannel](Slf4JLogger.java:146) Force-closing a channel whose registration task was not accepted by an event loop: [id: 0xebf6ebe3]
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:842)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:328)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:321)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:765)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:479)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74)
	at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:86)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:333)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:163)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:119)
	at org.tron.common.overlay.client.PeerClient.connectAsync(PeerClient.java:88)
	at org.tron.common.overlay.client.PeerClient.connectAsync(PeerClient.java:55)
	at org.tron.common.overlay.server.SyncPool.lambda$fillUp$4(SyncPool.java:125)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.tron.common.overlay.server.SyncPool.fillUp(SyncPool.java:124)
	at org.tron.common.overlay.server.SyncPool.lambda$init$0(SyncPool.java:73)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
17:23:34.236 ERROR [pool-38-thread-1] [i.n.u.c.D.rejectedExecution](Slf4JLogger.java:181) Failed to submit a listener notification task. Event loop shut down?
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:842)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:328)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:321)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:765)
	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:768)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:432)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:103)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1148)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:490)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80)

**Comment by vivian-kang** [comment]
"org.iq80.leveldb.DBException: Corruption: block checksum mismatch" is a db level error, but not java-tron error.
It happens if the CRC written with a block of data doesn't match the data, on read. So either it didn't get written properly, or it was randomly overwritten later. 
So please check your system: hard disk, drivers, overheating CPU/GPUs, and so on.
Thanks.

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
