### ISSUE TITLE
[Bounty] Disconnect throws null pointer exception

### ISSUE THREAD

**Issue by bloc4ain** [tronprotocol/java-tron#446]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
I started full node using latest git commit(62c8d6bf703a4e042c98d268b6570c8f252f8f2c)

2. What did you expect to see?
I did not expect to see null pointer exception

3. What did you see instead?
```
14:36:03.456 INFO [o.t.c.n.n.NodeImpl] disconnect with 47.91.246.252|| reason:USER_REASON
14:36:03.456 INFO [Channel] Channel disconnect /47.91.246.252:18888, reason:USER_REASON
14:36:03.456 ERROR [o.t.c.n.n.NodeImpl] Unhandled exception
java.lang.NullPointerException: null
        at org.tron.common.overlay.server.MessageQueue.disconnect(MessageQueue.java:129)
        at org.tron.common.overlay.server.MessageQueue.disconnect(MessageQueue.java:125)
        at org.tron.common.overlay.server.Channel.disconnect(Channel.java:212)
        at org.tron.core.net.node.NodeImpl.disconnectPeer(NodeImpl.java:1074)
        at org.tron.core.net.node.NodeImpl.lambda$disconnectInactive$28(NodeImpl.java:537)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.tron.core.net.node.NodeImpl.disconnectInactive(NodeImpl.java:512)
        at org.tron.core.net.node.NodeImpl.lambda$activeTronPump$16(NodeImpl.java:391)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
I restarted the process and i am unable to reproduce the problem.  [Here are more logs](https://pastebin.com/06mknQWr)

**Comment by bloc4ain** [comment]
Update: i looked at the console after 30 mins and the error appears again.

**Comment by lvs007** [comment]
@bloc4ain Does it happen every time?I start full node but don't happen
