### ISSUE TITLE
Node sync not happening at all

### ISSUE THREAD

**Issue by White2001Offl** [tronprotocol/java-tron#4472]
### 1. What did you do?
I started the node like `java -jar FullNode.jar -c main_net_config.conf` 
I used the config from the official docs
Then I see the node sync was not happening at all for an hour
So I searched and lookup the issues and found one it said to change ip.list to node.active
then I changed the ip.list to node.active list
but I see those nodes are not working at all

like all are connection refused

```
16:59:25.732 INFO  [TronJClientWorker-14] [net](TronChannelInitializer.java:48) Close channel:/54.252.224.209:18888 | 99ff892e7d001096b48580fa843090bd5e8fcdd69f4b8e54475550c0fd25a6be22a89c41a99a2c4942462009765d600f8c3b57a6b65d3f48f57c72e36165e3f5
16:59:26.579 WARN  [TronJClientWorker-19] [net](PeerClient.java:58) connect to 34.250.140.143:18888 fail,cause:Connection refused: /34.250.140.143:18888
16:59:26.579 INFO  [TronJClientWorker-19] [net](TronChannelInitializer.java:48) Close channel:null | <null>
16:59:26.845 WARN  [TronJClientWorker-0] [net](PeerClient.java:58) connect to 35.154.90.144:18888 fail,cause:Connection refused: /35.154.90.144:18888
16:59:26.845 INFO  [TronJClientWorker-0] [net](TronChannelInitializer.java:48) Close channel:null | <null>
16:59:27.419 WARN  [TronJClientWorker-58] [net](PeerClient.java:58) connect to 35.182.37.246:18888 fail,cause:connection timed out: /35.182.37.246:18888
16:59:27.419 INFO  [TronJClientWorker-58] [net](TronChannelInitializer.java:48) Close channel:null | <null>
16:59:27.420 WARN  [TronJClientWorker-59] [net](PeerClient.java:58) connect to 13.57.30.186:18888 fail,cause:connection timed out: /13.57.30.186:18888
16:59:27.420 INFO  [TronJClientWorker-59] [net](TronChannelInitializer.java:48) Close channel:null | <null>
16:59:27.422 WARN  [TronJClientWorker-62] [net](PeerClient.java:58) connect to 35.183.101.48:18888 fail,cause:connection timed out: /35.183.101.48:18888
16:59:27.422 INFO  [TronJClientWorker-62] [net](TronChannelInitializer.java:48) Close channel:null | <null>
16:59:27.424 WARN  [TronJClientWorker-63] [net](PeerClient.java:58) connect to 13.229.128.108:18888 fail,cause:connection timed out: /13.229.128.108:18888
16:59:27.424 INFO  [TronJClientWorker-63] [net](TronChannelInitializer.java:48) Close channel:null | <null>
16:59:27.424 WARN  [TronJClientWorker-2] [net](PeerClient.java:58) connect to 35.165.103.105:18888 fail,cause:connection timed out: /35.165.103.105:18888
16:59:27.424 INFO  [TronJClientWorker-2] [net](TronChannelInitializer.java:48) Close channel:null | <null>
16:59:27.425 WARN  [TronJClientWorker-4] [net](PeerClient.java:58) connect to 52.47.197.188:18888 fail,cause:connection timed out: /52.47.197.188:18888
16:59:27.425 INFO  [TronJClientWorker-4] [net](TronChannelInitializer.java:48) Close channel:null | <null>
16:59:27.427 WARN  [TronJClientWorker-6] [net](PeerClient.java:58) connect to 13.231.4.243:18888 fail,cause:connection timed out: /13.231.4.243:18888
16:59:27.427 INFO  [TronJClientWorker-6] [net](TronChannelInitializer.java:48) Close channel:null | <null>
16:59:27.428 WARN  [TronJClientWorker-7] [net](PeerClient.java:58) connect to 18.220.232.201:18888 fail,cause:connection timed out: /18.220.232.201:18888
16:59:27.428 INFO  [TronJClientWorker-7] [net](TronChannelInitializer.java:48) Close channel:null | <null>
16:59:27.429 WARN  [TronJClientWorker-10] [net](PeerClient.java:58) connect to 13.125.210.234:18888 fail,cause:connection timed out: /13.125.210.234:18888
16:59:27.429 INFO  [TronJClientWorker-10] [net](TronChannelInitializer.java:48) Close channel:null | <null>
16:59:27.429 WARN  [TronJClientWorker-11] [net](PeerClient.java:58) connect to 52.62.210.100:18888 fail,cause:connection timed out: /52.62.210.100:18888
16:59:27.429 INFO  [TronJClientWorker-11] [net](TronChannelInitializer.java:48) Close channel:null | <null>
16:59:27.430 WARN  [TronJClientWorker-15] [net](PeerClient.java:58) connect to 18.184.238.21:18888 fail,cause:connection timed out: /18.184.238.21:18888
16:59:27.430 INFO  [TronJClientWorker-15] [net](TronChannelInitializer.java:48) Close channel:null | <null>
16:59:27.431 WARN  [TronJClientWorker-17] [net](PeerClient.java:58) connect to 34.200.228.125:18888 fail,cause:connection timed out: /34.200.228.125:18888
16:59:27.431 WARN  [TronJClientWorker-16] [net](PeerClient.java:58) connect to 35.176.192.130:18888 fail,cause:connection timed out: /35.176.192.130:18888
16:59:27.431 INFO  [TronJClientWorker-17] [net](TronChannelInitializer.java:48) Close channel:null | <null>
16:59:27.431 INFO  [TronJClientWorker-16] [net](TronChannelInitializer.java:48) Close channel:null | <null>
16:59:27.433 WARN  [TronJClientWorker-13] [net](PeerClient.java:58) connect to 13.250.40.82:18888 fail,cause:connection timed out: /13.250.40.82:18888
16:59:27.433 INFO  [TronJClientWorker-13] [net](TronChannelInitializer.java:48) Close channel:null | <null>
16:59:27.433 WARN  [TronJClientWorker-21] [net](PeerClient.java:58) connect to 18.231.76.29:18888 fail,cause:connection timed out: /18.231.76.29:18888
16:59:27.433 INFO  [TronJClientWorker-21] [net](TronChannelInitializer.java:48) Close channel:null | <null>
```

I use WSL. I exposed the ports 8090, 8091, 18888, 50051
does it uses any other ports for connecting and node discovery??

### 2. What did you expect to see?
I expect to sync the node without any issue

### 3. What did you see instead?
I see the nodes getting connection refused that makes my node to not sync.

**Comment by White2001Offl** [comment]
[tron.log](https://github.com/tronprotocol/java-tron/files/8951131/tron.log)

My Log File

**Comment by wubin01** [comment]
Is it possible that you only exposed the UDP port, but not the TCP port ?

The exception reported in the log file should be caused by a problem with the configuration file format.

**Comment by White2001Offl** [comment]
> Is it possible that you only exposed the UDP port, but not the TCP port ?
> 
> The exception reported in the log file should be caused by a problem with the configuration file format.

I exposed 18888 for both tcp and udp
rest are tcp.

and the config file I used from the official docs
let me attach that too


[main_net_config.conf](https://github.com/tronprotocol/java-tron/files/8954310/main_net_config.txt)

**Comment by wubin01** [comment]
This configuration file is OK for me to start locally. Maybe there is a problem with your local configuration file? Try it with this configuration file you provided?

**Comment by White2001Offl** [comment]
> This configuration file is OK for me to start locally. Maybe there is a problem with your local configuration file? Try it with this configuration file you provided?

The about file is the one I use and that is my local config file.

**Comment by White2001Offl** [comment]
> Is the above log file generated by starting the node with this configuration file?
> Or you can use this configuration file to start the node, and then show me the log.

Yes the log you see is with the config file I provided

**Comment by wubin01** [comment]
Delete the database and try again (or change the database file name [output-directory -> output-directory-bak]), and then show me the log?

**Comment by White2001Offl** [comment]
[tron.log](https://github.com/tronprotocol/java-tron/files/8955233/tron.log)

Deleted the Database folder in output-directory
and started again
the above is the new log

**Comment by White2001Offl** [comment]
> try to use this FullNode.jar to start ？ `wget https://github.com/tronprotocol/java-tron/releases/download/GreatVoyage-v4.5.1/FullNode.jar`

still same
btw i started like this `java -jar FullNode.jar -c main_net_config.conf`

**Comment by wubin01** [comment]
use `java -jar FullNode.jar` ?

**Comment by White2001Offl** [comment]
> use `java -jar FullNode.jar` ?

Still same :( idk whats wrong

**Comment by White2001Offl** [comment]
@wubin01 what can be the issue?

**Comment by wubin01** [comment]
Start with this command `java -jar FullNode.jar`, and then show me the log, thanks.

**Comment by White2001Offl** [comment]
[tron.log](https://github.com/tronprotocol/java-tron/files/8957291/tron.log)

here is the new log file

**Comment by White2001Offl** [comment]
lmk what I should do guys? I need this fixed. Thanks

**Comment by forfreeday** [comment]
The recommended environments are centos or mac, which you can use to run

**Comment by forfreeday** [comment]
What specific environment are you using, e.g. JDK version, WSL version, be as specific as possible

**Comment by White2001Offl** [comment]
> The recommended environments are centos or mac, which you can use to run

I'll try to install centos and see if that works or not

**Comment by White2001Offl** [comment]
> What specific environment are you using, e.g. JDK version, WSL version, be as specific as possible

```
WSL 1
openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1)
OpenJDK 64-Bit Server VM (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1, mixed mode)
```

anymore info need? @forfreeday

**Comment by White2001Offl** [comment]
as @ethan1844 said
I updated to Oracle JDK18

but I get new error now

```
Exception in thread "main" java.lang.IllegalStateException: Cannot load configuration class: org.tron.core.config.DefaultConfig
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(ConfigurationClassPostProcessor.java:410)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanFactory(ConfigurationClassPostProcessor.java:263)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:284)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:130)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:678)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:520)
        at org.tron.program.FullNode.main(FullNode.java:80)
Caused by: java.lang.ExceptionInInitializerError
        at org.springframework.cglib.core.KeyFactory$Generator.getProtectionDomain(KeyFactory.java:136)
        at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:206)
        at org.springframework.cglib.core.KeyFactory$Generator.create(KeyFactory.java:149)
        at org.springframework.cglib.core.KeyFactory.create(KeyFactory.java:117)
        at org.springframework.cglib.core.KeyFactory.create(KeyFactory.java:109)
        at org.springframework.cglib.core.KeyFactory.create(KeyFactory.java:105)
        at org.springframework.cglib.proxy.Enhancer.<clinit>(Enhancer.java:71)
        at org.springframework.context.annotation.ConfigurationClassEnhancer.newEnhancer(ConfigurationClassEnhancer.java:119)
        at org.springframework.context.annotation.ConfigurationClassEnhancer.enhance(ConfigurationClassEnhancer.java:107)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(ConfigurationClassPostProcessor.java:400)
        ... 6 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @774bd0a2
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:200)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:194)
        at org.springframework.cglib.core.ReflectUtils$1.run(ReflectUtils.java:52)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at org.springframework.cglib.core.ReflectUtils.<clinit>(ReflectUtils.java:42)
        ... 16 more
  
  ```
  
  
  I tried with config and without config file same error
  My env is
  
  ```
  java version "18.0.1.1" 2022-04-22
Java(TM) SE Runtime Environment (build 18.0.1.1+2-6)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing)
```

**Comment by halibobo1205** [comment]
Not Oracle JDK18, use Oracle JDK1.8,  for example,`Oracle Corporation, Java(TM) SE Runtime Environment, 1.8.0_202-b08`.

**Comment by White2001Offl** [comment]
omg yes finally its working thanks. @halibobo1205 
I thought 1.8 as 18
