### ISSUE TITLE
stuck after catchup

### ISSUE THREAD

**Issue by ciuyuc** [tronprotocol/java-tron#4490]
### 1. What did you do?

While the initial catchup was quick after downloading the blockchain, the live catchup often gets stuck after the node has the newest block. It is eventually able to fully catch up but then pauses and falls behind again (difference of ~30 blocks). It then takes another 10-30 seconds for the newest block to be received.

startup script:
```
#!/bin/bash

export LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libtcmalloc.so.4"
export TCMALLOC_RELEASE_RATE=10

exec java -Xmx32g -XX:+UseConcMarkSweepGC \
	-jar ~/java-tron/build/libs/FullNode.jar \
	-c ~/main_net_config.conf \
	-d /storage/trx/output-directory
```

I use standard main_net_config which is available for the mainnet setup.

AMD EPYC 7402P 24 Cores @ 2.8 GHz 
RTX3070 GPU
256 GB RAM
OS SSD 2 TB SSD NVME 
data directory (/storage) is a RAID-0 array with 9x 2 TB SSD NVME

Kindly let me know if I forgot something.

### 2. What did you expect to see?
A permanent synchronization with the blockchain.

### 3. What did you see instead?
In addition to the permanent lag behind the blockchain, the journal registered some errors after a run of several hours:

```
root@live:~# journalctl -u tron
Jun 29 13:19:59 live-hagfish systemd[1]: Started TRON node.
Jun 29 16:07:07 live-hagfish tron.sh[3831196]: Jun 29, 2022 4:07:07 PM io.grpc.netty.NettyServerHandler onStreamError
Jun 29 16:07:07 live-hagfish tron.sh[3831196]: WARNING: Stream Error
Jun 29 16:07:07 live-hagfish tron.sh[3831196]: io.netty.handler.codec.http2.Http2Exception$StreamException: Stream closed before write could take place
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:149)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$FlowState.cancel(DefaultHttp2RemoteFlowController.java:4>
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$1.onStreamClosed(DefaultHttp2RemoteFlowController.java:1>
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.http2.DefaultHttp2Connection.notifyClosed(DefaultHttp2Connection.java:356)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.removeFromActiveStreams(DefaultHttp2Connection.java:>
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.deactivate(DefaultHttp2Connection.java:956)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultStream.close(DefaultHttp2Connection.java:512)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultStream.close(DefaultHttp2Connection.java:518)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.http2.Http2ConnectionHandler.closeStream(Http2ConnectionHandler.java:589)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onRstStreamRead(DefaultHttp2ConnectionDec>
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onRstStreamRead(Http2InboundFrameLogger.java:80)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readRstStreamFrame(DefaultHttp2FrameReader.java:516)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:260)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:118)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:390)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:450)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at java.lang.Thread.run(Thread.java:750)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]: Jun 29, 2022 4:07:07 PM io.grpc.netty.NettyServerHandler onStreamError
Jun 29 16:07:07 live-hagfish tron.sh[3831196]: WARNING: Stream Error
Jun 29 16:07:07 live-hagfish tron.sh[3831196]: io.netty.handler.codec.http2.Http2Exception$StreamException: Stream closed before write could take place
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:149)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$FlowState.cancel(DefaultHttp2RemoteFlowController.java:4>
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$1.onStreamClosed(DefaultHttp2RemoteFlowController.java:1>
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.http2.DefaultHttp2Connection.notifyClosed(DefaultHttp2Connection.java:356)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.removeFromActiveStreams(DefaultHttp2Connection.java:>
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.deactivate(DefaultHttp2Connection.java:956)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultStream.close(DefaultHttp2Connection.java:512)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultStream.close(DefaultHttp2Connection.java:518)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.http2.Http2ConnectionHandler.closeStream(Http2ConnectionHandler.java:589)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onRstStreamRead(DefaultHttp2ConnectionDec>
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onRstStreamRead(Http2InboundFrameLogger.java:80)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readRstStreamFrame(DefaultHttp2FrameReader.java:516)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:260)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:118)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:390)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:450)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
Jun 29 16:07:07 live-hagfish tron.sh[3831196]:         at java.lang.Thread.run(Thread.java:750)

```

**Comment by joker-gdb** [comment]
`tail -f output-directory/log/tron.log` to check the log, are there any error logs?

**Comment by ciuyuc** [comment]
> `tail -f output-directory/log/tron.log` to check the log, are there any error logs?

Pfa. output log for block section 42035884 to 42035926.

sync from 42035884 to 42035907, then stuck
sync from 42035907 to 42035917, then stuck
sync from 42035917 to 42035926, then stuck


[output.log](https://github.com/tronprotocol/java-tron/files/9028724/output.log)

**Comment by supportteam9** [comment]
Check out the Live support team if you haven't gotten a solution to your issue yet   https://direct.lc.chat/14269734/

**Comment by ciuyuc** [comment]
Not sure what happend, but since synchronizing System clock my node is also synchronized with the TRON network now.
May or may not related with, but at least the issue seems fixed for now.

```
root@live:~# timedatectl
               Local time: Tue 2022-07-05 16:06:17 EEST
           Universal time: Tue 2022-07-05 13:06:17 UTC
                 RTC time: Tue 2022-07-05 13:06:17
                Time zone: Europe/Vilnius (EEST, +0300)
**System clock synchronized: yes**
              NTP service: active
          RTC in local TZ: no

```
