### ISSUE TITLE
private chain supernode start failure

### ISSUE THREAD

**Issue by andy-github-info** [tronprotocol/java-tron#4517]
Build a private chain and start the super node error.
jdk：1.8.0_181
java-tron：GreatVoyage-v4.5.1(Tertullian)

Command
`
java -Xmx32g -XX:+UseConcMarkSweepGC -jar FullNode.jar  --witness  -c supernode.conf &
`

Error:
`
17:22:17.831 INFO  [main] [DB](LevelDbDataSourceImpl.java:136) DB transactionRetStore open success with : writeBufferSize 256M,cacheSize 32M,maxOpenFiles 100.
17:22:17.838 INFO  [main] [DB](LevelDbDataSourceImpl.java:136) DB recent-block open success with : writeBufferSize 16M,cacheSize 32M,maxOpenFiles 100.
17:22:17.844 INFO  [main] [DB](LevelDbDataSourceImpl.java:136) DB recent-transaction open success with : writeBufferSize 16M,cacheSize 32M,maxOpenFiles 100.
17:22:17.847 INFO  [main] [DB](LevelDbDataSourceImpl.java:136) DB transactionHistoryStore open success with : writeBufferSize 16M,cacheSize 32M,maxOpenFiles 100.
17:22:17.851 INFO  [main] [DB](LevelDbDataSourceImpl.java:136) DB common-database open success with : writeBufferSize 16M,cacheSize 32M,maxOpenFiles 100.
17:22:17.855 INFO  [main] [DB](LevelDbDataSourceImpl.java:136) DB pbft-sign-data open success with : writeBufferSize 16M,cacheSize 32M,maxOpenFiles 100.
17:22:17.860 INFO  [main] [DB](LevelDbDataSourceImpl.java:136) DB tree-block-index open success with : writeBufferSize 16M,cacheSize 32M,maxOpenFiles 100.
17:22:17.864 INFO  [main] [DB](LevelDbDataSourceImpl.java:136) DB section-bloom open success with : writeBufferSize 16M,cacheSize 32M,maxOpenFiles 100.
17:22:17.916 WARN  [main] [o.s.b.f.a.AutowiredAnnotationBeanPostProcessor](AutowiredAnnotationBeanPostProcessor.java:398) Autowired annotation is not supported on static fields: private static final java.util.concurrent.ConcurrentHashMap org.tron.core.config.args.Args.solidityContractLogTriggerMap
17:22:17.916 WARN  [main] [o.s.b.f.a.AutowiredAnnotationBeanPostProcessor](AutowiredAnnotationBeanPostProcessor.java:398) Autowired annotation is not supported on static fields: private static final java.util.concurrent.ConcurrentHashMap org.tron.core.config.args.Args.solidityContractEventTriggerMap
17:22:18.039 INFO  [main] [discover](NodeManager.java:81) homeNode : Node{ host='127.0.0.1', port=16666, id=d9acd10ed95c240c2fbcfa7ff39c36c2d8874ef09aa0089d3dd830d053eec7e56c5a8154ff8ef70a3fa09c4ca51ef46f265fc2869994121d904fd586cbe23dc1}
17:22:18.069 INFO  [main] [DB](LevelDbDataSourceImpl.java:136) DB trans-cache open success with : writeBufferSize 16M,cacheSize 32M,maxOpenFiles 100.
17:22:18.075 INFO  [main] [DB](TxCacheDB.java:96) Transaction cache init-1 db-size:0, blockNumMap-size:0, cost:0ms
17:22:18.149 INFO  [main] [DB](Manager.java:551) create genesis block
17:22:18.150 INFO  [main] [DB](Manager.java:557) save block: BlockCapsule 
[ hash=00000000000000006445151b79fab0bce3e95eac4523d3295189e3b7ce8802a4
number=0
parentId=957dc2d350daecc7bb6a38f3938ebde0a0c1cedafe15f0edae4256a2907449f6
witness address=41206e65772073797374656d206d75737420616c6c6f77206578697374696e672073797374656d7320746f206265206c696e6b656420746f67657468657220776974686f757420726571756972696e6720616e792063656e7472616c20636f6e74726f6c206f7220636f6f7264696e6174696f6e
generated by myself=true
generate time=1970-01-01 08:00:00.0
account root=0000000000000000000000000000000000000000000000000000000000000000
merkle root=53ec1d4e43e016e135471d596b6b584a4fc8719d6d5949c7007c1e362cac4b70
txs size=1
]
17:22:18.150 INFO  [main] [DB](DynamicPropertiesStore.java:2053) update latest block header number = 0
17:22:18.150 INFO  [main] [DB](DynamicPropertiesStore.java:2061) update latest block header id = 00000000000000006445151b79fab0bce3e95eac4523d3295189e3b7ce8802a4
17:22:18.151 INFO  [main] [DB](DynamicPropertiesStore.java:2045) update latest block header timestamp = 0
17:22:18.203 INFO  [main] [DB](AssetUpdateHelper.java:36) Start to update the asset
17:22:18.205 INFO  [main] [DB](LevelDbDataSourceImpl.java:136) DB asset-issue-v2 open success with : writeBufferSize 16M,cacheSize 32M,maxOpenFiles 100.
17:22:18.206 INFO  [main] [DB](LevelDbDataSourceImpl.java:136) DB asset-issue-v2 open success with : writeBufferSize 16M,cacheSize 32M,maxOpenFiles 100.
17:22:18.208 INFO  [main] [DB](LevelDbDataSourceImpl.java:136) DB exchange-v2 open success with : writeBufferSize 16M,cacheSize 32M,maxOpenFiles 100.
17:22:18.209 INFO  [main] [DB](LevelDbDataSourceImpl.java:136) DB exchange-v2 open success with : writeBufferSize 16M,cacheSize 32M,maxOpenFiles 100.
17:22:18.209 INFO  [main] [DB](AssetUpdateHelper.java:95) Total block:1
17:22:18.210 INFO  [main] [DB](AssetUpdateHelper.java:124) Complete the asset store update, Total assets:0
17:22:18.211 INFO  [main] [DB](AssetUpdateHelper.java:145) Complete the exchange store update, Total exchanges:0
17:22:18.213 INFO  [main] [DB](AssetUpdateHelper.java:194) The number of accounts that have completed the update: 0
17:22:18.213 INFO  [main] [DB](AssetUpdateHelper.java:199) Complete the account store update, total assets: 1
17:22:18.213 INFO  [main] [DB](AssetUpdateHelper.java:42) Complete the asset update, Total time:10 milliseconds
17:22:18.213 INFO  [main] [DB](MoveAbiHelper.java:25) Start to move abi
17:22:18.214 INFO  [main] [DB](MoveAbiHelper.java:42) Complete the abi move, total time: 1 milliseconds, total count: 0
17:22:18.214 INFO  [main] [DB](EnergyPriceHistoryLoader.java:25) Start to load energy price
17:22:18.216 INFO  [main] [DB](EnergyPriceHistoryLoader.java:34) Complete energy price load, total time: 2 milliseconds, total proposal count: 0
17:22:18.218 WARN  [main] [o.t.c.a.TronApplicationContext](AbstractApplicationContext.java:546) Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'applicationImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.net.TronNetService org.tron.common.application.ApplicationImpl.tronNetService; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tronNetService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.net.service.AdvService org.tron.core.net.TronNetService.advService; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'advService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.net.TronNetDelegate org.tron.core.net.service.AdvService.tronNetDelegate; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tronNetDelegate': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.db.Manager org.tron.core.net.TronNetDelegate.dbManager; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'manager': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: The key argument cannot be null
******** begin to pop revokingDb ********
******** before revokingDb size:0
******** end to pop revokingDb ********
17:22:18.226 ERROR [main] [app](DefaultConfig.java:43) Uncaught exception
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'applicationImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.net.TronNetService org.tron.common.application.ApplicationImpl.tronNetService; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tronNetService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.net.service.AdvService org.tron.core.net.TronNetService.advService; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'advService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.net.TronNetDelegate org.tron.core.net.service.AdvService.tronNetDelegate; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tronNetDelegate': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.db.Manager org.tron.core.net.TronNetDelegate.dbManager; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'manager': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: The key argument cannot be null
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
	at org.tron.program.FullNode.main(FullNode.java:80)
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.net.TronNetService org.tron.common.application.ApplicationImpl.tronNetService; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tronNetService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.net.service.AdvService org.tron.core.net.TronNetService.advService; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'advService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.net.TronNetDelegate org.tron.core.net.service.AdvService.tronNetDelegate; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tronNetDelegate': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.db.Manager org.tron.core.net.TronNetDelegate.dbManager; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'manager': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: The key argument cannot be null
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:573)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 11 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tronNetService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.net.service.AdvService org.tron.core.net.TronNetService.advService; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'advService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.net.TronNetDelegate org.tron.core.net.service.AdvService.tronNetDelegate; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tronNetDelegate': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.db.Manager org.tron.core.net.TronNetDelegate.dbManager; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'manager': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: The key argument cannot be null
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1192)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1116)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:545)
	... 13 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.net.service.AdvService org.tron.core.net.TronNetService.advService; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'advService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.net.TronNetDelegate org.tron.core.net.service.AdvService.tronNetDelegate; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tronNetDelegate': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.db.Manager org.tron.core.net.TronNetDelegate.dbManager; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'manager': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: The key argument cannot be null
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:573)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 24 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'advService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.net.TronNetDelegate org.tron.core.net.service.AdvService.tronNetDelegate; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tronNetDelegate': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.db.Manager org.tron.core.net.TronNetDelegate.dbManager; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'manager': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: The key argument cannot be null
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1192)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1116)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:545)
	... 26 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.net.TronNetDelegate org.tron.core.net.service.AdvService.tronNetDelegate; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tronNetDelegate': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.db.Manager org.tron.core.net.TronNetDelegate.dbManager; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'manager': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: The key argument cannot be null
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:573)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 37 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tronNetDelegate': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.db.Manager org.tron.core.net.TronNetDelegate.dbManager; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'manager': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: The key argument cannot be null
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1192)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1116)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:545)
	... 39 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.db.Manager org.tron.core.net.TronNetDelegate.dbManager; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'manager': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: The key argument cannot be null
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:573)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 50 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'manager': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: The key argument cannot be null
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1192)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1116)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:545)
	... 52 common frames omitted
Caused by: java.lang.IllegalArgumentException: The key argument cannot be null
	at org.fusesource.leveldbjni.internal.NativeDB.checkArgNotNull(NativeDB.java:209)
	at org.fusesource.leveldbjni.internal.NativeDB.get(NativeDB.java:290)
	at org.fusesource.leveldbjni.internal.JniDB.get(JniDB.java:85)
	at org.fusesource.leveldbjni.internal.JniDB.get(JniDB.java:77)
	at org.tron.common.storage.leveldb.LevelDbDataSourceImpl.getData(LevelDbDataSourceImpl.java:213)
	at org.tron.core.db2.common.LevelDB.get(LevelDB.java:25)
	at org.tron.core.db2.common.LevelDB.get(LevelDB.java:12)
	at org.tron.core.db2.core.SnapshotRoot.get(SnapshotRoot.java:40)
	at org.tron.core.db2.core.Chainbase.getUnchecked(Chainbase.java:153)
	at org.tron.core.db.TronStoreWithRevoking.getUnchecked(TronStoreWithRevoking.java:151)
	at org.tron.core.store.AccountStore.getBlackhole(AccountStore.java:112)
	at org.tron.core.db.Manager.resetBlackholeAccountPermission(Manager.java:331)
	at org.tron.core.db.Manager.init(Manager.java:484)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:354)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:305)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
	... 64 common frames omitted
`

**Comment by joker-gdb** [comment]
Minimum requirement: CPU: 16 cores, similar to this：https://github.com/tronprotocol/java-tron/issues/2988

**Comment by andy-github-info** [comment]
This is committee. allowCreationOfContracts is set to 1 lead to mistakes. It needs to be set to 0
