### ISSUE TITLE
run private chain on mac(m2) with errors

### ISSUE THREAD

**Issue by sampleblood** [tronprotocol/java-tron#4548]
### System information
```
java-tron: 
4.5.1
GreatVoyage-v4.4.6-257-ge06abd15c
16944
```
OS ：macOS Monterey version 12.4 , Apple M2

### 1. What did you do?
I try to build a private chain on my mac according to: https://developers.tron.network/docs/tron-private-chain, run  java -Xmx6g -XX:+HeapDumpOnOutOfMemoryError -jar FullNode.jar  --witness  -c supernode.conf  with this error:
```
Exception in thread "main" java.lang.IllegalStateException: Cannot load configuration class: org.tron.core.config.DefaultConfig
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(ConfigurationClassPostProcessor.java:410)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanFactory(ConfigurationClassPostProcessor.java:263)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:284)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:130)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:678)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:520)
	at org.tron.program.FullNode.main(FullNode.java:80)
Caused by: java.lang.UnsatisfiedLinkError: /private/var/folders/zb/rpskkgz1115cdkfy1rzbq_6h0000gn/T/librocksdbjni754936025482462603.jnilib: dlopen(/private/var/folders/zb/rpskkgz1115cdkfy1rzbq_6h0000gn/T/librocksdbjni754936025482462603.jnilib, 0x0001): tried: '/private/var/folders/zb/rpskkgz1115cdkfy1rzbq_6h0000gn/T/librocksdbjni754936025482462603.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1950)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1832)
	at java.lang.Runtime.load0(Runtime.java:811)
	at java.lang.System.load(System.java:1088)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
	at org.tron.core.config.DefaultConfig.<clinit>(DefaultConfig.java:32)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:397)
	at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:237)
	at org.springframework.cglib.proxy.Enhancer.createHelper(Enhancer.java:378)
	at org.springframework.cglib.proxy.Enhancer.createClass(Enhancer.java:318)
	at org.springframework.context.annotation.ConfigurationClassEnhancer.createClass(ConfigurationClassEnhancer.java:135)
	at org.springframework.context.annotation.ConfigurationClassEnhancer.enhance(ConfigurationClassEnhancer.java:107)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(ConfigurationClassPostProcessor.java:400)
```
Is there something wrong or M2 not supported?

**Comment by halibobo1205** [comment]
Need  `jdk1.8 for x86_64` ,arm is not supported for now.

**Comment by brucewang997** [comment]
> Need `jdk1.8 for x86_64` ,arm is not supported for now.

Is there a plan to support  or  timeline?

**Comment by halibobo1205** [comment]
> > Need `jdk1.8 for x86_64` ,arm is not supported for now.
> 
> Is there a plan to support or timeline?

You can install `jdk1.8 for x86_64` for mac_arm.

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
