### ISSUE TITLE
Bad MAX_FEE_LIMIT parameter value

### ISSUE THREAD

**Issue by ahaii** [tronprotocol/java-tron#4830]
### System information
ubuntu18.04

OS : Linux
JVM : Oracle Corporation 1.8.0_211 amd64
Git : 1404ec33cf4ca94e7a2f420b4d22751e5a38e3cc
Version : 4.6.0
Code : 17198

### 1. What did you do?

block can't sync，the err log：

Peer 212.32.249.175:18888 [155ddecf]
ping msg: count 50, max-average-min-last: 2935 311 254 259
connect time: 1003s
last know block num: 39543130
needSyncFromPeer:false
needSyncFromUs:true
syncToFetchSize:0
syncToFetchSizePeekNum:-1
syncBlockRequestedSize:0
remainNum:6885089
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 185(0), discover: 1/1 1/1 0/0 0/0 250ms, p2p: 2/2/5 , tron: 116/599 X 4 =>TOO_MANY_PEERS, tcp flow: 18790
top99 : 0.000000, top95 : 0.000000, top75 : 0.000000, max : 0, min : 0, mean : 0.000000, median : 0.000000

Peer 45.66.150.130:18888 [28bade54]
ping msg: count 38, max-average-min-last: 4421 336 100 104
connect time: 740s
last know block num: 91107
needSyncFromPeer:false
needSyncFromUs:true
syncToFetchSize:0
syncToFetchSizePeekNum:-1
syncBlockRequestedSize:0
remainNum:46337112
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 178(0), discover: 1/1 1/1 0/0 0/0 125ms, p2p: 7/7/8 , tron: 1960/5298 X 7<=TIME_OUT=>TOO_MANY_PEERS, tcp flow: 146010416
top99 : 0.000000, top95 : 0.000000, top75 : 0.000000, max : 0, min : 0, mean : 0.000000, median : 0.000000

16:12:22.167 INFO  [pool-53-thread-1] [DB](Manager.java:1141) Block num: 46428220, re-push-size: 0, pending-size: 0, block-tx-size: 260, verify-tx-size: 260
16:12:22.299 INFO  [TronJClientWorker-0] [net](MessageQueue.java:141) Receive from /47.75.249.119:18888, type: BLOCK
Num:46428238,ID:0000000002c4704e2a d35ab2317e627b8 3bcdfe16603cb592a44, trx size: 297

16:12:22.358 INFO  [TronJClientWorker-0] [net](MessageQueue.java:141) Receive from /47.75.249.119:18888, type: BLOCK
Num:46428243,ID:0000000002c4705324 cbfbf21bed0f83 563c59fa6b1e2a5363e02d, trx size: 255

16:12:22.418 INFO  [TronJClientWorker-0] [net](MessageQueue.java:141) Receive from /47.75.249.119:18888, type: BLOCK
Num:46428274,ID:0000000002c47072 0fe924bf810309f73 3d987f300de2f629a2f, trx size: 300

16:12:22.419 INFO  [TronJClientWorker-0] [net](MessageQueue.java:141) Receive from /47.75.249.119:18888, type: BLOCK
Num:46428280,ID:0000000002c4707 226aae947a2a2 f9cfd403778e57d044ca47c, trx size: 311

16:12:22.420 INFO  [TronJClientWorker-0] [net](MessageQueue.java:141) Receive from /47.75.249.119:18888, type: BLOCK
Num:46428291,ID:0000000002c4708 3a863704b464f 4d3252442066eb07266ab976e, trx size: 251

16:12:22.429 ERROR [pool-53-thread-1] [DB](Manager.java:1244) Bad MAX_FEE_LIMIT parameter value, valid range is [0,10_000_000_000L]
org.tron.core.exception.ContractValidateException: Bad MAX_FEE_LIMIT parameter value, valid range is [0,10_000_000_000L]
	at org.tron.core.utils.ProposalUtil.validator(ProposalUtil.java:398)
	at org.tron.core.actuator.ProposalCreateActuator.validateValue(ProposalCreateActuator.java:124)
	at org.tron.core.actuator.ProposalCreateActuator.validate(ProposalCreateActuator.java:116)
	at org.tron.common.runtime.RuntimeImpl.execute(RuntimeImpl.java:63)
	at org.tron.core.db.TransactionTrace.exec(TransactionTrace.java:180)
	at org.tron.core.db.Manager.processTransaction(Manager.java:1376)
	at org.tron.core.db.Manager.processBlock(Manager.java:1663)
	at org.tron.core.db.Manager.applyBlock(Manager.java:951)
	at org.tron.core.db.Manager.pushBlock(Manager.java:1236)
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:252)
	at org.tron.core.net.service.SyncService.processSyncBlock(SyncService.java:273)
	at org.tron.core.net.service.SyncService.lambda$handleSyncBlock$8(SyncService.java:261)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.tron.core.net.service.SyncService.handleSyncBlock(SyncService.java:243)
	at org.tron.core.net.service.SyncService.lambda$init$1(SyncService.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
16:12:22.429 INFO  [pool-53-thread-1] [DB](PendingManager.java:57) Pending tx size: 0.
16:12:22.429 ERROR [pool-53-thread-1] [net](TronNetDelegate.java:281) Process block failed, Num:46428220,ID:0000000002c4703cb3afc 8cb46206e06 4d8693887a88cab9, reason: Bad MAX_FEE_LIMIT parameter value, valid range is [0,10_000_000_000L]
16:12:22.429 ERROR [pool-53-thread-1] [net](SyncService.java:276) Process sync block Num:46428220,ID:0000000002c4703cb3afc003 4 6206e06a3 4d8693887a88cab9 failed
org.tron.core.exception.P2pException: org.tron.core.exception.ContractValidateException: Bad MAX_FEE_LIMIT parameter value, valid range is [0,10_000_000_000L]
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:282)
	at org.tron.core.net.service.SyncService.processSyncBlock(SyncService.java:273)
	at org.tron.core.net.service.SyncService.lambda$handleSyncBlock$8(SyncService.java:261)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.tron.core.net.service.SyncService.handleSyncBlock(SyncService.java:243)
	at org.tron.core.net.service.SyncService.lambda$init$1(SyncService.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.tron.core.exception.ContractValidateException: Bad MAX_FEE_LIMIT parameter value, valid range is [0,10_000_000_000L]
	at org.tron.core.utils.ProposalUtil.validator(ProposalUtil.java:398)
	at org.tron.core.actuator.ProposalCreateActuator.validateValue(ProposalCreateActuator.java:124)
	at org.tron.core.actuator.ProposalCreateActuator.validate(ProposalCreateActuator.java:116)
	at org.tron.common.runtime.RuntimeImpl.execute(RuntimeImpl.java:63)
	at org.tron.core.db.TransactionTrace.exec(TransactionTrace.java:180)
	at org.tron.core.db.Manager.processTransaction(Manager.java:1376)
	at org.tron.core.db.Manager.processBlock(Manager.java:1663)
	at org.tron.core.db.Manager.applyBlock(Manager.java:951)
	at org.tron.core.db.Manager.pushBlock(Manager.java:1236)
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:252)
	... 12 common frames omitted
16:12:22.430 INFO  [pool-53-thread-1] [net](Channel.java:142) Send to /47.75.249.119:18888 online-time 2s, type: P2P_DISCONNECT
reason: BAD_BLOCK
16:12:22.430 INFO  [pool-53-thread-1] [net](Channel.java:142) Send to /46.4.94.252:18888 online-time 31s, type: P2P_DISCONNECT
reason: BAD_BLOCK
16:12:22.430 INFO  [pool-53-thread-1] [net](Channel.java:142) Send to /116.202.52.186:18888 online-time 31s, type: P2P_DISCONNECT
reason: BAD_BLOCK

please help

**Comment by hitlxy** [comment]
Do you try to restart your node to solve this issue? or a workaround is to add the following item into the node configuration file.
committee = {
 allowTvmLondon = 1 
......
}

**Comment by ahaii** [comment]
> Do you try to restart your node to solve this issue? or a workaround is to add the following item into the node configuration file. committee = { allowTvmLondon = 1 ...... }

Thank you for your reply。

**Comment by ahaii** [comment]
> Do you try to restart your node to solve this issue? or a workaround is to add the following item into the node configuration file. committee = { allowTvmLondon = 1 ...... }

Thanks for your reply.

I restart my node and add `allowTvmLondon` to conf file, but the error still. 
Should I set the value of 'max_fee_limit'?

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
