### ISSUE TITLE
Process block failed, Num:46494224. reason: assetBalance must be greater than 0.

### ISSUE THREAD

**Issue by microcai** [tronprotocol/java-tron#4870]
#### System information

java-tron version: 4.7.0
OS & Version: Linux

#### Expected behaviour
 sync success

#### Actual behaviour
stop sync at height 46494223

#### Steps to reproduce the behaviour

sync from a height lower that 4649423

#### Backtrace

````
03:04:25.869 INFO  [qtp1912688982-49] [o.t.c.Wallet](Wallet.java:669) number: 46494224 is not found!
03:04:25.886 INFO  [nioEventLoopGroup-6-11] [net](MessageQueue.java:141) Receive from /117.139.223.95:34498, type: BLOCK
Num:46494658,ID:0000000002c573c242a3d56b7fbfa3813413fdd2337ba978189130aca0fd0ce4, trx size: 200

03:04:25.887 INFO  [nioEventLoopGroup-6-12] [net](MessageQueue.java:141) Receive from /103.82.227.52:38970, type: BLOCK
Num:46494760,ID:0000000002c5742880d1352c658923f0e6a6ccf65afc9608acb1b9f49e006d26, trx size: 258

03:04:25.888 ERROR [pool-54-thread-1] [DB](Manager.java:1213) assetBalance must be greater than 0.
org.tron.core.exception.ContractValidateException: assetBalance must be greater than 0.
        at org.tron.core.actuator.TransferAssetActuator.validate(TransferAssetActuator.java:163)
        at org.tron.common.runtime.RuntimeImpl.execute(RuntimeImpl.java:63)
        at org.tron.core.db.TransactionTrace.exec(TransactionTrace.java:180)
        at org.tron.core.db.Manager.processTransaction(Manager.java:1344)
        at org.tron.core.db.Manager.processBlock(Manager.java:1631)
        at org.tron.core.db.Manager.applyBlock(Manager.java:920)
        at org.tron.core.db.Manager.pushBlock(Manager.java:1205)
        at org.tron.core.db.Manager$$FastClassBySpringCGLIB$$c79c8985.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
        at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:58)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
        at org.tron.core.db.Manager$$EnhancerBySpringCGLIB$$46707bb4.pushBlock(<generated>)
        at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:252)
        at org.tron.core.net.service.SyncService.processSyncBlock(SyncService.java:273)
        at org.tron.core.net.service.SyncService.lambda$handleSyncBlock$8(SyncService.java:261)
        at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
        at org.tron.core.net.service.SyncService.handleSyncBlock(SyncService.java:243)
        at org.tron.core.net.service.SyncService.lambda$init$1(SyncService.java:83)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
03:04:25.890 INFO  [pool-54-thread-1] [DB](PendingManager.java:57) Pending tx size: 0.
03:04:25.891 INFO  [pool-54-thread-1] [o.t.c.d.b.BackupRocksDBAspect](BackupRocksDBAspect.java:49) AfterThrowing pushBlock
03:04:25.891 ERROR [pool-54-thread-1] [net](TronNetDelegate.java:281) Process block failed, Num:46494224,ID:0000000002c57210e66845f6586bbfcf83c81afa65038f895b87a28124ec5d48, reason: assetBalance must be greater than 0.
03:04:25.891 ERROR [pool-54-thread-1] [net](SyncService.java:276) Process sync block Num:46494224,ID:0000000002c57210e66845f6586bbfcf83c81afa65038f895b87a28124ec5d48 failed
org.tron.core.exception.P2pException: org.tron.core.exception.ContractValidateException: assetBalance must be greater than 0.
        at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:282)
        at org.tron.core.net.service.SyncService.processSyncBlock(SyncService.java:273)
        at org.tron.core.net.service.SyncService.lambda$handleSyncBlock$8(SyncService.java:261)
        at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
        at org.tron.core.net.service.SyncService.handleSyncBlock(SyncService.java:243)
        at org.tron.core.net.service.SyncService.lambda$init$1(SyncService.java:83)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.tron.core.exception.ContractValidateException: assetBalance must be greater than 0.
        at org.tron.core.actuator.TransferAssetActuator.validate(TransferAssetActuator.java:163)
        at org.tron.common.runtime.RuntimeImpl.execute(RuntimeImpl.java:63)
        at org.tron.core.db.TransactionTrace.exec(TransactionTrace.java:180)
        at org.tron.core.db.Manager.processTransaction(Manager.java:1344)
        at org.tron.core.db.Manager.processBlock(Manager.java:1631)
        at org.tron.core.db.Manager.applyBlock(Manager.java:920)
        at org.tron.core.db.Manager.pushBlock(Manager.java:1205)
        at org.tron.core.db.Manager$$FastClassBySpringCGLIB$$c79c8985.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
        at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:58)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
        at org.tron.core.db.Manager$$EnhancerBySpringCGLIB$$46707bb4.pushBlock(<generated>)
        at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:252)
        ... 12 common frames omitted
````

**Comment by forfreeday** [comment]
It is possible that your database is corrupt and the logs indicate that `number: 46494224 is not found!`, usually a corrupt database will cause blocks to be lost.
You will need to download a complete database to resolve this issue

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
