### ISSUE TITLE
Issue with gRPC connection - GreatVoyage-v4.7.0

### ISSUE THREAD

**Issue by terianil** [tronprotocol/java-tron#4927]
#### System information
FullNode.jar --version
OS : Linux
JVM : Amazon.com Inc. 1.8.0_322 amd64
Git : 7683c662dd6e621436f6d7c72ad301c40a7f09c6
Version : 4.7.0
Code : 17585

#### Expected behaviour
Correctly connecting gRPC client.

#### Actual behaviour
Cannot connect from gRPC client:
`{:error, %GRPC.RPCError{status: 13, message: ":stream_error: :closed"}}`

#### Steps to reproduce the behaviour
Update from GreatVoyage-v4.6.0 to GreatVoyage-v4.7.0 

#### Backtrace
```
Jan 17, 2023 1:25:17 PM io.grpc.netty.NettyServerTransport notifyTerminated
INFO: Transport failed
java.lang.UnsupportedOperationException
at io.grpc.netty.AbstractHttp2Headers.setLong(AbstractHttp2Headers.java:465)
at io.grpc.netty.AbstractHttp2Headers.setLong(AbstractHttp2Headers.java:26)
at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:396)
at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:337)
at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$PrefaceFrameListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:698)
at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onHeadersRead(Http2InboundFrameLogger.java:56)
at io.netty.handler.codec.http2.DefaultHttp2FrameReader$2.processFragment(DefaultHttp2FrameReader.java:476)
at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readHeadersFrame(DefaultHttp2FrameReader.java:484)
at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:253)
at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:159)
at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:173)
at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:393)
at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:250)
at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:453)
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:750)
```
### Issue
https://github.com/tronprotocol/java-tron/commit/a0edb2eca738cebcb90655584b91988c57864095

That commit introduced `netty` libs in much more advanced version - `4.1.78.Final`, than `grpc-netty` 1.14.0 (currently used) was released for (Netty 4.1.27). I think that there is a mismatch in compatibility causing `java.lang.UnsupportedOperationException`.
```
compile group: 'io.netty', name: 'netty-codec-http', version: '4.1.78.Final'
compile group: 'io.netty', name: 'netty-handler', version: '4.1.78.Final'
compile group: 'io.netty', name: 'netty-codec-http2', version: '4.1.78.Final'
```
https://github.com/grpc/grpc-java/releases/tag/v1.14.0

**Comment by halibobo1205** [comment]
Can you provide information about the `gRPC client` dependency?

**Comment by halibobo1205** [comment]
`wallet-cli` 
    compile group: 'io.grpc', name: 'grpc-netty', version: '1.9.0'
    compile group: 'io.grpc', name: 'grpc-protobuf', version: '1.9.0'
    compile group: 'io.grpc', name: 'grpc-stub', version: '1.9.0'

**Comment by halibobo1205** [comment]
https://github.com/grpc/grpc-java/issues/7953

**Comment by halibobo1205** [comment]
https://github.com/grpc/grpc-java/pull/7967

**Comment by terianil** [comment]
> Do you use nginx?

No, I don't. I connect directly to our own testnet node.

**Comment by terianil** [comment]
> [grpc/grpc-java#7953](https://github.com/grpc/grpc-java/issues/7953)

Is it possible to revert Natty version before 4.1.60?

**Comment by halibobo1205** [comment]
> 

or remove `content-length` in header temporarily

**Comment by halibobo1205** [comment]
https://github.com/grpc/grpc/issues/29216

**Comment by halibobo1205** [comment]
https://groups.google.com/g/grpc-io/c/Qg1-xxUzwKc
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/82020050/213349306-4ef176db-9974-4341-b89d-97b27fc9ecbb.png">

**Comment by halibobo1205** [comment]
`io.netty.handler.codec.http2`
 ```java
 private void verifyContentLength(Http2Stream stream, int data, boolean isEnd) throws Http2Exception {
        ContentLength contentLength = stream.getProperty(contentLengthKey);
        if (contentLength != null) {
            try {
                contentLength.increaseReceivedBytes(connection.isServer(), stream.id(), data, isEnd);
            } finally {
                if (isEnd) {
                    stream.removeProperty(contentLengthKey);
                }
            }
        }
    }

    private static final class ContentLength {
        private final long expected;
        private long seen;

        ContentLength(long expected) {
            this.expected = expected;
        }

        void increaseReceivedBytes(boolean server, int streamId, int bytes, boolean isEnd) throws Http2Exception {
            seen += bytes;
            // Check for overflow
            if (seen < 0) {
                throw streamError(streamId, PROTOCOL_ERROR,
                        "Received amount of data did overflow and so not match content-length header %d", expected);
            }
            // Check if we received more data then what was advertised via the content-length header.
            if (seen > expected) {
                throw streamError(streamId, PROTOCOL_ERROR,
                        "Received amount of data %d does not match content-length header %d", seen, expected);
            }

            if (isEnd) {
                if (seen == 0 && !server) {
                    // This may be a response to a HEAD request, let's just allow it.
                    return;
                }

                // Check that we really saw what was told via the content-length header.
                if (expected > seen) {
                    throw streamError(streamId, PROTOCOL_ERROR,
                            "Received amount of data %d does not match content-length header %d", seen, expected);
                }
            }
        }
    }
```

As above, If `content-length` is set, be sure to set it correctly

**Comment by halibobo1205** [comment]
https://github.com/netty/netty/pull/11561

**Comment by terianil** [comment]
Everything works fine on the new version - GreatVoyage-v4.7.0.1

**Comment by greenrose51** [comment]
Still same issue on GreatVoyage-v4.7.0.1
![image](https://user-images.githubusercontent.com/86264650/214653234-25b52087-23ba-4031-81c1-d4807b43fdcf.png)
- OS: Ubuntu22.04
- Parameter: 
```
java -XX:ReservedCodeCacheSize=256m -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=512m -XX:MaxDirectMemorySize=1G -XX:+PrintGCDetails -XX:+UseConcMarkSweepGC -XX:NewRatio=2 -XX:+CMSScavengeBeforeRemark -XX:+ParallelRefProcEnabled -XX:+HeapDumpOnOutOfMemoryError -XX:+UseCMSInitiatingOccupancyOnly  -XX:CMSInitiatingOccupancyFraction=70 -jar ./FullNode.jar -c ./main_net_config.conf
```

**Comment by greenrose51** [comment]
@terianil could you please share the FullNode.jar running parameter on GreatVoyage-v4.7.0.1?

**Comment by terianil** [comment]
It's not the same issue, your stack trace is different.

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
