### ISSUE TITLE
io.grpc.netty.NettyServerTransport notifyTerminated - Transport failed

### ISSUE THREAD

**Issue by lovelyrrg51** [tronprotocol/java-tron#4956]
#### System information

java-tron version: v4.7.0.1
OS & Version: Linux
Commit hash : 
#### Expected behaviour
`java -jar FullNode.jar`
#### Actual behaviour
```
Feb 01, 2023 2:43:52 PM io.grpc.netty.NettyServerTransport notifyTerminated
INFO: Transport failed
io.netty.handler.codec.http2.Http2Exception: Unexpected HTTP/1.x request: POST / 
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.readClientPrefaceString(Http2ConnectionHandler.java:314)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:251)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:450)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by lovelyrrg51** [comment]
Thanks for your support, @ethan1844 
Hope to get any update about this asap.
Thanks again.

**Comment by forfreeday** [comment]
grpc-java does not support HTTP/1.x requests

**Comment by lovelyrrg51** [comment]
so what is the solution? @forfreeday

**Comment by forfreeday** [comment]
What client are you using to access this FullNode

**Comment by lovelyrrg51** [comment]
We're gonna provide TRON rpc service. @forfreeday

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.

**Comment by lovelyrrg51** [comment]
It's still issues.
Please share the right config.
Using https://raw.githubusercontent.com/tronprotocol/tron-deployment/master/main_net_config.conf - still above issue
Hope to get your feedback soon.
Thanks.

P.S: I cannot re-open this issue myself.

**Comment by forfreeday** [comment]
What client are you using to access the FullNode you started, please use a client that supports http2 to access it, grpc does not support http1.x

https://github.com/grpc/grpc-web/issues/432
