### ISSUE TITLE
 Process block failed, reason: different resultCode 

### ISSUE THREAD

**Issue by hwf1991** [tronprotocol/java-tron#4965]
### System information

java-tron version: V4.7.0.1
Linux

15:30:40.498 INFO  [pool-48-thread-1] [DB](PendingManager.java:57) Pending tx size: 0.
15:30:40.498 ERROR [pool-48-thread-1] [net](TronNetDelegate.java:284) Process block failed, Num:48331859,ID:0000000002e17c534001bcac309a2be2a128fa369c06b8d56ec8fedb66e125c6, reason: different resultCode txId: e95ef87eb0451476cff0073ea9f5aef06c7a0242ec6e250872e78453b025c866, expect: OUT_OF_ENERGY, actual: SUCCESS
15:30:40.498 ERROR [pool-48-thread-1] [net](SyncService.java:275) Process sync block Num:48331859,ID:0000000002e17c534001bcac309a2be2a128fa369c06b8d56ec8fedb66e125c6 failed
org.tron.core.exception.P2pException: org.tron.core.exception.ReceiptCheckErrException: different resultCode txId: e95ef87eb0451476cff0073ea9f5aef06c7a0242ec6e250872e78453b025c866, expect: OUT_OF_ENERGY, actual: SUCCESS
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:285)
	at org.tron.core.net.service.sync.SyncService.processSyncBlock(SyncService.java:272)
	at org.tron.core.net.service.sync.SyncService.lambda$handleSyncBlock$8(SyncService.java:260)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.tron.core.net.service.sync.SyncService.handleSyncBlock(SyncService.java:242)
	at org.tron.core.net.service.sync.SyncService.lambda$init$1(SyncService.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.tron.core.exception.ReceiptCheckErrException: different resultCode txId: e95ef87eb0451476cff0073ea9f5aef06c7a0242ec6e250872e78453b025c866, expect: OUT_OF_ENERGY, actual: SUCCESS
	at org.tron.core.db.TransactionTrace.check(TransactionTrace.java:318)
	at org.tron.core.db.Manager.processTransaction(Manager.java:1442)
	at org.tron.core.db.Manager.processBlock(Manager.java:1719)
	at org.tron.core.db.Manager.applyBlock(Manager.java:1004)
	at org.tron.core.db.Manager.pushBlock(Manager.java:1289)
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:255)
	... 12 common frames omitted

**Comment by m-o-m12** [comment]
Maybe the node database is damaged, you need to re-download the database snapshot to solve this issue.

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.

**Comment by Gernotbronsert** [comment]
Rinzle tracks him down but after hearing light cycle recognizer vehicle.

**Comment by orstopiky** [comment]
i am facing the same issue. downloading a new snapshot doesn't help since the wrong tx is newer then the snapshot creation.

08:45:00.432 ERROR [sync-handle-block] [DB](Manager.java:1341) different resultCode txId: 245e582c5807cc6763893540647a245caf97e0b2515cefc57ec8e7b8c3a8be7a, expect: OUT_OF_ENERGY, actual: SUCCESS
org.tron.core.exception.ReceiptCheckErrException: different resultCode txId: 245e582c5807cc6763893540647a245caf97e0b2515cefc57ec8e7b8c3a8be7a, expect: OUT_OF_ENERGY, actual: SUCCESS
	at org.tron.core.db.TransactionTrace.check(TransactionTrace.java:342)
	at org.tron.core.db.Manager.processTransaction(Manager.java:1493)
	at org.tron.core.db.Manager.processBlock(Manager.java:1770)
	at org.tron.core.db.Manager.applyBlock(Manager.java:1047)
	at org.tron.core.db.Manager.pushBlock(Manager.java:1333)
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:266)
	at org.tron.core.net.service.sync.SyncService.processSyncBlock(SyncService.java:304)
	at org.tron.core.net.service.sync.SyncService.lambda$handleSyncBlock$9(SyncService.java:290)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.tron.core.net.service.sync.SyncService.handleSyncBlock(SyncService.java:269)
	at org.tron.core.net.service.sync.SyncService.lambda$init$1(SyncService.java:88)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
INFO 2024-07-09T08:45:00.434894671Z [resource.labels.containerName: cneclient] 08:45:00.434 ERROR [sync-handle-block] [net](TronNetDelegate.java:295) Process block failed, Num:63187548,ID:0000000003c42a5c08fbd087b0a5f655094878e624c9c7876ce338ae6254068f, reason: different resultCode txId: 245e582c5807cc6763893540647a245caf97e0b2515cefc57ec8e7b8c3a8be7a, expect: OUT_OF_ENERGY, actual: SUCCESS
  {
    "textPayload": "08:45:00.434 ERROR [sync-handle-block] [net](TronNetDelegate.java:295) Process block failed, Num:63187548,ID:0000000003c42a5c08fbd087b0a5f655094878e624c9c7876ce338ae6254068f, reason: different resultCode txId: 245e582c5807cc6763893540647a245caf97e0b2515cefc57ec8e7b8c3a8be7a, expect: OUT_OF_ENERGY, actual: SUCCESS",
    "insertId": "1hh20y6nhxzbyngl",
    "resource": {
      "type": "k8s_container",
      "labels": {
        "cluster_name": "cltrs-blink-prod-europe-west8",
        "container_name": "cneclient",
        "location": "europe-west8-a",
        "project_id": "verint-blink-prod",
        "namespace_name": "collector-tron",
        "pod_name": "cneclient-tron-0"
      }
    },
    "timestamp": "2024-07-09T08:45:00.434894671Z",
    "severity": "INFO",
    "labels": {
      "k8s-pod/statefulset_kubernetes_io/pod-name": "cneclient-tron-0",
      "compute.googleapis.com/resource_name": "gke-cltrs-blink-prod-cltrs-blink-prod-1816b113-27x4",
      "k8s-pod/name": "cneclient-tron",
      "k8s-pod/controller-revision-hash": "cneclient-tron-5c6c974656"
    },
    "logName": "projects/verint-blink-prod/logs/stdout",
    "receiveTimestamp": "2024-07-09T08:45:02.908979669Z"
  }
