### ISSUE TITLE
OUT_OF_ENERGY

### ISSUE THREAD

**Issue by hwf1991** [tronprotocol/java-tron#4966]
#### System information

OS : Linux
JVM : Oracle Corporation 1.8.0_361 amd64
Git : 7683c662dd6e621436f6d7c72ad301c40a7f09c6
Version : 4.7.0
Code : 17585

#### Expected behaviour
16:44:40.213 ERROR [pool-48-thread-1] [net](TronNetDelegate.java:284) Process block failed, Num:48331859,ID:0000000002e17c534001bcac309a2be2a128fa369c06b8d56ec8fedb66e125c6, reason: different resultCode txId: e95ef87eb0451476cff0073ea9f5aef06c7a0242ec6e250872e78453b025c866, expect: OUT_OF_ENERGY, actual: SUCCESS
16:44:40.213 ERROR [pool-48-thread-1] [net](SyncService.java:275) Process sync block Num:48331859,ID:0000000002e17c534001bcac309a2be2a128fa369c06b8d56ec8fedb66e125c6 failed
org.tron.core.exception.P2pException: org.tron.core.exception.ReceiptCheckErrException: different resultCode txId: e95ef87eb0451476cff0073ea9f5aef06c7a0242ec6e250872e78453b025c866, expect: OUT_OF_ENERGY, actual: SUCCESS
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:285)
	at org.tron.core.net.service.sync.SyncService.processSyncBlock(SyncService.java:272)
	at org.tron.core.net.service.sync.SyncService.lambda$handleSyncBlock$8(SyncService.java:260)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.tron.core.net.service.sync.SyncService.handleSyncBlock(SyncService.java:242)
	at org.tron.core.net.service.sync.SyncService.lambda$init$1(SyncService.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.tron.core.exception.ReceiptCheckErrException: different resultCode txId: e95ef87eb0451476cff0073ea9f5aef06c7a0242ec6e250872e78453b025c866, expect: OUT_OF_ENERGY, actual: SUCCESS
	at org.tron.core.db.TransactionTrace.check(TransactionTrace.java:318)
	at org.tron.core.db.Manager.processTransaction(Manager.java:1442)
	at org.tron.core.db.Manager.processBlock(Manager.java:1719)
	at org.tron.core.db.Manager.applyBlock(Manager.java:1004)
	at org.tron.core.db.Manager.pushBlock(Manager.java:1289)
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:255)
	... 12 common frames omitted

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by lin-zh-cn** [comment]
**System information**
`image: tronprotocol/java-tron:GreatVoyage-v4.7.0.1`

[root@tron-8598c8c479-5hd88 java-tron]# cat /proc/cpuinfo | grep -e "cpu cores" -e "siblings" | sort | uniq
```
cpu cores       : 8
siblings        : 16
```
[root@tron-8598c8c479-5hd88 java-tron]# free -g
```
              total        used        free      shared  buff/cache   available
Mem:             61          12          36           0          13          48
Swap:             0           0           0
```

[root@tron-8598c8c479-5hd88 java-tron]# ps -ef|grep java
`root           1       0 62 15:01 ?        00:05:23 /usr/local/jre/bin/java -XX:+UseConcMarkSweepGC -XX:+PrintGCDetails -Xloggc:./gc.log -XX:+PrintGCDateStamps -XX:+CMSParallelRemarkEnabled -XX:ReservedCodeCacheSize=256m -XX:+CMSScavengeBeforeRemark -Xmx24g -XX:+HeapDumpOnOutOfMemoryError -classpath /java-tron/lib/zksnark-java-sdk-1.0.0.jar:/java-tron/lib/vavr-match-0.9.2.jar:/java-tron/lib/vavr-0.9.2.jar:/java-tron/lib/typetools-0.4.7.jar:/java-tron/lib/sqlite-jdbc-3.16.1.jar:/java-tron/lib/spring-tx-5.3.18.jar:/java-tron/lib/spring-jcl-5.3.18.jar:/java-tron/lib/spring-expression-5.3.18.jar:/java-tron/lib/spring-core-5.3.18.jar:/java-tron/lib/spring-context-5.3.18.jar:/java-tron/lib/spring-beans-5.3.18.jar:/java-tron/lib/spring-aop-5.3.18.jar:/java-tron/lib/slf4j-api-1.7.32.jar:/java-tron/lib/simpleclient_tracer_otel_agent-0.15.0.jar:/java-tron/lib/simpleclient_tracer_otel-0.15.0.jar:/java-tron/lib/simpleclient_tracer_common-0.15.0.jar:/java-tron/lib/simpleclient_httpserver-0.15.0.jar:/java-tron/lib/simpleclient_hotspot-0.15.0.jar:/java-tron/lib/simpleclient_common-0.15.0.jar:/java-tron/lib/simpleclient-0.15.0.jar:/java-tron/lib/rocksdbjni-5.15.10.jar:/java-tron/lib/reflections-0.9.11.jar:/java-tron/lib/reflectasm-1.10.1.jar:/java-tron/lib/quartz-2.3.2.jar:/java-tron/lib/protocol-1.0.0.jar:/java-tron/lib/protobuf-java-util-3.19.2.jar:/java-tron/lib/protobuf-java-3.19.2.jar:/java-tron/lib/proto-google-common-protos-1.0.0.jar:/java-tron/lib/pf4j-2.5.0.jar:/java-tron/lib/opencensus-contrib-grpc-metrics-0.12.3.jar:/java-tron/lib/opencensus-api-0.12.3.jar:/java-tron/lib/objenesis-2.1.jar:/java-tron/lib/netty-transport-4.1.27.Final.jar:/java-tron/lib/netty-resolver-4.1.27.Final.jar:/java-tron/lib/netty-handler-proxy-4.1.27.Final.jar:/java-tron/lib/netty-handler-4.1.27.Final.jar:/java-tron/lib/netty-common-4.1.27.Final.jar:/java-tron/lib/netty-codec-socks-4.1.27.Final.jar:/java-tron/lib/netty-codec-http2-4.1.27.Final.jar:/java-tron/lib/netty-codec-http-4.1.27.Final.jar:/java-tron/lib/netty-codec-4.1.27.Final.jar:/java-tron/lib/netty-buffer-4.1.27.Final.jar:/java-tron/lib/minlog-1.3.0.jar:/java-tron/lib/metrics-influxdb-0.8.2.jar:/java-tron/lib/metrics-core-3.1.2.jar:/java-tron/lib/mchange-commons-java-0.2.15.jar:/java-tron/lib/logback-core-1.2.9.jar:/java-tron/lib/logback-classic-1.2.9.jar:/java-tron/lib/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/java-tron/lib/libp2p-0.1.2.jar:/java-tron/lib/leveldbjni-all-1.8.jar:/java-tron/lib/kryo-serializers-0.37.jar:/java-tron/lib/kryo-3.0.3.jar:/java-tron/lib/junit-4.12.jar:/java-tron/lib/jsr305-3.0.2.jar:/java-tron/lib/jsonrpc4j-1.6.jar:/java-tron/lib/json-io-2.4.1.jar:/java-tron/lib/joda-time-2.3.jar:/java-tron/lib/jnacl-1.0.0.jar:/java-tron/lib/jetty-util-ajax-9.4.49.v20220914.jar:/java-tron/lib/jetty-util-9.4.49.v20220914.jar:/java-tron/lib/jetty-servlet-9.4.49.v20220914.jar:/java-tron/lib/jetty-server-9.4.49.v20220914.jar:/java-tron/lib/jetty-security-9.4.49.v20220914.jar:/java-tron/lib/jetty-io-9.4.49.v20220914.jar:/java-tron/lib/jetty-http-9.4.49.v20220914.jar:/java-tron/lib/jeromq-0.5.0.jar:/java-tron/lib/jcommander-1.72.jar:/java-tron/lib/jcl-over-slf4j-1.7.25.jar:/java-tron/lib/jcip-annotations-1.0.jar:/java-tron/lib/javax.servlet-api-3.1.0.jar:/java-tron/lib/javax.inject-1.jar:/java-tron/lib/javassist-3.21.0-GA.jar:/java-tron/lib/java-util-1.8.0.jar:/java-tron/lib/java-sizeof-0.0.5.jar:/java-tron/lib/java-semver-0.9.0.jar:/java-tron/lib/jansi-1.16.jar:/java-tron/lib/jackson-databind-2.13.4.1.jar:/java-tron/lib/jackson-core-2.13.4.jar:/java-tron/lib/jackson-annotations-2.13.4.jar:/java-tron/lib/j2objc-annotations-1.3.jar:/java-tron/lib/httpcore-nio-4.4.5.jar:/java-tron/lib/httpcore-4.4.5.jar:/java-tron/lib/httpclient-4.5.1.jar:/java-tron/lib/httpasyncclient-4.1.1.jar:/java-tron/lib/hawtjni-runtime-1.18.jar:/java-tron/lib/hamcrest-core-1.3.jar:/java-tron/lib/guice-4.1.0.jar:/java-tron/lib/guava-30.1-jre.jar:/java-tron/lib/gson-2.8.6.jar:/java-tron/lib/grpc-stub-1.14.0.jar:/java-tron/lib/grpc-protobuf-lite-1.14.0.jar:/java-tron/lib/grpc-protobuf-1.14.0.jar:/java-tron/lib/grpc-netty-1.14.0.jar:/java-tron/lib/grpc-core-1.14.0.jar:/java-tron/lib/grpc-context-1.14.0.jar:/java-tron/lib/googleapis-common-protos-0.0.3.jar:/java-tron/lib/framework-1.0.0.jar:/java-tron/lib/fastjson-1.2.83.jar:/java-tron/lib/failureaccess-1.0.1.jar:/java-tron/lib/error_prone_annotations-2.5.1.jar:/java-tron/lib/crypto-1.0.0.jar:/java-tron/lib/cqengine-stream-support-1.1.0.jar:/java-tron/lib/cqengine-2.12.4.jar:/java-tron/lib/consensus-1.0.0.jar:/java-tron/lib/config-1.3.2.jar:/java-tron/lib/concurrent-trees-2.6.0.jar:/java-tron/lib/commons-math-2.2.jar:/java-tron/lib/commons-logging-1.2.jar:/java-tron/lib/commons-lang3-3.12.0.jar:/java-tron/lib/commons-io-2.11.0.jar:/java-tron/lib/commons-collections4-4.1.jar:/java-tron/lib/commons-codec-1.11.jar:/java-tron/lib/commons-cli-1.5.0.jar:/java-tron/lib/common-1.0.0.jar:/java-tron/lib/checker-qual-3.5.0.jar:/java-tron/lib/chainbase-1.0.0.jar:/java-tron/lib/c3p0-0.9.5.4.jar:/java-tron/lib/bcprov-jdk15on-1.69.jar:/java-tron/lib/base64-2.3.9.jar:/java-tron/lib/aspectjweaver-1.8.13.jar:/java-tron/lib/aspectjtools-1.8.13.jar:/java-tron/lib/aspectjrt-1.8.13.jar:/java-tron/lib/asm-5.0.3.jar:/java-tron/lib/aopalliance-1.0.jar:/java-tron/lib/antlr4-runtime-4.5.jar:/java-tron/lib/actuator-1.0.0.jar:/java-tron/lib/HikariCP-java7-2.4.13.jar: org.tron.program.FullNode -c /java-tron/config/main_net_config.conf --es`


**Expected behaviour**

[root@tron-8598c8c479-5hd88 java-tron]# grep ERROR logs/tron.log 
```
15:02:23.212 ERROR [pool-48-thread-1] [DB](Manager.java:1297) different resultCode txId: e95ef87eb0451476cff0073ea9f5aef06c7a0242ec6e250872e78453b025c866, expect: OUT_OF_ENERGY, actual: SUCCESS

15:02:23.214 ERROR [pool-48-thread-1] [net](TronNetDelegate.java:284) Process block failed, Num:48331859,ID:0000000002e17c534001bcac309a2be2a128fa369c06b8d56ec8fedb66e125c6, reason: different resultCode txId: e95ef87eb0451476cff0073ea9f5aef06c7a0242ec6e250872e78453b025c866, expect: OUT_OF_ENERGY, actual: SUCCESS

15:02:23.214 ERROR [pool-48-thread-1] [net](SyncService.java:275) Process sync block Num:48331859,ID:0000000002e17c534001bcac309a2be2a128fa369c06b8d56ec8fedb66e125c6 failed
```

```
15:02:23.214 ERROR [pool-48-thread-1] [net](TronNetDelegate.java:284) Process block failed, Num:48331859,ID:0000000002e17c534001bcac309a2be2a128fa369c06b8d56ec8fedb66e125c6, reason: different resultCode txId: e95ef87eb0451476cff0073ea9f5aef06c7a0242ec6e250872e78453b025c866, expect: OUT_OF_ENERGY, actual: SUCCESS
15:02:23.214 ERROR [pool-48-thread-1] [net](SyncService.java:275) Process sync block Num:48331859,ID:0000000002e17c534001bcac309a2be2a128fa369c06b8d56ec8fedb66e125c6 failed
org.tron.core.exception.P2pException: org.tron.core.exception.ReceiptCheckErrException: different resultCode txId: e95ef87eb0451476cff0073ea9f5aef06c7a0242ec6e250872e78453b025c866, expect: OUT_OF_ENERGY, actual: SUCCESS
        at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:285)
        at org.tron.core.net.service.sync.SyncService.processSyncBlock(SyncService.java:272)
        at org.tron.core.net.service.sync.SyncService.lambda$handleSyncBlock$8(SyncService.java:260)
        at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
        at org.tron.core.net.service.sync.SyncService.handleSyncBlock(SyncService.java:242)
        at org.tron.core.net.service.sync.SyncService.lambda$init$1(SyncService.java:83)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.tron.core.exception.ReceiptCheckErrException: different resultCode txId: e95ef87eb0451476cff0073ea9f5aef06c7a0242ec6e250872e78453b025c866, expect: OUT_OF_ENERGY, actual: SUCCESS
        at org.tron.core.db.TransactionTrace.check(TransactionTrace.java:318)
        at org.tron.core.db.Manager.processTransaction(Manager.java:1442)
        at org.tron.core.db.Manager.processBlock(Manager.java:1719)
        at org.tron.core.db.Manager.applyBlock(Manager.java:1004)
        at org.tron.core.db.Manager.pushBlock(Manager.java:1289)
        at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:255)
        ... 12 common frames omitted
```

**Comment by lin-zh-cn** [comment]
> 
```
vm = {
  supportConstant = true
  minTimeRatio = 0.0
  maxTimeRatio = 5.0
}
```
