### ISSUE TITLE
Sync stuck on block 38004300 (nile testnet)

### ISSUE THREAD

**Issue by ruanbekker** [tronprotocol/java-tron#5299]
#### System information

OS : `Linux`
JVM : `Temurin 1.8.0_372 amd64`
Git : `d5da6ae21692f149afe5cedffed85afd932f4b66`
Version : `4.7.1.1`
Code : `17686`

#### Expected behaviour

The blocks from my node should be in sync with the block numbers represented on the tronscan block explorer

#### Actual behaviour

Sync stays on block number 38004300 (nile testnet)

When following the block explorer https://nile.tronscan.org/#/ and at this point in time the block number was [38005606](https://nile.tronscan.org/#/block/38005606) but when I run:

```bash
curl -s http://$host:$port/wallet/getnowblock | jq -r '.block_header.raw_data'
{
  "number": 38004300,
  "version": 28,
  "timestamp": 1687932489000
}
```

Its been stuck on block 38004300 since 2023-06-28 06:08 UTC

#### Steps to reproduce the behaviour

Download https://github.com/tronprotocol/java-tron/releases/tag/GreatVoyage-v4.7.1.1, start the node, finish the sync (or restore from snapshot) sync gets stuck (verified on 2 different nodes)

#### Backtrace

Please see below:

````
06:09:36.175 ERROR [pool-48-thread-1] [net](TronNetDelegate.java:284) Process block failed, Num:38004301,ID:000000000243e64ded88e8db5e69ed93b77e6b5dae2187fcb36702f6013fe8c0, reason: Does not support code : 77
06:09:36.176 ERROR [pool-48-thread-1] [net](SyncService.java:288) Process sync block Num:38004301,ID:000000000243e64ded88e8db5e69ed93b77e6b5dae2187fcb36702f6013fe8c0 failed
org.tron.core.exception.P2pException: org.tron.core.exception.ContractValidateException: Does not support code : 77
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:285)
	at org.tron.core.net.service.sync.SyncService.processSyncBlock(SyncService.java:285)
	at org.tron.core.net.service.sync.SyncService.lambda$handleSyncBlock$9(SyncService.java:273)
	at java.util.concurrent.ConcurrentHashMap.forEach(Unknown Source)
	at org.tron.core.net.service.sync.SyncService.handleSyncBlock(SyncService.java:255)
	at org.tron.core.net.service.sync.SyncService.lambda$init$1(SyncService.java:84)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.tron.core.exception.ContractValidateException: Does not support code : 77
	at org.tron.core.utils.ProposalUtil$ProposalType.getEnum(ProposalUtil.java:779)
	at org.tron.core.utils.ProposalUtil.validator(ProposalUtil.java:28)
	at org.tron.core.actuator.ProposalCreateActuator.validateValue(ProposalCreateActuator.java:124)
	at org.tron.core.actuator.ProposalCreateActuator.validate(ProposalCreateActuator.java:116)
	at org.tron.common.runtime.RuntimeImpl.execute(RuntimeImpl.java:63)
	at org.tron.core.db.TransactionTrace.exec(TransactionTrace.java:187)
	at org.tron.core.db.Manager.processTransaction(Manager.java:1432)
	at org.tron.core.db.Manager.processBlock(Manager.java:1722)
	at org.tron.core.db.Manager.applyBlock(Manager.java:1007)
	at org.tron.core.db.Manager.pushBlock(Manager.java:1292)
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:255)
	... 12 common frames omitted
06:09:36.176 INFO  [pool-48-thread-1] [net](PeerConnection.java:171) Send peer /47.90.214.183:18888 message type: P2P_DISCONNECT
reason: BAD_BLOCK
````

**Comment by m-o-m12** [comment]
Hi @ruanbekker The TRON Nile testnet has already been upgraded to the GreatVoyage-v4.7.2 (Periander) pre-release version, and initiated a [proposal](https://nile.tronscan.org/#/proposal/19568) related to Periander. That is why your node stopped syncing from 38004301. So upgrading your node on Nile testnet to Periander version will solve your issue.  Download the code [here](https://github.com/tronprotocol/java-tron/tree/Nile) and compile it.

**Comment by ruanbekker** [comment]
Thanks @m-o-m12 for the fast response, appreciate it.

**Comment by apwiegman** [comment]
Hi @m-o-m12! Is there a tag for this release? 

https://github.com/tronprotocol/java-tron/tags

**Comment by apwiegman** [comment]
cool - thanks @m-o-m12!

**Comment by junghyun0783** [comment]
I'm running a tron node with docker right now
How do I update to GreatVoyage-v4.7.2 when running with Docker? It's embarrassing.

**Comment by junghyun0783** [comment]
@m-o-m12 First of all, thank you for your kind reply.
However, you told me to build from the code you gave me, but the docker.sh command doesn't work. I want to build, but I am unable to build.
how can i build it?

**Comment by vivian-kang** [comment]
> @m-o-m12 First of all, thank you for your kind reply. However, you told me to build from the code you gave me, but the docker.sh command doesn't work. I want to build, but I am unable to build. how can i build it? Do I need to edit the dockerfile?

@junghyun0783 Thanks for your contribution to Java-tron. Because you has already create a new issuse #5311 , So close this one.

**Comment by vivian-kang** [comment]
> @m-o-m12 First of all, thank you for your kind reply. However, you told me to build from the code you gave me, but the docker.sh command doesn't work. I want to build, but I am unable to build. how can i build it? Do I need to edit the dockerfile?

@junghyun0783  Because you have already create a new issue #5311 , So Lets go to #5311 to discuss this issue. Thanks.

**Comment by junghyun0783** [comment]
@vivian1912 
First of all, thank you for your kind response.
I solved the problem by creating an image file with a Docker file.
thank you
