### ISSUE TITLE
not working and the node crashes

### ISSUE THREAD

**Issue by Hossein-Teimouri** [tronprotocol/java-tron#5336]
#### System information

java-tron version: 
OS : Linux
JVM : Oracle Corporation 1.8.0_371 i386
Git : 9e95599de2a9d60f4e706d18d3b71ac8850a0c01
Version : 4.7.2
Code : 18031

OS & Version: 
OS: Linux
Description:    Ubuntu 20.04.6 LTS
Release:        20.04

#### Expected behaviour
Run and synchronization with Tron network.

#### Actual behaviour
````
06:40:47.463 INFO  [main] [app](FullNode.java:55) Full node running.
06:50:22.866 INFO  [main] [app](FullNode.java:55) Full node running.
06:50:23.260 WARN  [main] [app](LocalWitnesses.java:104) PrivateKey is null.
06:50:23.600 INFO  [main] [app](Args.java:1534) Bind address wasn't set, Punching to identify it...
06:50:24.027 INFO  [main] [app](Args.java:1537) UDP local bound to: 185.208.181.18
06:50:24.028 INFO  [main] [app](Args.java:1552) External IP wasn't set, using checkip.amazonaws.com to identify it...
06:50:24.495 INFO  [main] [app](Args.java:1566) External address identified: 142.54.189.108
06:50:24.502 INFO  [main] [app](Args.java:1649) 

06:50:24.502 INFO  [main] [app](Args.java:1650) ************************ Net config ************************
06:50:24.502 INFO  [main] [app](Args.java:1651) P2P version: 11111
06:50:24.502 INFO  [main] [app](Args.java:1652) Bind IP: 185.208.181.18
06:50:24.502 INFO  [main] [app](Args.java:1653) External IP: 142.54.189.108
06:50:24.502 INFO  [main] [app](Args.java:1654) Listen port: 18888
06:50:24.502 INFO  [main] [app](Args.java:1655) Node ipv6 enable: false
06:50:24.502 INFO  [main] [app](Args.java:1656) Discover enable: true
06:50:24.502 INFO  [main] [app](Args.java:1657) Active node size: 0
06:50:24.502 INFO  [main] [app](Args.java:1658) Passive node size: 0
06:50:24.502 INFO  [main] [app](Args.java:1659) FastForward node size: 2
06:50:24.502 INFO  [main] [app](Args.java:1660) FastForward node number: 3
06:50:24.503 INFO  [main] [app](Args.java:1661) Seed node size: 30
06:50:24.503 INFO  [main] [app](Args.java:1662) Max connection: 30
06:50:24.503 INFO  [main] [app](Args.java:1663) Min connection: 8
06:50:24.503 INFO  [main] [app](Args.java:1664) Min active connection: 3
06:50:24.503 INFO  [main] [app](Args.java:1665) Max connection with same IP: 2
06:50:24.503 INFO  [main] [app](Args.java:1666) Solidity threads: 4
06:50:24.503 INFO  [main] [app](Args.java:1667) Trx reference block: solid
06:50:24.503 INFO  [main] [app](Args.java:1668) Open full tcp disconnect: true
06:50:24.503 INFO  [main] [app](Args.java:1669) Node detect enable: false
06:50:24.503 INFO  [main] [app](Args.java:1670) Node effective check enable: false
06:50:24.503 INFO  [main] [app](Args.java:1671) Rate limiter global qps: 50000
06:50:24.504 INFO  [main] [app](Args.java:1672) Rate limiter global ip qps: 10000
06:50:24.504 INFO  [main] [app](Args.java:1673) ************************ Backup config ************************
06:50:24.504 INFO  [main] [app](Args.java:1674) Backup priority: 8
06:50:24.504 INFO  [main] [app](Args.java:1675) Backup listen port: 10001
06:50:24.504 INFO  [main] [app](Args.java:1676) Backup listen keepAliveInterval: 3000
06:50:24.504 INFO  [main] [app](Args.java:1677) Backup member size: 0
06:50:24.504 INFO  [main] [app](Args.java:1678) ************************ Code version *************************
06:50:24.504 INFO  [main] [app](Args.java:1679) Code version : 4.7.2
06:50:24.504 INFO  [main] [app](Args.java:1680) Version code: 18031
06:50:24.504 INFO  [main] [app](Args.java:1681) ************************ DB config *************************
06:50:24.505 INFO  [main] [app](Args.java:1682) DB engine : LEVELDB
06:50:24.505 INFO  [main] [app](Args.java:1683) Snapshot max flush count: 1
06:50:24.505 INFO  [main] [app](Args.java:1684) ***************************************************************
06:50:24.505 INFO  [main] [app](Args.java:1685) ************************ shutDown config *************************
06:50:24.505 INFO  [main] [app](Args.java:1686) ShutDown blockTime  : null
06:50:24.505 INFO  [main] [app](Args.java:1687) ShutDown blockHeight : -1
06:50:24.505 INFO  [main] [app](Args.java:1688) ShutDown blockCount : -1
06:50:24.505 INFO  [main] [app](Args.java:1689) ***************************************************************
06:50:24.505 INFO  [main] [app](Args.java:1690) 

06:50:24.505 INFO  [main] [app](FullNode.java:71) not in debug mode, it will check energy time
06:50:29.636 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB account open success with writeBufferSize 64 M, cacheSize 32 M, maxOpenFiles 100.
06:50:29.698 INFO  [main] [app](DefaultConfig.java:51) key-value data source created.
06:50:29.704 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB tmp open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:29.732 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB accountTrie open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:29.753 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB balance-trace open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:29.762 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB account-trace open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:29.785 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB properties open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:29.919 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB account-asset open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:29.927 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB block open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:29.934 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB witness open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:29.942 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB asset-issue open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:29.948 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB asset-issue-v2 open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:29.954 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB block-index open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:29.961 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB accountid-index open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:29.967 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB account-index open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:29.974 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB witness_schedule open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:29.980 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB votes open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:29.987 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB proposal open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:29.993 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB exchange open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:29.999 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB exchange-v2 open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:30.004 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB market_account open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:30.010 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB market_order open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:30.017 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB market_pair_price_to_order open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:30.024 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB market_pair_to_price open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:30.029 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB abi open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:30.035 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB code open success with writeBufferSize 64 M, cacheSize 32 M, maxOpenFiles 100.
06:50:30.041 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB contract open success with writeBufferSize 64 M, cacheSize 32 M, maxOpenFiles 100.
06:50:30.048 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB contract-state open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:30.054 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB DelegatedResource open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:30.060 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB DelegatedResourceAccountIndex open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:30.066 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB storage-row open success with writeBufferSize 64 M, cacheSize 32 M, maxOpenFiles 100.
06:50:30.071 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB nullifier open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:30.076 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB zkProof open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:30.081 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB IncrementalMerkleTree open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:30.088 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB delegation open success with writeBufferSize 64 M, cacheSize 32 M, maxOpenFiles 100.
06:50:30.096 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB block_KDB open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:30.102 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB common open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:30.107 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB trans open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:30.114 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB transactionRetStore open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:30.120 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB recent-block open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:30.125 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB recent-transaction open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:30.130 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB transactionHistoryStore open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:30.135 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB common-database open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:30.139 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB pbft-sign-data open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:30.145 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB tree-block-index open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:30.150 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB section-bloom open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:30.218 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB trans-cache open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
06:50:30.269 INFO  [main] [DB](SnapshotManager.java:512) checkpoint v1 recover success
06:50:30.273 INFO  [main] [DB](TxCacheDB.java:106) Load cache from persistentStore, db: 0, filter: 0, filter-fpp: 0.0, cost: 2 ms.
06:50:30.274 INFO  [main] [DB](TxCacheDB.java:129) Load cache from recentTransactionStore, filter: 0, filter-fpp: 0.0, cost: 1 ms.
06:50:30.388 INFO  [main] [DB](Manager.java:2384) Load trans for lite node.
06:50:30.389 INFO  [main] [DB](Manager.java:2407) Load trans complete, trans: 0, from = 9223372036854775807, to = -9223372036854775808.
06:50:30.389 INFO  [main] [DB](Manager.java:518) Current headNum is: 0.
06:50:30.390 INFO  [main] [DB](Manager.java:520) Node type is: full.
06:50:30.930 INFO  [main] [o.r.Reflections](Reflections.java:232) Reflections took 523 ms to scan 1 urls, producing 489 keys and 2813 values 
06:50:31.109 INFO  [main] [o.s.b.f.a.AutowiredAnnotationBeanPostProcessor](AutowiredAnnotationBeanPostProcessor.java:478) Autowired annotation is not supported on static fields: private static final java.util.concurrent.ConcurrentHashMap org.tron.core.config.args.Args.solidityContractLogTriggerMap
06:50:31.109 INFO  [main] [o.s.b.f.a.AutowiredAnnotationBeanPostProcessor](AutowiredAnnotationBeanPostProcessor.java:478) Autowired annotation is not supported on static fields: private static final java.util.concurrent.ConcurrentHashMap org.tron.core.config.args.Args.solidityContractEventTriggerMap
06:50:31.935 INFO  [main] [app](FullNode.java:143) ********register application shutdown hook********
06:50:31.937 INFO  [main] [API](FullNodeHttpApiService.java:322) init zk param begin
06:50:31.941 ERROR [main] [app](DefaultConfig.java:42) Uncaught exception
java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [java.lang.LinkageError: Unable to load library zksnarkjni]
	at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:237)
	at org.fusesource.hawtjni.runtime.Library.load(Library.java:189)
	at org.tron.common.zksnark.LibrustzcashWrapper.<clinit>(LibrustzcashWrapper.java:22)
	at org.tron.common.zksnark.JLibrustzcash.isOpenZen(JLibrustzcash.java:316)
	at org.tron.core.services.http.FullNodeHttpApiService.librustzcashInitZksnarkParams(FullNodeHttpApiService.java:324)
	at org.tron.core.services.http.FullNodeHttpApiService.init(FullNodeHttpApiService.java:352)
	at org.tron.common.application.ServiceContainer.init(ServiceContainer.java:46)
	at org.tron.common.application.ApplicationImpl.initServices(ApplicationImpl.java:57)
	at org.tron.program.FullNode.main(FullNode.java:135)
	Suppressed: java.lang.LinkageError: Unable to load library zksnarkjni
		at org.fusesource.hawtjni.runtime.Library.loadLibrary(Library.java:543)
		at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:221)
		... 8 common frames omitted
	Caused by: java.lang.UnsatisfiedLinkError: no zksnarkjni in java.library.path
		at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1863)
		at java.lang.Runtime.loadLibrary0(Runtime.java:843)
		at java.lang.System.loadLibrary(System.java:1134)
		at org.fusesource.hawtjni.runtime.Library.loadLibrary(Library.java:539)
		... 9 common frames omitted
````
#### Command executed
````
java -Xms3g -jar FullNode.jar -c main_net_config.conf -d /root/test-tron/FullNode/data
````

I have another question, how to see the log at the time of executing the command, I am currently reading from the file.

**Comment by lxcmyf** [comment]
@Hossein-Teimouri 
The jdk you are using is 32-bit. We apologize that Java tron does not support 32-bit jdks. Please reconfigure the jdk and its environment variables and try again. If successful, please let us know.

**Comment by Hossein-Teimouri** [comment]
> @Hossein-Teimouri The jdk you are using is 32-bit. We apologize that Java tron does not support 32-bit jdks. Please reconfigure the jdk and its environment variables and try again. If successful, please let us know.

Thank you for your help, my problem is solved

**Comment by asi90sp** [comment]
Ok
