### ISSUE TITLE
Connection with http protocol

### ISSUE THREAD

**Issue by Hossein-Teimouri** [tronprotocol/java-tron#5341]
### System information

java-tron version: 
JVM : Oracle Corporation 1.8.0_371 amd64
Git : d5da6ae21692f149afe5cedffed85afd932f4b66
Version : 4.7.1.1

OS & Version:
OS: Linux
Description:    Ubuntu 20.04.6 LTS
Release:        20.04

### 1. What did you do?
I want to use [tronpy](https://tronpy.readthedocs.io/en/latest/quickstart.html#quickstart) project to communicate with tron node
This library communicates with an http connection
I don't know what to enter (ip:port) and my connection is disconnected

#### The configuration I use is the default configuration file
[Config file.](https://github.com/tronprotocol/tron-deployment/blob/master/main_net_config.conf)

### 2. What did you expect to see?
Establishing the right connection and output.

#### The program code that runs:
```` python
from tronpy import Tron
from tronpy.providers import HTTPProvider

# Connect to the TRON node using HTTP Provider
client = Tron(HTTPProvider("http://172.0.0.1:50051"))

txi = client.get_transaction("8a31a5f930d035ce737cf007a02f3bf997807f53a4ca14b624bc1c7cf8dd3498")

print(f'data: \n\n {txi} \n\n')

````

### 3. What did you see instead?
````
root@teymuri:~# python3 test-tron.py
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 164, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f8e4284c880>, 'Connection to 172.0.0.1 timed out. (connect timeout=10.0)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='172.0.0.1', port=50051): Max retries exceeded with url: /wallet/gettransactionbyid (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f8e4284c880>, 'Connection to 172.0.0.1 timed out. (connect timeout=10.0)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test-tron.py", line 8, in <module>
    txi = client.get_transaction("8a31a5f930d035ce737cf007a02f3bf997807f53a4ca14b624bc1c7cf8dd3498")
  File "/usr/local/lib/python3.8/dist-packages/tronpy/tron.py", line 860, in get_transaction
    ret = self.provider.make_request("wallet/gettransactionbyid", {"value": txn_id, "visible": True})
  File "/usr/local/lib/python3.8/dist-packages/tronpy/providers/http.py", line 81, in make_request
    resp = self.sess.post(url, json=params, timeout=self.timeout)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)

requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='172.0.0.1', port=50051): Max retries exceeded with url: /wallet/gettransactionbyid (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f8e4284c880>, 'Connection to 172.0.0.1 timed out. (connect timeout=10.0)'))
````

**Comment by Jake151987** [comment]
@Hossein-Teimouri, if you are calling with HTTP, then the node port is,
fullNodePort = 8090
  solidityPort = 8091
The code you posted is calling the RPC port, not the HTTP port. From the line 167 to 174 in the config file, you will find all the ports for either HTTP or RPC.

**Comment by Hossein-Teimouri** [comment]
I connected to port 8090
But it doesn't recognize ip 172.0.0.1, I have to enter the address in localhost
http://localhost:8090
If I want to replace another ip, what should I change in ganfig?

**Comment by Jake151987** [comment]
@Hossein-Teimouri The local host should be 127.0.0.1, let me know if it works.
