### ISSUE TITLE
java.lang.IllegalStateException: STREAMED: (GetRewardServlet.java:36)

### ISSUE THREAD

**Issue by forfreeday** [tronprotocol/java-tron#5356]
#### System information

OS : `Linux`
JVM : `Oracle 1.8`
Version : `4.7.2`
Commit hash: `9e95599`
codeVersion: `18031`

#### Expected behaviour

Returns normal results when requesting `getReward` interface.

```
curl --location 'http://$IP:$PORT/wallet/getReward' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'address='
```

**result**

```
{
    "reward": 0
}
```

#### Actual behaviour

When I request `getReward` interface, it returns an exception message, and it should return the correct result.

```
10:30:50.359 ERROR [qtp1946337255-186242] [API](GetRewardServlet.java:36)
java.lang.IllegalStateException: STREAMED
    at org.eclipse.jetty.server.Request.getReader(Request.java:1188)
    at org.tron.core.services.http.Util.getAddress(Util.java:496)
    at org.tron.core.services.http.GetRewardServlet.doGet(GetRewardServlet.java:23)
    at org.tron.core.services.http.GetRewardServlet.doPost(GetRewardServlet.java:46)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at org.tron.core.services.http.RateLimiterServlet.service(RateLimiterServlet.java:109)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
...
```

#### Steps to reproduce the behaviour

Requesting the GetRewardServlet interface

```
curl --location 'http://$IP:$PORT/wallet/getReward' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'address='
```

return error message

```
10:30:50.359 ERROR [qtp1946337255-186242] [API](GetRewardServlet.java:36)
java.lang.IllegalStateException: STREAMED
    at org.eclipse.jetty.server.Request.getReader(Request.java:1188)
    at org.tron.core.services.http.Util.getAddress(Util.java:496)
    at org.tron.core.services.http.GetRewardServlet.doGet(GetRewardServlet.java:23)
    at org.tron.core.services.http.GetRewardServlet.doPost(GetRewardServlet.java:46)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at org.tron.core.services.http.RateLimiterServlet.service(RateLimiterServlet.java:109)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
...
```

**Comment by halibobo1205** [comment]
In my view, this is not really a bug, it's due to passing invalid parameters, and there should be similar scenarios.

**Comment by forfreeday** [comment]
This is not a bug, but it must also return normal information, not an exception.

**Comment by forfreeday** [comment]
@halibobo1205 
Yes, I've fixed the issue and submitted this PR: https://github.com/tronprotocol/java-tron/pull/5351

**Comment by lxcmyf** [comment]
@forfreeday 
Does the optimized interface request support the x-www form urlencoded content-type?
