### ISSUE TITLE
Can't initialize database - frequency happend

### ISSUE THREAD

**Issue by RockyDK007** [tronprotocol/java-tron#5511]
Dear Team,

I download screenshot with below link, and ran successfully, but after a day this error suddenly happen. Then I tried to redo and this experience repeating happening for 3 times. Could you please help to solve this issue?
http://52.77.31.45/backup20230918/FullNode_output-directory.tgz

00:13:21.655 INFO  [db-stats-thread-0] [metrics](DbStat.java:20) DB market_pair_price_to_order, level:0,files:0.0,size:0.0 M
00:13:21.663 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB market_pair_to_price open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:13:21.663 INFO  [db-stats-thread-0] [metrics](DbStat.java:20) DB market_pair_to_price, level:0,files:0.0,size:0.0 M
00:13:21.688 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB abi open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:13:21.688 INFO  [db-stats-thread-0] [metrics](DbStat.java:20) DB abi, level:0,files:1.0,size:1.0 M
00:13:21.689 INFO  [db-stats-thread-0] [metrics](DbStat.java:20) DB abi, level:3,files:80.0,size:137.0 M
00:13:21.718 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB code open success with writeBufferSize 64 M, cacheSize 32 M, maxOpenFiles 100.
00:13:21.719 INFO  [db-stats-thread-0] [metrics](DbStat.java:20) DB code, level:0,files:1.0,size:1.0 M
00:13:21.719 INFO  [db-stats-thread-0] [metrics](DbStat.java:20) DB code, level:3,files:546.0,size:993.0 M
00:13:21.719 INFO  [db-stats-thread-0] [metrics](DbStat.java:20) DB code, level:4,files:21.0,size:30.0 M
00:13:21.749 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB contract open success with writeBufferSize 64 M, cacheSize 32 M, maxOpenFiles 100.
00:13:21.750 INFO  [db-stats-thread-0] [metrics](DbStat.java:20) DB contract, level:0,files:1.0,size:1.0 M
00:13:21.750 INFO  [db-stats-thread-0] [metrics](DbStat.java:20) DB contract, level:2,files:1.0,size:0.0 M
00:13:21.750 INFO  [db-stats-thread-0] [metrics](DbStat.java:20) DB contract, level:3,files:494.0,size:855.0 M
00:13:21.809 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB contract-state open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:13:21.810 INFO  [db-stats-thread-0] [metrics](DbStat.java:20) DB contract-state, level:0,files:1.0,size:1.0 M
00:13:21.810 INFO  [db-stats-thread-0] [metrics](DbStat.java:20) DB contract-state, level:2,files:17.0,size:31.0 M
00:13:21.925 INFO  [main] [DB](LevelDbDataSourceImpl.java:147) DB DelegatedResource open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:13:21.926 INFO  [db-stats-thread-0] [metrics](DbStat.java:20) DB DelegatedResource, level:0,files:1.0,size:3.0 M
00:13:21.926 INFO  [db-stats-thread-0] [metrics](DbStat.java:20) DB DelegatedResource, level:2,files:2.0,size:3.0 M
00:13:21.976 WARN  [main] [o.t.c.a.TronApplicationContext](AbstractApplicationContext.java:591) Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'transactionUtil': Unsatisfied dependency expressed through field 'chainBaseManager'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'chainBaseManager': Unsatisfied dependency expressed through field 'delegatedResourceAccountIndexStore'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'delegatedResourceAccountIndexStore' defined in URL [jar:file:/data/tron/FullNode.jar!/org/tron/core/store/DelegatedResourceAccountIndexStore.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.tron.core.store.DelegatedResourceAccountIndexStore]: Constructor threw exception; nested exception is java.lang.RuntimeException: Can't initialize database, DelegatedResourceAccountIndex
00:13:21.994 ERROR [main] [app](DefaultConfig.java:42) Uncaught exception
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'transactionUtil': Unsatisfied dependency expressed through field 'chainBaseManager'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'chainBaseManager': Unsatisfied dependency expressed through field 'delegatedResourceAccountIndexStore'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'delegatedResourceAccountIndexStore' defined in URL [jar:file:/data/tron/FullNode.jar!/org/tron/core/store/DelegatedResourceAccountIndexStore.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.tron.core.store.DelegatedResourceAccountIndexStore]: Constructor threw exception; nested exception is java.lang.RuntimeException: Can't initialize database, DelegatedResourceAccountIndex
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:659)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:639)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.tron.program.FullNode.main(FullNode.java:82)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'chainBaseManager': Unsatisfied dependency expressed through field 'delegatedResourceAccountIndexStore'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'delegatedResourceAccountIndexStore' defined in URL [jar:file:/data/tron/FullNode.jar!/org/tron/core/store/DelegatedResourceAccountIndexStore.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.tron.core.store.DelegatedResourceAccountIndexStore]: Constructor threw exception; nested exception is java.lang.RuntimeException: Can't initialize database, DelegatedResourceAccountIndex
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:659)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:639)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:656)
	... 14 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'delegatedResourceAccountIndexStore' defined in URL [jar:file:/data/tron/FullNode.jar!/org/tron/core/store/DelegatedResourceAccountIndexStore.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.tron.core.store.DelegatedResourceAccountIndexStore]: Constructor threw exception; nested exception is java.lang.RuntimeException: Can't initialize database, DelegatedResourceAccountIndex
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:315)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:296)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:656)
	... 28 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.tron.core.store.DelegatedResourceAccountIndexStore]: Constructor threw exception; nested exception is java.lang.RuntimeException: Can't initialize database, DelegatedResourceAccountIndex
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:224)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:311)
	... 41 common frames omitted
Caused by: java.lang.RuntimeException: Can't initialize database, DelegatedResourceAccountIndex
	at org.tron.common.storage.leveldb.LevelDbDataSourceImpl.initDB(LevelDbDataSourceImpl.java:128)
	at org.tron.common.storage.leveldb.LevelDbDataSourceImpl.<init>(LevelDbDataSourceImpl.java:96)
	at org.tron.core.db.TronStoreWithRevoking.<init>(TronStoreWithRevoking.java:64)
	at org.tron.core.store.DelegatedResourceAccountIndexStore.<init>(DelegatedResourceAccountIndexStore.java:32)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211)
	... 43 common frames omitted
Caused by: org.fusesource.leveldbjni.internal.NativeDB$DBException: Corruption: checksum mismatch
	at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200)
	at org.fusesource.leveldbjni.internal.NativeDB.open(NativeDB.java:218)
	at org.fusesource.leveldbjni.JniDBFactory.open(JniDBFactory.java:168)
	at org.tron.common.storage.leveldb.LevelDbDataSourceImpl.openDatabase(LevelDbDataSourceImpl.java:145)
	at org.tron.common.storage.leveldb.LevelDbDataSourceImpl.initDB(LevelDbDataSourceImpl.java:125)
	... 51 common frames omitted

**Comment by halibobo1205** [comment]
> I download screenshot with below link, and ran successfully, but after a day this error suddenly happen. 

@RockyDK007 Hi,  was the machine down during that time?


> Then I tried to redo and this experience repeating happening for 3 times

 After the data is downloaded, is it an error on startup?

From the above information, it is clear that the `DelegatedResourceAccountIndex` database is corrupt.

**Comment by RockyDK007** [comment]
hi @halibobo1205, The server was not down during that time.

**Comment by halibobo1205** [comment]
@RockyDK007 , We rechecked the database, and there was no such problem, suggest checking to see if the disk is full or other issues.

**Comment by vivian1912** [comment]
@RockyDK007 Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.
Please feel free to re-open it if you still see the issue, thanks.
