### ISSUE TITLE
Recommended ports

### ISSUE THREAD

**Issue by bondibox** [tronprotocol/java-tron#563]
My java-tron instance is purring along nicely now, just waiting in the queue to process blocks.

One of my tricks is this command
`more java-tron/logs/tron.log | grep nodes.`
which turns up lines like these
> Write Node statistics to PeersStore: 2437 nodes.

However when I connect wallet-cli to the server I don't get expected results. I started out leaving the config file alone, and then thought maybe the server wasn't listening on the loopback because I configured a specific IP to bind to. But the error I get when I try 'GetBlock' it returns

> io.grpc.StatusRuntimeException: UNAVAILABLE: io exception

When I login and try 'getBalance' it returns

> 23:57:58.659 [main] INFO TestClient - Get Balance failed !!!!
        at org.tron.walletserver.WalletClient.queryAccount(WalletClient.java:225)
        at org.tron.walletserver.WalletClient.queryAccount(WalletClient.java:221)
        at org.tron.walletcli.Client.queryAccount(Client.java:162)
        at org.tron.walletcli.TestClient.getBalance(TestClient.java:156)
        at org.tron.walletcli.TestClient.run(TestClient.java:736)
        at org.tron.walletcli.TestClient.main(TestClient.java:853)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: tronmain/23.239.19.106:50050
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:323)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:633)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused

You can see it's trying port 50050, so I opened 50050 on the firewall but still it doesn't connect the wallet. Is there a Solidity setting in the java-tron config file that needs to be set? Other than port 18888 and 50051 are there other ports that need to be opened?

**Comment by bondibox** [comment]
Moving to wallet-cli
