### ISSUE TITLE
Nile testnet node, block synchronization stopped 

### ISSUE THREAD

**Issue by user357831** [tronprotocol/java-tron#5652]
Hi,

On Jan 6th at ~21:40 UTC both of my nile testnet nodes stopped block synchronization.

Could you tell me please if there were any updates on nile testnet side? What can I do to fix the issue?

```
Jan 07 11:44:10 tron-test-node-01 tron-testnet[3487935]: 11:44:10.801 INFO  [peerClient-16] [DB](Manager.java:1906) HeadNumber: 43284760, syncBeginNumber: 43284742, solidBlockNumber: 43284742.
Jan 07 11:44:11 tron-test-node-01 tron-testnet[3487935]: 11:44:11.386 INFO  [peerClient-16] [DB](Manager.java:1906) HeadNumber: 43284760, syncBeginNumber: 43284742, solidBlockNumber: 43284742.
Jan 07 11:44:13 tron-test-node-01 tron-testnet[3487935]: 11:44:13.294 INFO  [sync-handle-block] [DB](Manager.java:1214) Block num: 43284761, re-push-size: 0, pending-size: 0, block-tx-size: 2, verify-tx-size: 2
Jan 07 11:44:13 tron-test-node-01 tron-testnet[3487935]: 11:44:13.296 WARN  [sync-handle-block] [actuator](TransferActuator.java:160) Balance is not sufficient. Account: TDvSsdrNM5eeXNL3czpa6AxLDHZA9nwe9K, balance: 184000, amount: 184001, fee: 0.
Jan 07 11:44:13 tron-test-node-01 tron-testnet[3487935]: 11:44:13.296 ERROR [sync-handle-block] [DB](Manager.java:1318) Validate TransferContract error, balance is not sufficient.
Jan 07 11:44:13 tron-test-node-01 tron-testnet[3487935]: org.tron.core.exception.ContractValidateException: Validate TransferContract error, balance is not sufficient.
Jan 07 11:44:13 tron-test-node-01 tron-testnet[3487935]:         at org.tron.core.actuator.TransferActuator.validate(TransferActuator.java:162)
Jan 07 11:44:13 tron-test-node-01 tron-testnet[3487935]:         at org.tron.common.runtime.RuntimeImpl.execute(RuntimeImpl.java:63)
Jan 07 11:44:13 tron-test-node-01 tron-testnet[3487935]:         at org.tron.core.db.TransactionTrace.exec(TransactionTrace.java:189)
Jan 07 11:44:13 tron-test-node-01 tron-testnet[3487935]:         at org.tron.core.db.Manager.processTransaction(Manager.java:1450)
Jan 07 11:44:13 tron-test-node-01 tron-testnet[3487935]:         at org.tron.core.db.Manager.processBlock(Manager.java:1740)
Jan 07 11:44:13 tron-test-node-01 tron-testnet[3487935]:         at org.tron.core.db.Manager.applyBlock(Manager.java:1024)
Jan 07 11:44:13 tron-test-node-01 tron-testnet[3487935]:         at org.tron.core.db.Manager.pushBlock(Manager.java:1310)
Jan 07 11:44:13 tron-test-node-01 tron-testnet[3487935]:         at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:260)
Jan 07 11:44:13 tron-test-node-01 tron-testnet[3487935]:         at org.tron.core.net.service.sync.SyncService.processSyncBlock(SyncService.java:304)
Jan 07 11:44:13 tron-test-node-01 tron-testnet[3487935]:         at org.tron.core.net.service.sync.SyncService.lambda$handleSyncBlock$9(SyncService.java:290)
Jan 07 11:44:13 tron-test-node-01 tron-testnet[3487935]:         at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
Jan 07 11:44:13 tron-test-node-01 tron-testnet[3487935]:         at org.tron.core.net.service.sync.SyncService.handleSyncBlock(SyncService.java:269)
Jan 07 11:44:13 tron-test-node-01 tron-testnet[3487935]:         at org.tron.core.net.service.sync.SyncService.lambda$init$1(SyncService.java:88)
Jan 07 11:44:13 tron-test-node-01 tron-testnet[3487935]:         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Jan 07 11:44:13 tron-test-node-01 tron-testnet[3487935]:         at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
Jan 07 11:44:13 tron-test-node-01 tron-testnet[3487935]:         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
Jan 07 11:44:13 tron-test-node-01 tron-testnet[3487935]:         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
Jan 07 11:44:13 tron-test-node-01 tron-testnet[3487935]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Jan 07 11:44:13 tron-test-node-01 tron-testnet[3487935]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Jan 07 11:44:13 tron-test-node-01 tron-testnet[3487935]:         at java.lang.Thread.run(Thread.java:748)
Jan 07 11:44:13 tron-test-node-01 tron-testnet[3487935]: 11:44:13.297 INFO  [sync-handle-block] [DB](PendingManager.java:57) Pending tx size: 0.
Jan 07 11:44:13 tron-test-node-01 tron-testnet[3487935]: 11:44:13.297 ERROR [sync-handle-block] [net](TronNetDelegate.java:289) Process block failed, Num:43284761,ID:0000000002947919904f1353664a949c8f21f8c1b40b3d925d90c1e6edc21a92, reason: Validate TransferContract error, balance is not sufficient.
Jan 07 11:44:13 tron-test-node-01 tron-testnet[3487935]: 11:44:13.297 ERROR [sync-handle-block] [net](SyncService.java:307) Process sync block Num:43284761,ID:0000000002947919904f1353664a949c8f21f8c1b40b3d925d90c1e6edc21a92 failed, type: 10, bad block
Jan 07 11:44:13 tron-test-node-01 tron-testnet[3487935]: 11:44:13.693 INFO  [peerClient-2] [DB](Manager.java:1906) HeadNumber: 43284760, syncBeginNumber: 43284742, solidBlockNumber: 43284742.
Jan 07 11:44:14 tron-test-node-01 tron-testnet[3487935]: 11:44:14.289 INFO  [peerClient-2] [DB](Manager.java:1906) HeadNumber: 43284760, syncBeginNumber: 43284742, solidBlockNumber: 43284742.
Jan 07 11:44:20 tron-test-node-01 tron-testnet[3487935]: 11:44:20.027 INFO  [peerClient-5] [DB](Manager.java:1906) HeadNumber: 43284760, syncBeginNumber: 43284742, solidBlockNumber: 43284742.
```

**Comment by jwrct** [comment]
Based on the error logs, it seems that the local node data is inconsistent with the on-chain data. It is recommended to download the latest data snapshot and restart for recovery.
https://database.nileex.io/

**Comment by Jony321** [comment]
I have the same problem.
Started on January 6 at 21:40 UTC

<details><summary>tron.log</summary>

```
============ Peer stats: all 0, active 0, passive 0


13:34:05.690 INFO  [connPool] [net](ConnPoolService.java:194) Connect to peer /47.90.214.183:18888
13:34:07.695 WARN  [peerClient-14] [net](PeerClient.java:72) Connect to peer /47.90.214.183:18888 fail, cause:connection timed out: /47.90.214.183:18888
13:34:07.696 INFO  [peerClient-14] [net](P2pChannelInitializer.java:45) Close channel:null
13:34:07.696 WARN  [peerClient-14] [net](ChannelManager.java:90) Notify Disconnect peer has no address.
13:34:08.423 INFO  [peerWorker-19] [net](P2pChannelInitializer.java:45) Close channel:/172.18.0.1:57336
13:34:08.423 INFO  [peerWorker-19] [net](ConnPoolService.java:261) Peer stats: channels 0, activePeers 0, active 0, passive 0
13:34:09.292 INFO  [connPool] [net](ConnPoolService.java:194) Connect to peer /47.90.214.183:18888
13:34:11.298 WARN  [peerClient-15] [net](PeerClient.java:72) Connect to peer /47.90.214.183:18888 fail, cause:connection timed out: /47.90.214.183:18888
13:34:11.298 INFO  [peerClient-15] [net](P2pChannelInitializer.java:45) Close channel:null
13:34:11.299 WARN  [peerClient-15] [net](ChannelManager.java:90) Notify Disconnect peer has no address.
13:34:12.895 INFO  [connPool] [net](ConnPoolService.java:194) Connect to peer /47.90.214.183:18888
13:34:14.229 INFO  [peer-manager] [net](PeerManager.java:152) 

============ Peer stats: all 0, active 0, passive 0


13:34:14.901 WARN  [peerClient-16] [net](PeerClient.java:72) Connect to peer /47.90.214.183:18888 fail, cause:connection timed out: /47.90.214.183:18888
13:34:14.902 INFO  [peerClient-16] [net](P2pChannelInitializer.java:45) Close channel:null
13:34:14.902 WARN  [peerClient-16] [net](ChannelManager.java:90) Notify Disconnect peer has no address.
13:34:16.498 INFO  [connPool] [net](ConnPoolService.java:194) Connect to peer /47.90.214.183:18888
13:34:18.426 INFO  [peerWorker-20] [net](P2pChannelInitializer.java:45) Close channel:/172.18.0.1:36698
13:34:18.427 INFO  [peerWorker-20] [net](ConnPoolService.java:261) Peer stats: channels 0, activePeers 0, active 0, passive 0
13:34:18.502 WARN  [peerClient-17] [net](PeerClient.java:72) Connect to peer /47.90.214.183:18888 fail, cause:connection timed out: /47.90.214.183:18888
13:34:18.503 INFO  [peerClient-17] [net](P2pChannelInitializer.java:45) Close channel:null
13:34:18.503 WARN  [peerClient-17] [net](ChannelManager.java:90) Notify Disconnect peer has no address.
13:34:20.100 INFO  [connPool] [net](ConnPoolService.java:194) Connect to peer /47.90.214.183:18888
13:34:22.105 WARN  [peerClient-18] [net](PeerClient.java:72) Connect to peer /47.90.214.183:18888 fail, cause:connection timed out: /47.90.214.183:18888
13:34:22.106 INFO  [peerClient-18] [net](P2pChannelInitializer.java:45) Close channel:null
13:34:22.106 WARN  [peerClient-18] [net](ChannelManager.java:90) Notify Disconnect peer has no address.
13:34:23.703 INFO  [connPool] [net](ConnPoolService.java:194) Connect to peer /47.90.214.183:18888
13:34:24.230 INFO  [peer-manager] [net](PeerManager.java:152) 

============ Peer stats: all 0, active 0, passive 0


13:34:25.709 WARN  [peerClient-19] [net](PeerClient.java:72) Connect to peer /47.90.214.183:18888 fail, cause:connection timed out: /47.90.214.183:18888
13:34:25.710 INFO  [peerClient-19] [net](P2pChannelInitializer.java:45) Close channel:null
13:34:25.710 WARN  [peerClient-19] [net](ChannelManager.java:90) Notify Disconnect peer has no address.
13:34:27.306 INFO  [connPool] [net](ConnPoolService.java:194) Connect to peer /47.90.214.183:18888
13:34:28.429 INFO  [peerWorker-21] [net](P2pChannelInitializer.java:45) Close channel:/172.18.0.1:37382
13:34:28.429 INFO  [peerWorker-21] [net](ConnPoolService.java:261) Peer stats: channels 0, activePeers 0, active 0, passive 0
13:34:29.310 WARN  [peerClient-20] [net](PeerClient.java:72) Connect to peer /47.90.214.183:18888 fail, cause:connection timed out: /47.90.214.183:18888
13:34:29.311 INFO  [peerClient-20] [net](P2pChannelInitializer.java:45) Close channel:null
13:34:29.311 WARN  [peerClient-20] [net](ChannelManager.java:90) Notify Disconnect peer has no address.
13:34:30.908 INFO  [connPool] [net](ConnPoolService.java:194) Connect to peer /47.90.214.183:18888
```

</details>

Is synchronization from a snapshot the only way to restore functionality?

**Comment by user357831** [comment]
Hi @jwrct, 

Thanks! I recovered my nodes from the latest snapshot.
