### ISSUE TITLE
[Bounty]SolidityNode Run will OutOfMemoryError

### ISSUE THREAD

**Issue by deanrobin** [tronprotocol/java-tron#566]
I watch 'top' about an hour
Fullnode need memory 1.6G
But SolidityNode need more than 3.3G 

There is log....

```
18:02:48.562 ERROR [org.tron.program.SolidityNode] [general](DefaultConfig.java:26) Uncaught exception
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.spongycastle.math.ec.ECPoint$Fp.twiceJacobianModified(ECPoint.java:1342)
	at org.spongycastle.math.ec.ECPoint$Fp.twicePlus(ECPoint.java:1082)
	at org.spongycastle.math.ec.ECAlgorithms.implSumOfMultiplies(ECAlgorithms.java:480)
	at org.spongycastle.math.ec.ECAlgorithms.implSumOfMultiplies(ECAlgorithms.java:434)
	at org.spongycastle.math.ec.ECAlgorithms.implSumOfMultipliesGLV(ECAlgorithms.java:395)
	at org.spongycastle.math.ec.ECAlgorithms.sumOfTwoMultiplies(ECAlgorithms.java:90)
	at org.tron.common.crypto.ECKey.recoverPubBytesFromSignature(ECKey.java:661)
	at org.tron.common.crypto.ECKey.signatureToKeyBytes(ECKey.java:452)
	at org.tron.common.crypto.ECKey.signatureToKeyBytes(ECKey.java:427)
	at org.tron.common.crypto.ECKey.signatureToAddress(ECKey.java:470)
	at org.tron.core.capsule.TransactionCapsule.validateSignature(TransactionCapsule.java:312)
	at org.tron.core.db.Manager.processTransaction(Manager.java:735)
	at org.tron.core.db.Manager.processBlock(Manager.java:869)
	at org.tron.core.db.Manager.applyBlock(Manager.java:464)
	at org.tron.core.db.Manager.pushBlock(Manager.java:610)
	at org.tron.program.SolidityNode.syncSolidityBlock(SolidityNode.java:74)
	at org.tron.program.SolidityNode.syncLoop(SolidityNode.java:52)
	at org.tron.program.SolidityNode.lambda$start$0(SolidityNode.java:94)
	at org.tron.program.SolidityNode$$Lambda$97/215415062.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)

```

And log this `update latest block header number = 4239`

How much memory do I need???

**Comment by deanrobin** [comment]
and, Can you explicate SolidityNode so slow...

**Comment by deanrobin** [comment]
`[Full GC (Ergonomics) [PSYoungGen: 2036736K->400365K(2066944K)] [ParOldGen: 3022736K->3022470K(3022848K)] 5059472K->3422836K(5089792K), [Metaspace: 35294K->35294K(1081344K)], 17.2483837 secs] [Times: user=52.08 sys=0.14, real=17.24 secs] 
Heap after GC invocations=220 (full 33):
 PSYoungGen      total 2066944K, used 400365K [0x0000000740000000, 0x00000007c0000000, 0x00000007c0000000)
  eden space 2036736K, 19% used [0x0000000740000000,0x00000007586fb740,0x00000007bc500000)
  from space 30208K, 0% used [0x00000007bc500000,0x00000007bc500000,0x00000007be280000)
  to   space 29696K, 0% used [0x00000007be300000,0x00000007be300000,0x00000007c0000000)
 ParOldGen       total 3022848K, used 3022470K [0x0000000687800000, 0x0000000740000000, 0x0000000740000000)
  object space 3022848K, 99% used [0x0000000687800000,0x000000073ffa1b50,0x0000000740000000)
 Metaspace       used 35294K, capacity 35982K, committed 36184K, reserved 1081344K
  class space    used 4285K, capacity 4411K, committed 4480K, reserved 1048576K
}
`
After Full GC, OldGen not decrease memory..
I guess, maybe some connection no close or some collection object need less..

**Comment by zhaohong** [comment]
@huzhenyuan  follow this.

**Comment by huzhenyuan** [comment]
caused by cqengine
when push new block in solidity node, cqengine obtain memory for every block

**Comment by huzhenyuan** [comment]
@Yrp

**Comment by deanrobin** [comment]
@huzhenyuan  
If you fix this bug, please tell me.
thank you

**Comment by deanrobin** [comment]
My Email: ladeanrobin@163.com

**Comment by Yrp** [comment]
@deanrobin Hi,this problem has been fixed. The latest develop branch contains this fix. But the latest code is not compatible with online public testnet. We will update public test with the latest develop branch, and inform you by then.

**Comment by Yrp** [comment]
@deanrobin Please pull the latest code and try again.

**Comment by deanrobin** [comment]
Build fail...my friend
`org.tron.core.net.node.StartFetchSyncBlockTest > testStartFetchSyncBlock FAILED
    java.util.NoSuchElementException
        at java.util.ArrayList$Itr.next(ArrayList.java:854)
        at org.tron.core.net.node.StartFetchSyncBlockTest.testStartFetchSyncBlock(StartFetchSyncBlockTest.java:97)`
`org.tron.core.witness.WitnessControllerTest > testSlot FAILED
    java.lang.AssertionError: expected:<4> but was:<21>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at org.tron.core.witness.WitnessControllerTest.testSlot(WitnessControllerTest.java:50)`

And I should use which branch, develop or master. I guess develop

**Comment by Yrp** [comment]
hi, @deanrobin Is there still a OutOfMemoryError problem?

**Comment by deanrobin** [comment]
@Yrp  HI, I just run lastest code about two days. That's very good.
I think it hasn't that problem and you can close it.

**Comment by deanrobin** [comment]
By the way, Document write very good, But I think may be write some comments or note in code that is better for us.Like parameter calculation unit.

**Comment by marcusyanghe** [comment]
Hi, @deanrobin 
I am pleased to inform you that you are rewarded TRX from Tron Foundation for your contribution in our Bug Bounty Program in May 2018. Please provide a valid account address that can receive the TRX reward.
Please send the address to my email yanghe@tron.network so we can deliver the TRX on time.
Thanks,
Marcus Yang
