### ISSUE TITLE
Optimize Insufficient TRX Error Message of Multi-Sign Transaction

### ISSUE THREAD

**Issue by lxcmyf** [tronprotocol/java-tron#5736]
# Rationale

Currently, when users try to query the maximum delegated bandwidth through the `/wallet/getcandelegatedmaxsize` interface, they find that the bandwidth margin is sufficient. However, when using the `/wallet/delegateresource` interface for delegateing resource, they may encounter an error message "Account resource insufficient error." After investigation, it was found that the actual reason for this error is not insufficient bandwidth resources, but insufficient transaction (TRX) balance in the account. This is because this transaction is a multi signature transaction, and the transaction cost of the multi signature operation needs to be deducted from the TRX balance of the account.

The current issue lies in the broad and sometimes inaccurate definition of the exception thrown. This can lead to confusion and misunderstanding among users, who may wrongly believe that they need to purchase more bandwidth resources instead of simply topping up their TRX balance.

To address this, we propose two solutions:

1. **Replacing the Exception Type:** Currently, there is an exception type called "BalanceInsufficientException", which can be used instead of the previously misreported "AccountResourceInsufficientException", insufficient TRX balance for multi-signature transactions.
2. **Extending the Existing Exception Type:** Alternatively, we can expand the meaning of the current exception type to include the possibility of insufficient TRX balance, perhaps by adding an "or" clause to its description.

# Implementation

### Solution 1: Replacing the exception type

- Identify the current exception class being thrown for the "Account resource insufficient" error.

- Currently, there is an exception type called "BalanceInsufficientException", which can be used instead of the previously misreported "AccountResourceInsufficientException", specifically for the case of insufficient TRX balance for multi-signature transactions.

- Update the relevant code paths within the specific implementation to throw this new exception type when the TRX balance is insufficient.

- Update the error handling and messaging systems to recognize and display the new exception type with an appropriate error message.

### Solution 2: Extending the Existing Exception Type

- Identify the current exception class being thrown for the "Account resource insufficient" error.

- Modify the exception class's description or message to include the possibility of insufficient TRX balance for multi-signature transactions, perhaps by adding an "or" clause.

- Update the relevant code paths within the specific implementation to throw this modified exception when either the bandwidth resources or the TRX balance is insufficient.

- Update the error handling and messaging systems to recognize and display the modified exception with an appropriate error message.

Either solution would help improve the user experience by providing a more accurate and useful error message in the case of insufficient TRX balance for multi-signature transactions.

**Comment by CarlChaoCarl** [comment]
Nice, I support option one

**Comment by halibobo1205** [comment]
> Nice, I support option one

+1,  The error message is clear

**Comment by lxcmyf** [comment]
> Is it possible to determine the account type during the query and return the correct amount of available resources?

@tomatoishealthy 
This may not be related to the account type, as this transaction is a multi signature transaction, so an additional deduction of account TRX is required, and this fee consumption is not deducted from the available bandwidth of the account.

**Comment by lxcmyf** [comment]
Considering that the abnormal information thrown by Plan 2 may cause ambiguity, Plan 1 will be used to optimize this issue.

**Comment by YuMenGuan** [comment]
> Considering that the abnormal information thrown by option 2 may cause ambiguity, option 1 will be used to optimize this issue.
@lxcmyf  
Option 1 is also my choose. But I have another question, whether the error message can contain the information of minimum quantity of TRX the account should have.

**Comment by lxcmyf** [comment]
@YuMenGuan 
It's feasible, good advice.

**Comment by lxcmyf** [comment]
For this issue, further assessment will be conducted on the current error message return mechanism to identify the most suitable improvement direction. Ensuring better compatibility in future version updates is a priority.

**Comment by lxcmyf** [comment]
1

**Comment by studentforcode** [comment]
Hello ,
### **is any help to my tronpy sample add ? i will be appreciate is some one engage** 
i realized problem from multisig wallet how to bypas it ?


E:\tronwallet>python a.py
{'permission': {'keys': [{'address': '417b3be285dc2e***********c40c30f950814303b',
                          'weight': 1}],
                'permission_name': 'owner',
                'threshold': 1},
 'raw_data': {'contract': [{'parameter': {'type_url': 'type.googleapis.com/protocol.TransferContract',
                                          'value': {'amount': 300,
                                                    'owner_address': '417b3be285dc*************40c30f950814303b',
                                                    'to_address': '414297483ba5927****************66cca876e58fa10f'}},
                            'type': 'TransferContract'}],
              'data': '7465737****6d656d6f',
              'expiration': 17410******65651,
              'ref_block_bytes': '71fd',
              'ref_block_hash': 'b4e5e6****425f269',
              'timestamp': 1741******05651},
 'signature': [],
 'txID': 'ae6faf35528fabf*********************cf50c7862b89f590878fd5a5ab61'}
Traceback (most recent call last):
  File "E:\tronwallet\a.py", line 14, in <module>
    .broadcast()
     ~~~~~~~~~^^
  File "C:\Users\j\AppData\Local\Programs\Python\Python313\Lib\site-packages\tronpy\tron.py", line 184, in broadcast
    return TransactionRet(self._client.broadcast(self), client=self._client, method=self._method)
                          ~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\j\AppData\Local\Programs\Python\Python313\Lib\site-packages\tronpy\tron.py", line 1079, in broadcast
    self._handle_api_error(payload)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\j\AppData\Local\Programs\Python\Python313\Lib\site-packages\tronpy\tron.py", line 618, in _handle_api_error
    raise UnknownError(msg, payload["code"])
tronpy.exceptions.UnknownError: ('Account resource insufficient error.', 'BANDWITH_ERROR')

E:\tronwallet>



a.py application code



from tronpy import Tron
from tronpy.keys import PrivateKey

client = Tron(network='nile')
# Private key of TMCorX**********vMkDr1pFN4JW56
priv_key = PrivateKey(bytes.fromhex("e796f91b583929096********************800f44f14c35b84d3d"))

txn = (
    client.trx.transfer("TMCorXWTUC********r1pFN4JW56", "TG3JpzHoDCBcj*******yzGFDw", 3_00)
    .memo("test memo")
     .build()
    .inspect()
    .sign(priv_key)
    .broadcast()
)

print(txn)
# > {'result': True, 'txid': '5182b96bc0d74f416d6b************6a11d4df030459132'}
print()
# > {'id': '5182b96bc0d74f*************5a6a11d4df030459132', 'blockNumber': 6415370, 'blockTimeStamp': 1591951155000, 'contractResult': [''], 'receipt': {'net_usage': 283}}

**Comment by Sunny6889** [comment]
@studentforcode  I noticed the error: `'Account resource insufficient error.', 'BANDWIDTH_ERROR'`. Please ensure that your account has sufficient bandwidth or TRX. You can also delegate TRX for additional bandwidth. For more information, check the [developer documentation](https://tronprotocol.github.io/documentation-en/mechanism-algorithm/resource/#bandwidth-points).

**Comment by studentforcode** [comment]
@Sunny6889 No brother the account has sufficient bandwidth , sorry that i forgot to say , the owner account is multysig , and i am using the owner private key as developer to  to challenge myselft and other respect and vip peoples like you , to see if you can send the fund with out the active account's permission.  

 File "E:\tronwallet\d.py", line 14, in <module>
    .broadcast()
     ~~~~~~~~~^^
  File "C:\Users\j\AppData\Local\Programs\Python\Python313\Lib\site-packages\tronpy\tron.py", line 184, in broadcast
    return TransactionRet(self._client.broadcast(self), client=self._client, method=self._method)
                          ~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\j\AppData\Local\Programs\Python\Python313\Lib\site-packages\tronpy\tron.py", line 1079, in broadcast
    self._handle_api_error(payload)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\j\AppData\Local\Programs\Python\Python313\Lib\site-packages\tronpy\tron.py", line 618, in _handle_api_error
    raise UnknownError(msg, payload["code"])
tronpy.exceptions.UnknownError: ('Account resource insufficient error.', 'BANDWITH_ERROR')

`https://github.com/andelf/tronpy/blob/master/tronpy/tron.py`

please consider https://github.com/tronprotocol/java-tron/issues/5736 .

thanks for your quick reply ..

**Comment by laurenceja** [comment]
> [@Sunny6889](https://github.com/Sunny6889) No brother the account has sufficient bandwidth , sorry that i forgot to say , the owner account is multysig , and i am using the owner private key as developer to challenge myselft and other respect and vip peoples like you , to see if possible we can make transaction this way with out the active account's permission.
> 
> File "E:\tronwallet\d.py", line 14, in .broadcast() ~~~~~~~~~^^ File "C:\Users\j\AppData\Local\Programs\Python\Python313\Lib\site-packages\tronpy\tron.py", line 184, in broadcast return TransactionRet(self._client.broadcast(self), client=self._client, method=self._method) ~~~~~~~~~~~~~~~~~~~~~~^^^^^^ File "C:\Users\j\AppData\Local\Programs\Python\Python313\Lib\site-packages\tronpy\tron.py", line 1079, in broadcast self._handle_api_error(payload) ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^ File "C:\Users\j\AppData\Local\Programs\Python\Python313\Lib\site-packages\tronpy\tron.py", line 618, in _handle_api_error raise UnknownError(msg, payload["code"]) tronpy.exceptions.UnknownError: ('Account resource insufficient error.', 'BANDWITH_ERROR')
> 
> `https://github.com/andelf/tronpy/blob/master/tronpy/tron.py`
> 
> thanks for your quick reply ..

@studentforcode Has your issue been resolved? If not, I will suggest to check the transaction creation process, and [here](https://developers.tron.network/docs/multi-signature-example-process-flow) is the guide about how to send a transaction using different account permission. And if you use the account's owner permission, please check whether the account has enough available bandwidth or TRX.

**Comment by studentforcode** [comment]
@Sunny6889 
No senior , i still not been solve it, before i am using python as suggested , i will sith to . be inform that this is my project completely this year . i will start it today as i am doing nothing this year then . i will update you here. 

thanks and Allah help you muvh brother .

**Comment by lxcmyf** [comment]
@studentforcode 
Hello, The question you raised is not related to the content of this issue. It is suggested to open another issue specifically to discuss the problem you encountered. There will be more professional responses waiting for you.

**Comment by studentforcode** [comment]
@Sunny6889 
Noted and sorry for bad English.
