### ISSUE TITLE
Corruption: corrupted compressed block contents

### ISSUE THREAD

**Issue by leonchuk** [tronprotocol/java-tron#5853]
After updating and rebuilding the node, it stopped syncing at block 61909967 with the error:

```
15:05:14.991 ERROR [sync-handle-block] [DB](Manager.java:1337) Corruption: corrupted compressed block contents
org.tron.core.exception.ValidateSignatureException: Corruption: corrupted compressed block contents
        at org.tron.core.db.Manager.preValidateTransactionSign(Manager.java:1984)
        at org.tron.core.db.Manager.processBlock(Manager.java:1739)
        at org.tron.core.db.Manager.applyBlock(Manager.java:1043)
        at org.tron.core.db.Manager.pushBlock(Manager.java:1329)
        at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:266)
        at org.tron.core.net.service.sync.SyncService.processSyncBlock(SyncService.java:304)
        at org.tron.core.net.service.sync.SyncService.lambda$handleSyncBlock$9(SyncService.java:290)
        at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
        at org.tron.core.net.service.sync.SyncService.handleSyncBlock(SyncService.java:269)
        at org.tron.core.net.service.sync.SyncService.lambda$init$1(SyncService.java:88)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

15:05:14.993 INFO  [sync-handle-block] [DB](PendingManager.java:57) Pending tx size: 0.

15:05:14.993 ERROR [sync-handle-block] [net](TronNetDelegate.java:295) Process block failed, Num:61909967,ID:0000000003b0abcf2ac1e3f669e39810fafa0188378a289ea48e2e28f39e4517, reason: Corruption: corrupted compressed block contents

15:05:14.994 ERROR [sync-handle-block] [net](SyncService.java:307) Process sync block Num:61909967,ID:0000000003b0abcf2ac1e3f669e39810fafa0188378a289ea48e2e28f39e4517 failed, type: 10, bad block
```

After launch, several tens of blocks are synchronized until they reach block 61909967

**Comment by zeusoo001** [comment]
@leonchuk Could you provide the completed log, as well as the java-tron version, jdk version, hardware configuration, startup script information? Thank you.

**Comment by leonchuk** [comment]
> @leonchuk Could you provide the completed log, as well as the java-tron version, jdk version, hardware configuration, startup script information? Thank you.

Ubuntu 22.04.4 LTS
openjdk version "1.8.0_412"
Code version : 4.7.5
[startup.log](https://github.com/user-attachments/files/15783893/startup.log)

now i downloaded the last lite snapshot and the sync goes without errors

**Comment by zeusoo001** [comment]
@leonchuk The database may be corrupted. Where did you get the last database from? How did you stop the node?

**Comment by leonchuk** [comment]
> @leonchuk The database may be corrupted. Where did you get the original database from? How did you stop the node? Is there any physical failure on the machine, such as a sudden shutdown?

Use a script to stop the node:

```
#!/bin/bash
while true; do
  pid=`ps -ef |grep FullNode.jar |grep -v grep |awk '{print $2}'`
  if [ -n "$pid" ]; then
    kill -15 $pid
    echo "The java-tron process is exiting, it may take some time, forcing the exit may cause damage to the database, please wait patiently..."
    sleep 1
  else
    echo "java-tron killed successfully!"
    break
  fi
done
```

Node has been working for half year, this is the first time such a problem.
The provider had technical work, with a temporary shutdown, but I'm not sure what it was at that time.

It is unlikely to be a corrupted database. After each restart of the node, the blocks were loaded and synchronized (about the last 100 before the problematic block), and it was precisely on the node 61909967 that the error constantly occurred

```
15:05:01.758 INFO  [peerWorker-9] [net](P2pEventHandlerImpl.java:168) Receive message from  peer: /116.202.171.24:46036, type: BLOCK
Num:61910083,ID:0000000003b0ac43094e031df35184a1a1f0913e24df5529e095d97bec555737, trx size: 294

15:05:01.759 INFO  [peerClient-46] [net](P2pEventHandlerImpl.java:168) Receive message from  peer: /172.111.38.165:18888, type: BLOCK
Num:61910549,ID:0000000003b0ae1556d6369ec11a29c28578df06b4e89587672f440d867cb732, trx size: 281

15:05:01.759 INFO  [peerClient-17] [net](P2pEventHandlerImpl.java:168) Receive message from  peer: /52.47.129.140:18888, type: BLOCK
Num:61910190,ID:0000000003b0acaebeda137ff48aeccc0106faea080519dccf1e22a51c2de8ff, trx size: 336

15:05:01.760 INFO  [peerWorker-8] [net](P2pEventHandlerImpl.java:168) Receive message from  peer: /95.183.54.138:42736, type: BLOCK
Num:61909967,ID:0000000003b0abcf2ac1e3f669e39810fafa0188378a289ea48e2e28f39e4517, trx size: 198

15:05:01.760 INFO  [peerClient-46] [net](P2pEventHandlerImpl.java:168) Receive message from  peer: /172.111.38.165:18888, type: BLOCK
Num:61910550,ID:0000000003b0ae1654822a8f8535ec5a69ed96092f5b94f91dfc513c7ff11875, trx size: 253

15:05:01.762 INFO  [peerWorker-9] [net](P2pEventHandlerImpl.java:168) Receive message from  peer: /116.202.171.24:46036, type: BLOCK
Num:61910084,ID:0000000003b0ac44aca309421d7fb9f5e7483d36addb5b2895218307ab8f2533, trx size: 210

15:05:01.764 INFO  [peerWorker-8] [net](P2pEventHandlerImpl.java:168) Receive message from  peer: /95.183.54.138:42736, type: BLOCK
Num:61909968,ID:0000000003b0abd05de69c736a78ea85b5e948ed2fedd3fdfcd2adf40f0f904c, trx size: 234
```
**15:05:01.760 INFO  [peerWorker-8] [net](P2pEventHandlerImpl.java:168) Receive message from  peer: /95.183.54.138:42736, type: BLOCK
Num:61909967,ID:0000000003b0abcf2ac1e3f669e39810fafa0188378a289ea48e2e28f39e4517, trx size: 198**


The recent snapshot (from 3.219.199.168) still synced and everything works fine

**Comment by zeusoo001** [comment]
@leonchuk Abnormally stopping a node may cause database corruption, which may lead to failure in the execution of a future block.
