### ISSUE TITLE
tron prod sync fullnode block stop

### ISSUE THREAD

**Issue by iwindx** [tronprotocol/java-tron#5901]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [Discord](https://discord.gg/cGKSsRVCGm) or [Telegram](https://t.me/TronOfficialDevelopersGroupEn).

![image](https://github.com/tronprotocol/java-tron/assets/16376649/e86593b2-1bb4-4c8b-bcec-e70c41ee089e)

fullnode tron.log 
``` error
org.tron.core.exception.ReceiptCheckErrException: different resultCode txId: e729bf16841aed03eca5e6a95511c17685c7de0313b3f2d3ed899097cbcae298, expect: SUCCESS, actual: OUT_OF_TIME
	at org.tron.core.db.TransactionTrace.check(TransactionTrace.java:342)
	at org.tron.core.db.Manager.processTransaction(Manager.java:1482)
	at org.tron.core.db.Manager.processBlock(Manager.java:1759)
	at org.tron.core.db.Manager.applyBlock(Manager.java:1043)
	at org.tron.core.db.Manager.pushBlock(Manager.java:1329)
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:266)
	at org.tron.core.net.service.sync.SyncService.processSyncBlock(SyncService.java:304)
	at org.tron.core.net.service.sync.SyncService.lambda$handleSyncBlock$9(SyncService.java:290)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.tron.core.net.service.sync.SyncService.handleSyncBlock(SyncService.java:269)
	at org.tron.core.net.service.sync.SyncService.lambda$init$1(SyncService.java:88)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

06:24.832 INFO  [sync-handle-block] [DB](PendingManager.java:57) Pending tx size: 0.
00:06:24.833 ERROR [sync-handle-block] [net](TronNetDelegate.java:295) Process block failed, Num:63133112,ID:0000000003c355b83071da22c0a1d3f3a4f80cd7f1b600aaa94834869a677a45, reason: different resultCode txId: e729bf16841aed03eca5e6a95511c17685c7de0313b3f2d3ed899097cbcae298, expect: SUCCESS, actual: OUT_OF_TIME


01:06:47.194 ERROR [sync-handle-block] [DB](Manager.java:1337) different resultCode txId: e729bf16841aed03eca5e6a95511c17685c7de0313b3f2d3ed899097cbcae298, expect: SUCCESS, actual: OUT_OF_TIME
org.tron.core.exception.ReceiptCheckErrException: different resultCode txId: e729bf16841aed03eca5e6a95511c17685c7de0313b3f2d3ed899097cbcae298, expect: SUCCESS, actual: OUT_OF_TIME
	at org.tron.core.db.TransactionTrace.check(TransactionTrace.java:342)
	at org.tron.core.db.Manager.processTransaction(Manager.java:1482)
	at org.tron.core.db.Manager.processBlock(Manager.java:1759)
	at org.tron.core.db.Manager.applyBlock(Manager.java:1043)
	at org.tron.core.db.Manager.pushBlock(Manager.java:1329)
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:266)
	at org.tron.core.net.service.sync.SyncService.processSyncBlock(SyncService.java:304)
	at org.tron.core.net.service.sync.SyncService.lambda$handleSyncBlock$9(SyncService.java:290)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.tron.core.net.service.sync.SyncService.handleSyncBlock(SyncService.java:269)
	at org.tron.core.net.service.sync.SyncService.lambda$init$1(SyncService.java:88)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

```

full node Start command
deploy_tron.sh download url : wget https://raw.githubusercontent.com/tronprotocol/TronDeployment/master/deploy_tron.sh -O deploy_tron.sh
bash deploy_tron.sh --app FullNode --net mainnet

**Comment by iwindx** [comment]
tron.log Complete log download url:
http://82.208.20.80/static/log/tron.log

**Comment by halibobo1205** [comment]
For OUT_OF_TIME error :
Increase the time tolerance of verification transactions
Increase the value of the `maxTimeRatio` configuration item in the node configuration file to 20.0 or higher(max 100.0).

vm = {
supportConstant = false
minTimeRatio = 0.0
maxTimeRatio = 20.0
saveInternalTx = false
}
