### ISSUE TITLE
Node stuck at height 64039423

### ISSUE THREAD

**Issue by alecalve** [tronprotocol/java-tron#5950]
#### Software Versions
```
OS : docker image ubuntu:20.04
JVM : JDK 8
Version : 4.7.5
```

#### Expected behaviour

We'd expect the node to sync.

#### Actual behaviour

Logs show:

```
14:37:57.277 ERROR [sync-handle-block] [DB](Manager.java:1337) delegateBalance must be less than or equal to available FreezeBandwidthV2 balance
org.tron.core.exception.ContractValidateException: delegateBalance must be less than or equal to available FreezeBandwidthV2 balance
	at org.tron.core.actuator.DelegateResourceActuator.validate(DelegateResourceActuator.java:167)
	at org.tron.common.runtime.RuntimeImpl.execute(RuntimeImpl.java:63)
	at org.tron.core.db.TransactionTrace.exec(TransactionTrace.java:189)
	at org.tron.core.db.Manager.processTransaction(Manager.java:1469)
	at org.tron.core.db.Manager.processBlock(Manager.java:1759)
	at org.tron.core.db.Manager.applyBlock(Manager.java:1043)
	at org.tron.core.db.Manager.pushBlock(Manager.java:1329)
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:266)
	at org.tron.core.net.service.sync.SyncService.processSyncBlock(SyncService.java:304)
	at org.tron.core.net.service.sync.SyncService.lambda$handleSyncBlock$9(SyncService.java:290)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.tron.core.net.service.sync.SyncService.handleSyncBlock(SyncService.java:269)
	at org.tron.core.net.service.sync.SyncService.lambda$init$1(SyncService.java:88)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
14:37:57.277 ERROR [sync-handle-block] [net](TronNetDelegate.java:295) Process block failed, Num:64039423,ID:0000000003d129ff3ad75ff1dcaf02eac45459f5afe83668f5b4b7b73b7b3d27, reason: delegateBalance must be less than or equal to available FreezeBandwidthV2 balance
14:37:57.277 ERROR [sync-handle-block] [net](SyncService.java:307) Process sync block Num:64039423,ID:0000000003d129ff3ad75ff1dcaf02eac45459f5afe83668f5b4b7b73b7b3d27 failed, type: 10, bad block
```

**Comment by xxo1shine** [comment]
> What should we do in this case? Re-sync completely?

@alecalve  The database may be damaged. You can download the latest database from here https://developers.tron.network/docs/main-net-database-snapshots

**Comment by vivian1912** [comment]
@alecalve May I ask if this issue has been resolved? If yes, this issue will be closed later and please feel free to re-open it if you still see the issue, thanks.
