### ISSUE TITLE
Sync never completes, Error in tron.log file

### ISSUE THREAD

**Issue by iiimoon** [tronprotocol/java-tron#809]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Started the process using the command

java -jar java-tron.jar -p <my privite key>  --witness -c /tmp/java-tron/config.conf & disown 

2. What did you expect to see?

I should see sync complete and new block generated 

3. What did you see instead?

It's hung at height 91 from last 20+ hours.  I see following error in the logs but not sure if it's related, I did not get chance to check the code

01:32:02.964 ERROR [pool-8-thread-1] [o.t.c.d.Manager](Manager.java:780) start time should be greater than HeadBlockTime
org.tron.core.exception.ContractValidateException: start time should be greater than HeadBlockTime
	at org.tron.core.actuator.AssetIssueActuator.validate(AssetIssueActuator.java:141)
	at org.tron.core.db.Manager.processTransaction(Manager.java:927)
	at org.tron.core.db.Manager.processBlock(Manager.java:1086)
	at org.tron.core.db.Manager.applyBlock(Manager.java:619)
	at org.tron.core.db.Manager.pushBlock(Manager.java:775)
	at org.tron.core.net.node.NodeDelegateImpl.handleBlock(NodeDelegateImpl.java:59)
	at org.tron.core.net.node.NodeImpl.processSyncBlock(NodeImpl.java:787)
	at org.tron.core.net.node.NodeImpl.lambda$handleSyncBlock$26(NodeImpl.java:560)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.tron.core.net.node.NodeImpl.handleSyncBlock(NodeImpl.java:547)
	at org.tron.core.net.node.NodeImpl.lambda$activeTronPump$9(NodeImpl.java:416)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by deblanco** [comment]
I'm on the same situation, blocked at height 91

**Comment by iiimoon** [comment]
Thanks, its working fine now, sync is in progress
