### ISSUE TITLE
[BOUNTY] - Unhandled exception Witness Manager

### ISSUE THREAD

**Issue by jerkyrs** [tronprotocol/java-tron#835]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Run witness node on from Master commit c4f4e1ff08ce67aa50029aa6352c2940b497a863

2. What did you expect to see?

No Error

3. What did you see instead?
```
07:58:49.044 ERROR [pool-6-thread-1] [o.t.c.n.n.NodeImpl](NodeImpl.java:418) Unhandled exception
java.lang.NullPointerException: null
        at org.tron.core.db.Manager.updateSignedWitness(Manager.java:1161)
        at org.tron.core.db.Manager.processBlock(Manager.java:1075)
        at org.tron.core.db.Manager.applyBlock(Manager.java:601)
        at org.tron.core.db.Manager.pushBlock(Manager.java:757)
        at org.tron.core.net.node.NodeDelegateImpl.handleBlock(NodeDelegateImpl.java:59)
        at org.tron.core.net.node.NodeImpl.processSyncBlock(NodeImpl.java:786)
        at org.tron.core.net.node.NodeImpl.lambda$handleSyncBlock$26(NodeImpl.java:559)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at org.tron.core.net.node.NodeImpl.handleSyncBlock(NodeImpl.java:546)
        at org.tron.core.net.node.NodeImpl.lambda$activeTronPump$9(NodeImpl.java:415)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by zhaohong** [comment]
@olenheim  follow this

**Comment by jerkyrs** [comment]
This happens with an extra comma in witnesses 

```
  witnesses = [
    {
      address: 27hFJd22fcjyoU6J7speJRorbMqJQKT4A3B,
      url= "http://hacker.com",
      voteCount = 10000
    },
  ]
```

**Comment by olenheim** [comment]
OK, we will check config in the next version

**Comment by marcusyanghe** [comment]
Hi, @jerkyrs 
I am pleased to inform you that you are rewarded TRX from Tron Foundation for your contribution in our Bug Bounty Program in May 2018. Please provide a valid account address that can receive the TRX reward.
Please send the address to my email yanghe@tron.network so we can deliver the TRX on time.
Thanks,
Marcus Yang

**Comment by jerkyrs** [comment]
@tronmarcus @marcusyanghe i sent email from s********es@k******.com
